mozilla-bteam/bmo

Bugzilla/Template.pm, extensions/MyDashboard/web/js/query.js, js/global.js
Insert `<wbr>` to bug summaries on My Dashboard, just like regular bug lists and bug page, so the query table won’t overlap with the request tables. This also applies the `<wbr>` hack to all uppercase + camel case symbols such as `MOZILLA_PKIX_ERROR_ADDITIONAL_POLICY_CONSTRAINT_FAILED`. Updated the Perl implementation along with the new JavaScript helper function. Tested previously regressed cases to make sure the change won’t break them again.
[Bug 929502 - bugs with very long but unwrappable summaries cause the tables to overlap when the window is small](https://bugzilla.mozilla.org/show_bug.cgi?id=929502)
=> Bug 929502 - bugs with very long but unwrappable summaries cause the tables to overlap when the window is small

extensions/BMO/web/js/firefox-crash-table.js, extensions/BMO/web/styles/bug_modal.css
Fix the size of the Crash Signature `<textarea>` plus the position of the Update status flags button in the Crash Data section.
[Bug 1557360 - Crash Signature textbox is too narrow](https://bugzilla.mozilla.org/show_bug.cgi?id=1557360)
=> Bug 1557360 - Crash Signature textbox is too narrow

extensions/BMO/web/js/sorttable.js
The legacy `forEach` polyfill that comes with [sorttable.js](https://github.com/mozilla-bteam/bmo/blob/master/extensions/BMO/web/js/sorttable.js) needs to be removed. `Array`/`String` generics have been [deprecated since Firefox 53](https://www.fxsitecompat.com/en-CA/docs/2016/non-standard-array-string-generics-have-been-deprecated/) and will be removed in the near future.
=> Bug 1540425 - Remove Array.forEach from sorttable.js

extensions/PhabBugz/lib/Feed.pm, extensions/PhabBugz/lib/Revision.pm
Bugzilla Link:
[Bug 1556836 - Feed daemon needs to add security-revision and bmo security tags back to revision if removed by user or other process](https://bugzilla.mozilla.org/show_bug.cgi?id=1556836)
=> Bug 1556836 - Feed daemon needs to add security-revision and bmo security tags back to revision if removed by user or other process

extensions/BugModal/web/bug_modal.js
Show the regular user menu when clicking a CC member on the modal UI instead of triggering the `mailto:` link itself.
[Bug 1362951 - CC list implies there's a drop-down menu, but clicking the dropdown button treats it as send email](https://bugzilla.mozilla.org/show_bug.cgi?id=1362951)
=> Bug 1362951 - CC list implies there's a drop-down menu, but clicking the dropdown button treats it as send email

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1557779" target="_blank">1557779</a>] OAuth flow broken when user is not already logged in *and* uses duo auth</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1557186" target="_blank">1557186</a>] No official documentation for relative dates</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1557726" target="_blank">1557726</a>] Remove author column from Phabricator table to avoid revision owner vs. commit author confusion</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1540425" target="_blank">1540425</a>] Remove Array.forEach from sorttable.js</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1558494" target="_blank">1558494</a>] Fix some more issues in the …
=> Bump version to 20190613.1

extensions/BugModal/template/en/default/bug_modal/new_comment.html.tmpl
Show the “Never email me about this bug” checkbox on the modal UI not only in the edit mode but also in the view mode. It was visible by default on the legacy UI, so it’s considered as a regression.
[Bug 1317224 - Option 'Ignore Bug Mail' is hidden by default on modal UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1317224)
=> Bug 1317224 - Option 'Ignore Bug Mail' is hidden by default on modal UI

scripts/build-useragent-blocking-regex.pl
When chatting with dkl, I realized this script didn't exist in BMO but it has
been used to enable the user agent blocking regex.
It must be run from the same perl as production (5.10).
=> no bug - add script to rebuild the useragent blocking regex

skins/standard/global.css
Fix a small UI glitch in the Requests dropdown that can be seen when there’s a secure bug. `@supports` allows to support both the latest and old browsers.
[Bug 1559830 - Second line in the Requests dropdown is partially cut if there is secure bug icon](https://bugzilla.mozilla.org/show_bug.cgi?id=1559830)
=> Bug 1559830 - Second line in the Requests dropdown is partially cut if there is secure bug icon

Bugzilla/Bug.pm, Bugzilla/Hook.pm, Bugzilla/WebService/Bug.pm, extensions/EditComments/Extension.pm
Add comment revisions to the bug history page and API. Also add comment tag changes to the bug history API.
[Bug 1512497 - Comment editing should be listed on the bug history page and API](https://bugzilla.mozilla.org/show_bug.cgi?id=1512497)
=> Bug 1512497 - Comment editing should be listed on the bug history page and API

enter_bug.cgi, template/en/default/bug/create/create.html.tmpl
Use the defect bug type for a regression by default when the URL param contains `regressed_by`.
[Bug 1560133 - Bug filed as a regression should be given type "defect”](https://bugzilla.mozilla.org/show_bug.cgi?id=1560133)
=> Bug 1560133 - Bug filed as a regression should be given type "defect"

skins/standard/dependency-tree.css
Fix wrong indentation on the dependency tree. With the current indent, child bugs may look like on the same level as their parent depending on the grouping. 
Fixed screenshot of [Bug 1451850 dependency tree](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1451850&hide_resolved=1):
=> no bug - Fix indent on dependency tree

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl, extensions/BugModal/web/bug_modal.js
This is a bug due to confusion between the comment ID and comment count. Just make sure which is which.
[Bug 1545002 - Clicking on "Reply to this comment" on a private comment should automatically check the private checkbox](https://bugzilla.mozilla.org/show_bug.cgi?id=1545002)
=> Bug 1545002 - Clicking on "Reply to this comment" on a private comment should automatically check the private checkbox

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl, extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl, extensions/BugModal/template/en/default/bug_modal/field.html.tmpl, extensions/BugModal/template/en/default/bug_modal/navigate.html.tmpl, extensions/BugModal/template/en/default/bug_modal/new_comment.html.tmpl, extensions/BugModal/web/comments.js, extensions/EditComments/template/en/default/hook/bug_modal/activity_stream-comment_action.html.tmpl, extensions/Needinfo/template/en/default/bug/needinfo.html.tmpl, template/en/default/global/userselect.html.tmpl
Improve UX for screen reader users by adding missing labels, removing redundant labels, and adding `role="presentation”` to layout tables. I’ll keep this blocked so we can gather some feedback during All Hands.
[Bug 1558096 - [a11y] Fix remaining accessibility issues on modal UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1558096)
=> Bug 1558096 - [a11y] Fix remaining accessibility issues on modal UI

Bugzilla.pm, Bugzilla/Extension.pm, Bugzilla/Hook.pm, Bugzilla/Template/Context.pm, extensions/Push/Extension.pm, extensions/RestrictComments/Extension.pm
Every hook is $NUMBER_OF_HOOKS calls to `->can()`.
Some hooks can be called thousands of times per request, or more.
This patch changes how Bugzilla::Hook works. After all extensions are
loaded, the list of packages is passed to Bugzilla::Hook::finalize,
which builds a cache that maps hook names to lists of functions.
Calling a hook is just simple iteration over that list, which is much
faster. In addition, unused hooks have virtually no cost.
=> Bug 1559988 - Make extension hooks faster

Bugzilla/Hook.pm, Bugzilla/Search.pm, extensions/BMO/Extension.pm, extensions/BMO/template/en/default/hook/global/user-error-errors.html.tmpl
Allow to use Firefox release date pronouns for date fields, including `%LAST_MERGE_DATE%`, `%LAST_RELEASE_DATE%` and `%LAST_SOFTFREEZE_DATE%`, in advanced search queries. These dates are from [`firefox_versions.json`](https://product-details.mozilla.org/1.0/firefox_versions.json).
[Bug 1531968 - Allow to search bugs by Firefox merge dates](https://bugzilla.mozilla.org/show_bug.cgi?id=1531968)
=> Bug 1531968 - Allow to search bugs by Firefox merge dates

extensions/BugModal/web/bug_modal.js
When large text data like `about:support` or network log is pasted into the comment box, provide an option to upload it as an attachment.
[Bug 1559039 - Suggest that a user uses an attachment when a comment is very long](https://bugzilla.mozilla.org/show_bug.cgi?id=1559039)
=> Bug 1559039 - Suggest that a user uses an attachment when a comment is very long

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1317224" target="_blank">1317224</a>] Option 'Ignore Bug Mail' is hidden by default on modal UI</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1559830" target="_blank">1559830</a>] Second line in the Requests dropdown is partially cut if there is secure bug icon</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1543700" target="_blank">1543700</a>] Reimplememt Custom Search UI on Advanced Search page</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1546788" target="_blank">1546788</a>] Deselect bug type by default unless component-specific type is defined</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1512497" target="_blank">1512497</a>] Comment editing should be …
=> Bump version to 20190627.1

template/en/default/search/custom-search.html.tmpl
Fix the Custom Search UI not working when a user-defined query is passed via URL params, especially from the Edit Search link. It’s likely due to my bad Replace All during the development.
[Bug 1562139 - "Edit Search" broken](https://bugzilla.mozilla.org/show_bug.cgi?id=1562139)
=> Bug 1562139 - "Edit Search" broken

.circleci/config.yml, scripts/entrypoint.pl
Needed to not run script to create legacy QA data when running from conduit-suite or other modes. It should only run when running the webservices and selenium tests in CircleCI.
=> no bug - Do not create qa data if not running qa tests

extensions/BugModal/template/en/default/bug/show-modal.html.tmpl, post_bug.cgi, process_bug.cgi, qa/t/lib/QA/Util.pm, qa/t/test_bug_edit.t, qa/t/test_qa_contact.t, show_bug.cgi, template/en/default/bug/choose.html.tmpl, template/en/default/bug/process/bugmail.html.tmpl, template/en/default/bug/show.html.tmpl
With this PR post_bug.cgi and process_bug.cgi now redirect to show_bug.cgi after successfully creating/updating a bug successfully. They no longer attempt to render the show_bug page themselves, making things more consistent and less buggy.
These changes work for both the bug-modal UI and the old bug UI.
See #1085 for the update to attachments. This PR should be merged first then that one immediately afterward.
=> Bug 1524174 - Redirect to show_bug.cgi after creating bug or updating a bug

extensions/Needinfo/template/en/default/bug/needinfo.html.tmpl
Fix a wrong label for requesting info.
[Bug 1563269 - Stray "from" when redirecting needinfo](https://bugzilla.mozilla.org/show_bug.cgi?id=1563269)
=> Bug 1563269 - Stray "from" when redirecting needinfo

extensions/UserProfile/template/en/default/pages/user_profile.html.tmpl
[Bug 1562804 - status NEW is not present in the status changed section in a bugzilla user profile](https://bugzilla.mozilla.org/show_bug.cgi?id=1562804)
=> Bug 1562804 - status NEW is not present in the status changed section in a bugzilla user profile

extensions/Bitly/web/js/bitly.js, extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl, extensions/BugModal/web/bug_modal.css, extensions/BugModal/web/bug_modal.js, extensions/BugModal/web/comments.js, extensions/ComponentWatching/web/js/overlay.js, extensions/EditComments/web/js/inline-editor.js, extensions/EditComments/web/js/revisions.js, extensions/FlagTypeComment/web/js/ftc.js, extensions/GuidedBugEntry/web/js/guided.js, extensions/MyDashboard/lib/WebService.pm, extensions/MyDashboard/web/js/flags.js, extensions/MyDashboard/web/js/query.js, extensions/PhabBugz/web/js/phabricator.js, extensions/ProdCompSearch/web/js/prod_comp_search.js, extensions/REMO/web/js/payment.js, extensions/Review/web/js/review_history.js, js/account.js, js/bug.js, js/comment-tagging.js, js/field.js, js/global.js, js/instant-search.js, js/util.js, template/en/default/bug/show-header.html.tmpl, template/en/default/global/header.html.tmpl
* Implement the `Bugzilla.API` class offering REST API utility methods that replace `bugzilla_ajax()` originally from `bug_modal.js`
* Use the new, simple utility methods for all the REST API calls
* Replace all the JSON-RPC calls with REST API 🎉 
* Generate an API token on all pages so it can be used for new features on the global header (but the token auth support will be removed soon; see the Notes below)
* Tested everything locally except for the PhabBugz review list on My Dashboard, which requires API access
* The `Bugzilla_api_token` param, now appended in `Bugzilla.API._init()`, will be [removed soon](https://bugzilla.mozilla.org/show_bug.cgi?id=1477163) in favour of login cookies
[Bug 1380437 - Implement REST API utility methods in global.js to replace bugzilla_ajax(), eliminate …
=> Bug 1380437 - Implement REST API utility methods in global.js to replace bugzilla_ajax(), eliminate JSON-RPC usage

attachment.cgi, extensions/BugModal/template/en/default/bug/show-modal.html.tmpl, template/en/default/bug/process/attachment-results.html.tmpl, template/en/default/bug/show.html.tmpl
- Includes changes from https://github.com/mozilla-bteam/bmo/pull/1068 until that gets merged.
- This PR depends on #1065 being merged.
- As the title suggests this causes BMO to redirect when attachments are created/updated/deleted. This lets us have 1 point (show_bug.cgi) that actually renders the show bug page.
- This works for the bug modal UI and the old UI.
-  ~~TODO: Determine how to handle large recipient lists which won't fit in flash storage.~~ Solved by just listing how many people were emailed.
=> Bug 1524175 - Redirect to show_bug.cgi after creating or updating an attachment

Bugzilla/DB/Mysql.pm, Bugzilla/DB/Oracle.pm, Bugzilla/DB/Pg.pm, Bugzilla/DB/Sqlite.pm, Bugzilla/Flag.pm, extensions/BMO/lib/Reports/UserActivity.pm, extensions/InlineHistory/Extension.pm, request.cgi
This is due to a wrong date comparison between `%Y-%m-%d` (hyphens) and `%Y.%m.%d` (dots) in [`find_activity_id_for_flag()`](https://github.com/mozilla-bteam/bmo/blob/master/extensions/BugModal/lib/ActivityStream.pm#L97-L128). Use `%Y-%m-%d` intensively to solve the issue.
[Bug 1563312 - Needinfo links at top of bug goes to #c0 rather than relevant comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1563312)
=> Bug 1563312 - Needinfo links at top of bug goes to #c0 rather than relevant comment

extensions/BMO/web/js/advanced-search.js, js/advanced-search.js, js/field.js, qa/t/test_bug_edit.t, skins/standard/search_form.css, template/en/default/search/form.html.tmpl
* <del>Select **[Bug creation]** by default because people sometimes forget to select a field name and unexpected results will be returned. It will be simply ignored unless a date range is specified</del>
* Mark `<select name="chfield">` required when a date range is specified
* Remove inline script from the section (and eventually from the entire Advanced Search page)
* Add a link to the relative dates doc being added in #1320
[Bug 1557799 - Search By Change History: date range is ignored when field is not specified](https://bugzilla.mozilla.org/show_bug.cgi?id=1557799)
=> Bug 1557799 - Search By Change History: date range is ignored when field is not specified

js/util.js
Forgot to have this in #665. `BUGZILLA.api_token` will be empty for logged-out users, and sending an empty token will lead to a 400 Bad Request. The `Bugzilla_api_token` param should be set only when the token is given. Some features require an API key, and the API will return an error anyway in such cases.
=> Bug 1380437 follow-up - Send API token only if available

extensions/GuidedBugEntry/template/en/default/guided/guided.html.tmpl
Add required radio buttons on the guided bug entry form to ask if the bug is defect or enhancement, rather than using the defect type for all new bugs.
[Bug 1565741 - Let users choose defect or enhancement on guided bug entry form](https://bugzilla.mozilla.org/show_bug.cgi?id=1565741)
=> Bug 1565741 - Let users choose defect or enhancement on guided bug entry form

Bugzilla/Search.pm
Allow to use product/component pairs like “Core::General, IPC” for the Component field in Custom Search. This also works with simple queries like `buglist.cgi?component=Core%3A%3AGeneral&component=IPC`.
[Bug 1541898 - Allow to search on product/component pair](https://bugzilla.mozilla.org/show_bug.cgi?id=1541898)
=> Bug 1541898 - Allow to search on product/component pair

Bugzilla/Field.pm, Bugzilla/Search.pm, js/advanced-search.js, query.cgi, template/en/default/global/field-descs.none.tmpl
Allow to do custom searches like 
* `Whatever / changed by / foo@bar.org`
* `Whatever / changed after / -1m`
[Bug 1533717 - Add a search keyword "Whatever"](https://bugzilla.mozilla.org/show_bug.cgi?id=1533717)
=> Bug 1533717 - Add a search keyword "Whatever"

Bugzilla/User/Setting.pm, extensions/BugModal/Extension.pm, extensions/BugModal/template/en/default/hook/global/setting-descs-settings.none.tmpl, scripts/entrypoint.pl
Remove the “experimental UI” setting and always use the modal UI. Goodbye legacy!
Blocked by #1334 and @emceeaich’s “intent to change” email.
[Bug 1273046 - Disable the legacy non-modal bug UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1273046)
=> Bug 1273046 - Disable the legacy non-modal bug UI

Bugzilla/Bug.pm
This bug turned out to be due to an error in SQL, though it doesn’t look like a recent regression. And I don’t know why it only happens to some people.
> DBD::mysql::db selectall_arrayref failed: Column 'bug_when' in where clause is ambiguous
`bug_when` is an alias column so it cannot be used in `where` clauses as is. Adding an outer table to work around the issue.
[Bug 1562651 - My Dashboard broken, reporting "Failed to load last changes from Bugzilla"](https://bugzilla.mozilla.org/show_bug.cgi?id=1562651)
=> Bug 1562651 - My Dashboard broken, reporting "Failed to load last changes from Bugzilla"

enter_bug.cgi, extensions/GuidedBugEntry/web/js/guided.js, post_bug.cgi
Stop storing the Firefox version in a cookie and reusing it on the New Bug page, because it confuses users. With this change, the product’s default version (currently undefined) will be used. The client version won’t be used, because the Version field is almost deprecated in favour of status flags.
[Bug 1565319 - FF Version selection does not update from client version, shows previous reported version](https://bugzilla.mozilla.org/show_bug.cgi?id=1565319)
=> Bug 1565319 - FF Version selection does not update from client version, shows previous reported version

extensions/BugModal/web/bug_modal.css, extensions/BugModal/web/comments.js, skins/standard/global.css
Fix the Home/End key scrolling issue by:
* Removing the smooth scrolling effect from CSS (Note: smooth scrolling remains in effect depending on the browser setting, but it’s OK)
* Changing the way inline attachments are rendered: Create a placeholder first and render lazily, so the scroll position won’t change due to the content being pushed down
[Bug 1563360 - End key does not scroll all the way to the bottom of BMO page](https://bugzilla.mozilla.org/show_bug.cgi?id=1563360)
=> Bug 1563360 - End key does not scroll all the way to the bottom of BMO page

extensions/BMO/template/en/default/global/choose-product.html.tmpl, extensions/BMO/web/styles/choose_product.css
Optimize the layout for wider monitors. The following screenshot is 1280x1280.
[Bug 1567571 - Make featured product list 3+ columns](https://bugzilla.mozilla.org/show_bug.cgi?id=1567571)
=> Bug 1567571 - Make featured product list 3+ columns

extensions/Bitly/web/js/bitly.js
Fix a shorten URL not generated when the popup comes up. Looks like the callback for the `bPopup()` jQuery plug-in doesn’t accept an `async` function, so use a regular function as a wrapper to work around the issue.
[Bug 1568259 - Short URL generation isn't working](https://bugzilla.mozilla.org/show_bug.cgi?id=1568259)
=> Bug 1568259 - Short URL generation isn't working

template/en/default/bug/create/create.html.tmpl
The bug comment is prefilled when the `comment` URL param is given or a bug is cloned. In such cases, the comment should not be replaced by the (empty) description template of the component. Add a proper check to avoid the issue.
[Bug 1568863 - Prefilled comment will be wiped after changing component](https://bugzilla.mozilla.org/show_bug.cgi?id=1568863)
=> Bug 1568863 - Prefilled comment will be wiped after changing component

Bugzilla/Search.pm
Oops! This doesn’t throw any exception but is obviously wrong [:?](https://www.urbandictionary.com/define.php?term=%3A%3F)
=> no bug - Fix an error in regex

extensions/BugModal/web/bug_modal.js
Fix the weird behaviours of the jQuery tooltip widget.
* Wrong position: This is because the tooltip is always inserted to `<body>`. Moving to a proper scroll parent and recalculate the position to solve the issue.
* Reappears after switching tabs: This is because the tooltip is displayed whenever the source element gets focus, which include the time when the window/tab gets focus. Temporarily disable the tooltip functionality in such cases to solve the issue.
[Bug 1533269 - Tooltip displayed at wrong position when page is zoomed or scrolled, and reappears after switching back tab](https://bugzilla.mozilla.org/show_bug.cgi?id=1533269)
=> Bug 1533269 - Tooltip displayed at wrong position when page is zoomed or scrolled, and reappears after switching back tab

extensions/BugModal/web/bug_modal.css, skins/standard/buglist.css, skins/standard/global.css
Show the hand/pointer cursor while hovering a button just like what the legacy Sandstone skin did. Also use the hand cursor for other actionable widgets including dropdown lists, radio buttons, checkboxes, tabs and menu items for consistency.
[Bug 1555508 - Cursor does not change to hand (cursor: pointer) when mouse is over "Edit Bug" or "Save Changes" buttons](https://bugzilla.mozilla.org/show_bug.cgi?id=1555508)
=> Bug 1555508 - Cursor does not change to hand (cursor: pointer) when mouse is over "Edit Bug" or "Save Changes" buttons

extensions/MyDashboard/web/js/flags.js, extensions/MyDashboard/web/js/query.js
Show a simple error message inline instead of using `alert()`. Note: `fetch()` throws a generic `TypeError` instead of an `AbortError` when the user navigates manually, so it’s difficult to know if the request is aborted.
[Bug 1569194 - My Dashboard shows Unexpected Error dialog when request is aborted while loading](https://bugzilla.mozilla.org/show_bug.cgi?id=1569194)
=> Bug 1569194 - My Dashboard shows Unexpected Error dialog when request is aborted while loading

Bugzilla/Search.pm
Convert invalid search condition “Resolution / is (not) equal to / ---“ to “Resolution / is (not) empty” internally so users can get expected results.
[Bug 1568704 - Allow to use --- as empty Resolution field value in Custom Search](https://bugzilla.mozilla.org/show_bug.cgi?id=1568704)
=> Bug 1568704 - Allow to use --- as empty Resolution field value in Custom Search

docs/en/rst/api/core/v1/general.rst
Update the [API document](https://bmo.readthedocs.io/en/latest/api/core/v1/general.html) to clarify what happens when a too long URL is given.
[Bug 1569130 - Explain in the API doc that Bugzilla returns a 302 redirect when the query string is > 10 KB](https://bugzilla.mozilla.org/show_bug.cgi?id=1569130)
=> Bug 1569130 - Explain in the API doc that Bugzilla returns a 302 redirect when the query string is > 10 KB

skins/standard/global.css
Update the toggle button design to make the selected item distinguishable when using a high contrast system theme, and to make it less distracting in a normal theme. A [screenshot](https://bug1545331.bmoattachments.org/attachment.cgi?id=9082139) is attached in the bug.
[Bug 1545331 - I can't see which of defect/enhancment/task is currently selected during editing](https://bugzilla.mozilla.org/show_bug.cgi?id=1545331)
=> Bug 1545331 - I can't see which of defect/enhancment/task is currently selected during editing

Bugzilla/Hook.pm, Bugzilla/Search.pm, Bugzilla/WebService/Constants.pm, extensions/BMO/Extension.pm, template/en/default/global/user-error.html.tmpl
The current date pronoun support is incomplete because pronouns can be used only for certain date fields. This allows to use a pronoun for any other field in conjunction with the changed before/after operator, and shows a proper error if it’s not a valid pronoun.
[Bug 1568695 - Allow to use merge date pronouns with changed before/after operator](https://bugzilla.mozilla.org/show_bug.cgi?id=1568695)
=> Bug 1568695 - Allow to use merge date pronouns with changed before/after operator

Bugzilla/Constants.pm
Support `font/*` as a legal content type.
[Bug 1571129 - Allow attaching font/* content types](https://bugzilla.mozilla.org/show_bug.cgi?id=1571129)
=> Bug 1571129 - Allow attaching font/* content types

extensions/Needinfo/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl
Use the `needinfo_from` URL param, if exists, to prefill the needinfo field. The string is HTML-filtered in `userselect.html.tmpl` so no filter here.
[Bug 1571572 - Allow to prefill needinfo field on the Enter Bug page](https://bugzilla.mozilla.org/show_bug.cgi?id=1571572)
=> Bug 1571572 - Allow to prefill needinfo field on the Enter Bug page

Bugzilla/Bug.pm, Bugzilla/Config/BugFields.pm, Bugzilla/Field.pm, Bugzilla/WebService/Bug.pm, Bugzilla/WebService/Constants.pm, docs/en/rst/administering/parameters.rst, docs/en/rst/api/core/v1/bug.rst, docs/en/rst/api/core/v1/bugzilla.rst, extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl, extensions/BugModal/template/en/default/bug_modal/field.html.tmpl, js/field.js, qa/t/lib/QA/Tests.pm, qa/t/webservice_bug_create.t, qa/t/webservice_bug_fields.t, qa/t/webservice_bug_get.t, qa/t/webservice_bug_get_bugs.t, qa/t/webservice_bug_search.t, template/en/default/admin/params/bugfields.html.tmpl, template/en/default/bug/create/create.html.tmpl, template/en/default/bug/field-label.html.tmpl, template/en/default/bug/field.html.tmpl, template/en/default/global/user-error.html.tmpl
Add an admin param for requiring the bug type field. Return an error if it’s required but not specified when the user files a new bug through the API (and UI, though it already makes the field required with HTML/JavaScript).
[Bug 1562364 - Enforce setting bug type when creating bug through API](https://bugzilla.mozilla.org/show_bug.cgi?id=1562364).
=> Bug 1562364 - Enforce setting bug type when creating bug through API

extensions/GoogleAnalytics/template/en/default/hook/global/header-additional_header.html.tmpl, extensions/GoogleAnalytics/template/en/default/hook/global/header-start.html.tmpl, extensions/GoogleAnalytics/web/js/analytics.js
* <del>Start logging actual URLs instead of template names. The query params will also be logged except for sensitive tokens and user-specific bug list IDs</del>
* Start logging users’ logged-in/out status using a [custom dimention](https://support.google.com/analytics/answer/2709828)
* Start logging insiders while prevent security/private bugs being logged
* Remove jQuery dependency
[Bug 1529406 - Record user’s logged-in/out status and track insiders with Google Analytics](https://bugzilla.mozilla.org/show_bug.cgi?id=1529406)
=> Bug 1529406 - Record user’s logged-in/out status and track insiders with Google Analytics

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1555508" target="_blank">1555508</a>] Cursor does not change to hand (cursor: pointer) when mouse is over "Edit Bug" or "Save Changes" buttons</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1569194" target="_blank">1569194</a>] My Dashboard shows Unexpected Error dialog when request is aborted while loading</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1568592" target="_blank">1568592</a>] Custom fields are lost when using Edit Search</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1568704" target="_blank">1568704</a>] Allow to use --- as empty Resolution field value in Custom Search</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1569130" …
=> Bump version to 20190808.1

Bugzilla/Search.pm
Fix the API error by parsing the `%last_changed%` pronoun before merge date pronouns. The current control flow (not my code) is somewhat meaningless anyway.
[Bug 1572731 - Updated Since Last Visit section of My Dashboard broken](https://bugzilla.mozilla.org/show_bug.cgi?id=1572731)
=> Bug 1572731 - Updated Since Last Visit section of My Dashboard broken

extensions/GuidedBugEntry/web/js/guided.js
Don’t set the hidden `rep_platform` and `op_sys` fields when the default values are empty = auto-detect. Just use All/All as hardcoded in the guided bug form template.
[Bug 1572945 - Cannot enter bug through Guided Bug Form if the product’s default platform is auto-detect](https://bugzilla.mozilla.org/show_bug.cgi?id=1572945)
=> Bug 1572945 - Cannot enter bug through Guided Bug Form if the product’s default platform is auto-detect

extensions/BMO/template/en/default/bug/create/create-shield-studies.html.tmpl
I’ve checked custom forms if they have bug type specified. Other than #1410, only this Shield Studies form doesn’t have it.
=> no bug - Add bug_type field to custom Shield Studies form

Bugzilla/CGI.pm, extensions/GitHubAuth/lib/Client.pm, extensions/GitHubAuth/template/en/default/hook/account/auth/login-additional_methods.html.tmpl, extensions/GitHubAuth/template/en/default/hook/account/auth/login-small-additional_methods.html.tmpl
- Remove request_uri from Bugzilla/CGI.pm as GitHub login was only thing using.
- Change GitHub target_uri to always redirect back to index.cgi
- Remove login_uri method from GitHub extension as no code was using it.
- Internal error occurring due to no [% urlbase %] in the login templates. github.cgi looks for the urlbase before sending off to GitHub for auth.
=> Bug 1574792 - Bugzilla has suffered an internal error:  Bugzilla cannot log you into an external site via GitHub.

auth.cgi, extensions/PhabBugz/Extension.pm, template/en/default/account/auth/delegation.html.tmpl
- Display a confirmation of the new key being created on the auth delegation verification page. Do this instead of sending an email for those types of new keys.
=> Bug 1575005 - Do not send email announcement upon automated creation of API keys by auth.cgi

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1573127" target="_blank">1573127</a>] Blocklist bug form is missing a bug type field</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1572945" target="_blank">1572945</a>] Cannot enter bug through Guided Bug Form if the product’s default platform is auto-detect</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1574792" target="_blank">1574792</a>] Bugzilla has suffered an internal error:  Bugzilla cannot log you into an external site via GitHub.</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1575005" target="_blank">1575005</a>] Do not send email announcement upon automated creation pf API keys by auth.cgi</li>
</ul>
=> Bumped version to 20190819.1

extensions/BMO/template/en/default/hook/bug_modal/edit-custom_field-cf_crash_signature.html.tmpl, extensions/BMO/web/js/edituser_menu.js, extensions/BMO/web/js/firefox-crash-table.js, extensions/BMO/web/styles/bug_modal.css, extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl, extensions/BugModal/template/en/default/bug_modal/attachments.html.tmpl, extensions/BugModal/template/en/default/bug_modal/cc_list.html.tmpl, extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl, extensions/BugModal/template/en/default/bug_modal/field.html.tmpl, extensions/BugModal/template/en/default/bug_modal/navigate.html.tmpl, extensions/BugModal/web/bug_modal.css, extensions/BugModal/web/bug_modal.js, qa/t/test_target_milestones.t, qa/t/test_votes.t, skins/standard/global.css
* Reorganize bug modal modules based on my [information architecture plan](https://bugzilla.mozilla.org/show_bug.cgi?id=1344091#c3) so similar fields are properly grouped.
* Hide more fields if it’s empty or unspecified so the view mode will be cleaner: Version, Target, Points, Whiteboard, Triage Owner
* Toolbar: Include both search navigation and page action buttons
* Header: Remove redundant info and instead add simple status (Open/Closed), reported date and updated/resolved date; add menus that are currently on the page footer
* User names on modules: now displayed as Gravatar + nick
* Attachments module: now always displayed with the Attach New File button-like link
* Misc fixes: simplified URL labels, better module header subtitles, etc.
[Bug 1344091 - Move all the related bug fields …
=> Bug 1344091 - Reorganize the header and modules on modal bug UI

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1344091" target="_blank">1344091</a>] Reorganize the header and modules on modal bug UI</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1574792" target="_blank">1574792</a>] Bugzilla has suffered an internal error:  Bugzilla cannot log you into an external site via GitHub.</li>
</ul>
=> Bumped version to 20190821.1

extensions/BMO/template/en/default/bug/create/create-client-bounty.html.tmpl
leaves bug submission form open when bounty program info is clicked
=> Open Client Bounty Program link in new tab

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
Fix a wrong value check to hide the field. I should have noticed this earlier.
[Bug 1575885 - Triage Owner field cannot be found in reorganized bug UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1575885)
=> Bug 1575885 - Triage Owner field cannot be found in reorganized bug UI

extensions/BugModal/web/bug_modal.css
Use the pointer (hand) cursor for the CC field expander, so it looks clickable.
[Bug 1576236 - Arrow beside "CC" does not have any affordance to indicate it's clickable](https://bugzilla.mozilla.org/show_bug.cgi?id=1576236)
=> Bug 1576236 - Arrow beside "CC" does not have any affordance to indicate it's clickable

extensions/BugModal/web/bug_modal.js
Re-enable the Save buttons when the user goes back to the modal bug page due to any field error or mid-air collision.
[Bug 1576149 - 'Save changes' button disabled after submitting changes which get rejected and using Back button (e.g. bug summary too long)](https://bugzilla.mozilla.org/show_bug.cgi?id=1576149)
=> Bug 1576149 - 'Save changes' button disabled after submitting changes which get rejected and using Back button (e.g. bug summary too long)

extensions/BugModal/web/bug_modal.js
Workaround the issue by remembering if a module is expanded or collapsed only when the module is visible.
[Bug 1575805 - Manually expanded section will be collapsed again after visiting a bug that hides the section by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1575805)
=> Bug 1575805 - Manually expanded section will be collapsed again after visiting a bug that hides the section by default

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1575885" target="_blank">1575885</a>] Triage Owner field cannot be found in reorganized bug UI</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1576236" target="_blank">1576236</a>] Arrow beside "CC" does not have any affordance to indicate it's clickable</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1576149" target="_blank">1576149</a>] 'Save changes' button disabled after submitting changes which get rejected and using Back button (e.g. bug summary too long)</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1575805" target="_blank">1575805</a>] Manually expanded section will be collapsed again after visiting a bug that hides the section by default</li>
<li>[<a …
=> Bumped version to 20190829.1

Bugzilla/User/APIKey.pm
- This fixes the not null error for creation_ts
=> Bug 1576667 - Add creation timestamp to the user_api_keys table to show when an api key was first generated (Schema Fix)

extensions/TrackingFlags/Extension.pm, extensions/TrackingFlags/template/en/default/hook/admin/admin-end_links_right.html.tmpl
The *edittrackingflags* group has been created on BMO already.
=> Bug 1578481 - Update tracking flags admin UI to use special edittrackingflags group instead of admin and add relman to the new group

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1576667" target="_blank">1576667</a>] Add creation timestamp to the user_api_keys table to show when an api key was first generated</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1578481" target="_blank">1578481</a>] Update tracking flags admin UI to use special edittrackingflags group instead of admin and add relman to the new group</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1579236" target="_blank">1579236</a>] Push connector for Phabricator should add security and bmo groups to revision if revision is private</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1578805" target="_blank">1578805</a>] When changing password or enabling 2fa, previous sessions should be revoked …
=> Bumped version to 20190906.1

template/en/default/account/prefs/account.html.tmpl, userprefs.cgi
Testing:
* Create test account
* Go to Preferences -> Account
* Click Disable My Account
* Click checkbox to acknowledge disabling the account.
* Click Disable Account
* Observe error stating that old password was incorrect.
* Go back and enter current password.
* Click Disable Account
* Account should be disabled and test account cannot login.
=> Bug 1549262 - Lack of password confirmation when deleting your account.

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1580371" target="_blank">1580371</a>] Audit changes to user api key changes to the audit log table (skip last_used information)</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1580909" target="_blank">1580909</a>] Javascript error on New Bug form causing the default setting for showing advanced fields to be ignored</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1549262" target="_blank">1549262</a>] Lack of password confirmation when deleting your account.</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1583824" target="_blank">1583824</a>] "Update Status Flags" button stopped working</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1578965" …
=> Bumped version to 20190926.1

template/en/default/account/password/set-forgotten-password.html.tmpl, template/en/default/account/prefs/account.html.tmpl, template/en/default/account/reset-password.html.tmpl
See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#Values
autocomplete="current-password"
autocomplete="new-password"
can be used to provide the correct semantics.
The latter also allows integration with the password generation feature in Chrome and Firefox.
=> Bug 1586698 - Add proper autocomplete attributes for password change fields

extensions/BMO/web/js/firefox-crash-table.js
Load the crash table iframe after it becomes visible, so the height is always set properly.
[Bug 1587133 - Crash panel sizing incorrect when first opened](https://bugzilla.mozilla.org/show_bug.cgi?id=1587133)
=> Bug 1587133 - Crash panel sizing incorrect when first opened

js/attachment.js
Automatically tick the patch checkbox on the New Attachment page only when the description starts with “patch” so “screenshot of patch” won’t be treated as a patch. Also, toggle the checkbox properly whenever the description is updated by the user.
[Bug 1580980 - Including "patch" in attachment description automatically flags the attachment as a patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1580980)
=> Bug 1580980 - Including "patch" in attachment description automatically flags the attachment as a patch

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
Show the modal UI’s “Dependency tree / graph“ links even in Edit mode, especially for those who are using the “Always Enable Edit Mode” option.
[Bug 1580998 - Show link to dependency tree in edit mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1580998)
=> Bug 1580998 - Show link to dependency tree in edit mode

Bugzilla/Bug.pm
A See Also change can be stored in multiple rows in the `bugs_activity` table and needs to be joined wisely. If the second row is empty, just return the first row, so no extra comma will be included.
[Bug 1587982 - Extraneous comma in history due to wrong join of added field in Bug 1368555](https://bugzilla.mozilla.org/show_bug.cgi?id=1587982)
=> Bug 1587982 - Extraneous comma in history due to wrong join of added field in Bug 1368555

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1573227" target="_blank">1573227</a>] Various UI text and code comments assume male gender</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1586698" target="_blank">1586698</a>] Add proper autocomplete attributes for password change fields</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1587133" target="_blank">1587133</a>] Crash panel sizing incorrect when first opened</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1461358" target="_blank">1461358</a>] Add a dev server link to the account creation process.</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1584191" target="_blank">1584191</a>] Cloning a bug doesn't copy the regressed by / regressions field</li> …
=> Bump version to 20191016.1

extensions/BMO/template/en/default/hook/flag/type_comment-form.html.tmpl, extensions/FlagTypeComment/web/js/ftc.js, skins/standard/attachment.css, skins/standard/global.css, template/en/default/attachment/edit.html.tmpl
Fix a couple of issues on the [uplift request form](https://release.mozilla.org/tooling/bugzilla/2018/10/03/uplift-form):
* Disable the Submit button and show a status message while sending background requests
* Show an error message if something went wrong
* Make the background request process a bit faster by reducing the number of `await`
* Remove the uplift form from the Create New Attachment page, because the form requires only on the Edit Attachment page
[Bug 1567696 - Forms for approval requests should indicate XHR / progress](https://bugzilla.mozilla.org/show_bug.cgi?id=1567696)
=> Bug 1567696 - Forms for approval requests should indicate XHR / progress

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1185841" target="_blank">1185841</a>] remove references to XMLRPC and JSONRPC from the docs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=655408" target="_blank">655408</a>] add "non-visual but accessible to screen-readers" test to security bugs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1425604" target="_blank">1425604</a>] Name of "Priority" field is inconsistent between "Enter Bug" view and "Edit Bug" view</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1589444" target="_blank">1589444</a>] Add an option for recently fixed bugs in a particular component</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1590434" target="_blank">1590434</a>] Update Firefox …
=> Bumped version to 20191106.1

extensions/BugModal/web/bug_modal.css
A one-liner fix. Just change the cursor on the blue “X new comments since last visit” banner.
[Bug 1585048 - "X new comments since last visit" text doesn't have click affordance](https://bugzilla.mozilla.org/show_bug.cgi?id=1585048)
=> Bug 1585048 - "X new comments since last visit" text doesn't have click affordance

skins/standard/global.css, template/en/default/reports/report.html.tmpl
Make the YUI table headers readable in dark mode by overriding the default theme colour.
[Bug 1584583 - Reports are unreadable in dark mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1584583)
=> Bug 1584583 - Reports are unreadable in dark mode

Bugzilla/Attachment.pm
Use a user-defined MIME type for attached text instead of assuming `text/plain`.
[Bug 1597235 - Setting the mime type of a pasted attachment doesn't work.](https://bugzilla.mozilla.org/show_bug.cgi?id=1597235)
=> Bug 1597235 - Setting the mime type of a pasted attachment doesn't work.

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1585048" target="_blank">1585048</a>] "X new comments since last visit" text doesn't have click affordance</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1594844" target="_blank">1594844</a>] Automatically set the bug's assignee when they upload a revision to an unassigned bug</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1596628" target="_blank">1596628</a>] The param --since-db is not working for the report_ping script that sends data to STMO</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1584583" target="_blank">1584583</a>] Reports are unreadable in dark mode</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1597235" target="_blank">1597235</a>] Setting the …
=> Bumped version to 20191121.1

vagrant_support/apache.yml, vagrant_support/checksetup_answers.j2, vagrant_support/devtools.yml, vagrant_support/jobqueue.yml, vagrant_support/playbook.yml
* canonical_urlbase was missing from checksetup_answers and was causing checksetup.pl to bail before creating the database.
* other cleanups and changes needed
=> Bug 1597524 - vagrant up failed, saying table 'bugs_bmo.profiles' doesn't exist

skins/standard/dependency-tree.css
Fix wrong indentations on the dependency tree which confuses people.
[Bug 1583153 - Dependency tree view has wrong/confusing indentation](https://bugzilla.mozilla.org/show_bug.cgi?id=1583153)
=> Bug 1583153 - Dependency tree view has wrong/confusing indentation

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1599002" target="_blank">1599002</a>] Change bug status from NEW to ASSIGNED when setting assignee from Phabricator</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1597524" target="_blank">1597524</a>] vagrant up failed, saying table 'bugs_bmo.profiles' doesn't exist</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1599620" target="_blank">1599620</a>] Don't auto-assign if there are no reviewers specified.</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1599539" target="_blank">1599539</a>] Bugzilla should strip whitespace from the beginning of the "URL" field (because a leading space triggers "This is considered an unsafe URL and could possibly be harmful" dialog)</li>
<li>[<a …
=> Bump version to 20191212.1

extensions/ProdCompSearch/web/js/prod_comp_search.js
Replace any empty product/component query parameters, so the most-used component links will take you to the advanced bug form as expected.
[Bug 1607030 - Selecting a most-used component goes into a loop when switching from guided bug entry form](https://bugzilla.mozilla.org/show_bug.cgi?id=1607030)
=> Bug 1607030 - Selecting a most-used component goes into a loop when switching from guided bug entry form

template/en/default/attachment/createformcontents.html.tmpl
This is useful for about:support JSON files or Firefox Remote Settings data snippets.
Untested patch.
=> Add JSON to the attachment content types dropdown

Bugzilla/Util.pm, js/util.js
Fix date labels that I changed in #1297 by saying “1 year ago” Instead of “last year.” Also simply the logic. Since the code already uses the math `round` function, 17 months ago will be 1 year ago but 18 months will be 2 years ago, which won’t be changed.
[Bug 1608960 - 2018 is not last year](https://bugzilla.mozilla.org/show_bug.cgi?id=1608960)
=> Bug 1608960 - 2018 is not last year

Bugzilla/DB/Schema.pm, Bugzilla/DB/Schema/Mysql.pm, Bugzilla/DB/Schema/Oracle.pm, Bugzilla/DB/Schema/Pg.pm, Bugzilla/DB/Schema/Sqlite.pm, Bugzilla/Install/DB.pm, extensions/Review/Extension.pm
Will need to hold on this a little longer as it may require BMO outage to do the table upgrades. There is also a chance we can do this online using Percona toolkit or Ghost.
=> Revert "Bug 1588221 - Update current s3 storage controller to only upload attachments over a certain size (schema only)"

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1569274" target="_blank">1569274</a>] Updated Dockerfile and circleci configuration to build dependencies into a new bmo-slim image based on Perl 5.30</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1604738" target="_blank">1604738</a>] crash graph doesn't handle signatures with "+" character</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1592410" target="_blank">1592410</a>] different bug count with and without count_only=1 parameter</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1607030" target="_blank">1607030</a>] Selecting a most-used component goes into a loop when switching from guided bug entry form</li>
<li>[<a …
=> Bumped version to 20200117.1

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1611257" target="_blank">1611257</a>] Bugmail is being filtered incorrectly since this morning's BMO deployment</li>
</ul>
=> Bump version to 20200123.1

Bugzilla/Test/Selenium.pm, extensions/BugModal/template/en/default/bug/show-modal.html.tmpl, extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl, extensions/BugModal/web/bug_modal.css, extensions/BugModal/web/bug_modal.js, qa/t/test_bmo_autolinkification.t, qa/t/test_flags.t, qa/t/test_time_summary.t, template/en/default/bug/process/attachment-results.html.tmpl, template/en/default/bug/process/bugmail.html.tmpl, template/en/default/bug/process/results.html.tmpl
Hide the change summary displayed after creating/updating a bug/attachment, and instead show a shorter summary as a toast notification just like what you’ll see when clicking the Copy Summary or Follow button. This makes the UI less cluttered, and allows to fix the bug header at the top of the page.
Note: this change actually _hides_ the “email sent to” message, so people really want it can show it using a user stylesheet. Once the bug form submission is replaced with a background API request, it will be completely removed.
[Bug 1556727 - Replace “Email sent to” message with a toast notification](https://bugzilla.mozilla.org/show_bug.cgi?id=1556727)
=> Bug 1556727 - Replace “Email sent to” message with a toast notification

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1613686" target="_blank">1613686</a>] Improper encoding of content-type, content-transfer-encoding for security reports causes content to not be displayed properly</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1556727" target="_blank">1556727</a>] Replace “Email sent to” message with a toast notification</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1611281" target="_blank">1611281</a>] Double-escaping of '&lt;' in code areas</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1611494" target="_blank">1611494</a>] Bugzilla custom email headers are getting mashed together</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1612287" target="_blank">1612287</a>] Issue …
=> Bump version to 20200211.1

extensions/MyDashboard/template/en/default/pages/mydashboard.html.tmpl
The "phabricator review requests" link had an extra slash in the url. This patch removes it.
=> Bug 1617358 - Remove extra slash in mydashboard.html.tmpl

Bugzilla/Bug.pm, qa/t/lib/QA/RPC.pm, qa/t/test_security.t, qa/t/webservice_bug_get.t, qa/t/webservice_bug_get_bugs.t
Use the `Bugzilla->user->visible_bugs` filter to hide security/confidential bugs from people without access. The change applies to the modal bug UI’s References section, inline history and separate history page as well as the API.
[Bug 1591549 - Hide bugs in dependencies and regression fields from users without access](https://bugzilla.mozilla.org/show_bug.cgi?id=1591549)
=> Bug 1591549 - Hide bugs in dependencies and regression fields from users without access

Bugzilla/Template.pm
modified:   Bugzilla/Template.pm to account for 1 byte file size
=> Bug 1237874 - File size unit always plural: "1 bytes"

template/en/default/bug/create/create.html.tmpl
Prevent the description (comment) field on the New Bug page from being cleared during browser session restore or back-forward page navigation.
[Bug 1599865 - Bug description is erased during page load, leading to dataloss during Firefox session restore](https://bugzilla.mozilla.org/show_bug.cgi?id=1599865)
=> Bug 1599865 - Bug description is erased during page load, leading to dataloss during Firefox session restore

extensions/BugModal/web/bug_modal.js, template/en/default/bug/process/results.html.tmpl
Clear any saved comment on the bug page once the bug is successfully updated, not immediately after the Save Changes button is clicked. This prevents the user’s comment from being cleared when a mid-air collision happens.
Note: the test failure should be solved once #1503 is merged.
[Bug 1472757 - Comment field empty after clicking "go back page"](https://bugzilla.mozilla.org/show_bug.cgi?id=1472757)
=> Bug 1472757 - Comment field empty after clicking "go back page"

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1617358" target="_blank">1617358</a>] Extra slash in the "phabricator review requests" link's url on the BMO dashboard</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1591549" target="_blank">1591549</a>] Hide bugs in dependencies and regression fields from users without access</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1612290" target="_blank">1612290</a>] Provide self-service UI for users to reactivate their account after being disabled due to bouncing</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1237874" target="_blank">1237874</a>] File size unit always plural: "1 bytes"</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1599865" …
=> Bump version to 20200225.1

Bugzilla/Util.pm, js/util.js
Revert the logic changes from #1492 which lead to show "13 hours ago" as "1 day ago" and "16 days ago" as "1 month ago". The previous logic was more conservative even if it looks slightly more complex. Preserved the label changes.
[Bug 1614634 - 13 hours ago wasn't "1 day ago"](https://bugzilla.mozilla.org/show_bug.cgi?id=1614634)
=> Bug 1614634 - 13 hours ago was not "1 day ago"

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1617358" target="_blank">1617358</a>] Extra slash in the "phabricator review requests" link's url on the BMO dashboard</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1591549" target="_blank">1591549</a>] Hide bugs in dependencies and regression fields from users without access</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1237874" target="_blank">1237874</a>] File size unit always plural: "1 bytes"</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1599865" target="_blank">1599865</a>] Bug description is erased during page load, leading to dataloss during Firefox session restore</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1472757" target="_blank">1472757</a>] …
=> Bump version to 20200226.1

extensions/REMO/template/en/default/bug/create/comment-mozreps.txt.tmpl, extensions/REMO/template/en/default/bug/create/create-mozreps.html.tmpl, extensions/REMO/template/en/default/bug/create/created-mozreps.html.tmpl, extensions/REMO/web/js/moz_reps.js, extensions/REMO/web/styles/moz_reps.css
In the past years we changed the Reps program application criteria several times. Nowadays our application form does not match what we need to know in an application anymore. This leads to an inefficient process where we need to ask back and request information. Due to this [Tim](https://reps.mozilla.org/u/Mad_Maks/) has created a new form, tested it and streamlined our application process. This PR adjusts the form to that variant.
I've tested this locally and Tim has also verified that it behaves as required.
=> Bug 1619361 - Update Reps Application Form

extensions/BugModal/web/bug_modal.js, template/en/default/bug/process/results.html.tmpl
Pass a bug ID to `clearSavedBugComment()` to make sure the comment cache of the updated bug, not the current bug, will be cleared.
https://bugzilla.mozilla.org/show_bug.cgi?id=1620236
=> Bug 1620236 - Comments on submitted bugs are re-populated if user chooses to show next bug in my list after changing a bug

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl, extensions/BugModal/web/bug_modal.css, extensions/BugModal/web/comments.js
Add the Save button to the comment tagging UI so people don’t forget to save a new tag by hitting the Enter key. The Enter-to-save keyboard shortcut is still supported. Plus, clean up the code a bit.
https://bugzilla.mozilla.org/show_bug.cgi?id=1605761
=> Bug 1605761 - It's not clear at all that you need to hit -enter- to save a comment tag.

.vscode/tasks.json, README.rst
Add `docker-compose` commands to the VS Code tasks file. Make the Docker `rsync` command the default build task instead of Vagrant, so it can be used quickly with the Cmd+Shift+B keyboard shortcut.
=> no bug - Update VS Code tasks with Docker commands

skins/standard/buglist.css
Make sure stagger headers on the search results table are displayed properly. `position: sticky` has to be set on `<thead>` instead of `<tr class="bz_buglist_header">` that will double when staggered.
Note 1: stagger headers can be used when you customize the columns via the “Change Columns” link at the bottom of the search results page.
Note 2: this technique works only on Firefox and Safari. It seems Chrome still doesn’t support `position: sticky` within a `<table>`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1621160
=> Bug 1621160 - First row of stagger column headers will be hidden when table header becomes sticky

template/en/default/list/table.html.tmpl
Linkify all bug IDs on the search results page, including the fixed Bug ID column. Somehow the Duplicates field’s column type is `FIELD_TYPE_BUG_ID` so I’ll keep it to avoid any potential breakage and make the linkification work for both single bug ID and multiple bug IDs.
https://bugzilla.mozilla.org/show_bug.cgi?id=1621278
=> Bug 1621278 - Make bug IDs on search results proper bug links

template/en/default/reports/keywords.html.tmpl
Link added to describe keywords page
=> Bug 1344094 - Add a link to a wiki.mozilla.org page describing how to request a keyword

extensions/MyDashboard/lib/Queries.pm, extensions/MyDashboard/web/js/query.js
As an Outreachy applicant, I made the enhancement Bug1370492 - "Assigned to you" in My dashboard should show bugs priority. I placed the priority column next to the update column.
@dklawren @emceeaich
=> Bug 1370492 - Assigned to you shows bugs priority in My dashboard

extensions/BMO/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl, extensions/BMO/template/en/default/hook/bug/create/create-end.html.tmpl, extensions/Needinfo/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl, extensions/Review/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl, extensions/UserStory/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl, js/attachment.js, skins/standard/attachment.css, template/en/default/attachment/createformcontents.html.tmpl, template/en/default/bug/comment.html.tmpl, template/en/default/bug/create/create.html.tmpl, template/en/default/bug/field-label.html.tmpl, template/en/default/bug/field.html.tmpl, template/en/default/flag/list.html.tmpl, template/en/default/global/header.html.tmpl, template/en/default/global/textarea.html.tmpl, template/en/default/global/userselect.html.tmpl
Improve accessibility of the Enter Bug page by making sure form input fields have an accessible label (plus a description where possible) and modifying the markup. Tested with VoiceOver.
https://bugzilla.mozilla.org/show_bug.cgi?id=1626543
=> Bug 1626543 - Some fields on enter bug page do not have associated labels

extensions/BugModal/web/bug_modal.js
Escape HTML tags properly so copy will work with any summary.
https://bugzilla.mozilla.org/show_bug.cgi?id=1627601
=> Bug 1627601 - Copy Summary function doesn’t work properly if the bug summary contains HTML tags

template/en/default/account/prefs/account.html.tmpl
The order of the fields to change password and email change in order to give a better UX because the current password change preferences panel looks like a new email address is also required. @dklawren @emceeaich
=> Bug 1202669 - UX correction for change password and email

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1622311" target="_blank">1622311</a>] For security bugs, link the security issue banner to https://wiki.mozilla.org/Security/Bug_Approval_Process</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1626543" target="_blank">1626543</a>] Some fields on enter bug page do not have associated labels</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1627601" target="_blank">1627601</a>] Copy Summary function doesn’t work properly if the bug summary contains HTML tags</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1628467" target="_blank">1628467</a>] Add a method to opt-out of auto-refreshing on my dashboard</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1202669" …
=> Bumped version to 20200416.1

extensions/MyDashboard/web/js/flags.js, extensions/MyDashboard/web/js/query.js
Added a cookie to store the current setting of the auto-refresh button in My dashboard so that it is either on all of the time or off even if the page is reloaded. @dklawren
=> Bug 1631051-Store current configuration of auto refresh button in My  Dashboard

README.rst
This should assist users/contributors who are looking for assistance, but aren't aware of the Matrix channel yet.
=> Bug 1631971 - Adds link to Matrix in README

extensions/BugModal/template/en/default/bug/show-modal.html.tmpl
Not to scare new contributors.
https://bugzilla.mozilla.org/show_bug.cgi?id=1632038
=> Bug 1632038 -  Remove number of people from bug update toast notification

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1631051" target="_blank">1631051</a>] The current setting of the auto-refresh button in My dashboard should be stored</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1631971" target="_blank">1631971</a>] Create link to Matrix support channel for each product</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1632038" target="_blank">1632038</a>] Remove number of people from bug update toast notification</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1632624" target="_blank">1632624</a>] When adding vars to the fields data that is logged to stack driver, convert to a JSON string</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1632994" target="_blank">1632994</a>] …
=> Bumped version to 20200429.1

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1635148" target="_blank">1635148</a>] Recent changes to add support for attachments in S3 caused a memory leak in the phabbugz feed daemon</li>
</ul>
=> Bumped version to 20200504.1

js/advanced-search.js
Increase the field index properly given deeply nested groups.
https://bugzilla.mozilla.org/show_bug.cgi?id=1594066
=> Bug 1594066 - reproducible "Can't use ARRAY(0x17340610) as a field name." when Custom Search used

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1633846" target="_blank">1633846</a>] Enable retries for uploading attachments to S3 when an error occurs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1636549" target="_blank">1636549</a>] Guided Bug Helper extension filing bugs with 'normal' instead of '--' severity.</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1634342" target="_blank">1634342</a>] change links for security approval documents to source docs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1594066" target="_blank">1594066</a>] reproducible "Can't use ARRAY(0x17340610) as a field name." when Custom Search used</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1635332" …
=> Bumped version to 20200511.1

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1638022" target="_blank">1638022</a>] Phabbugz should not try to set needs-review when the revision is closed or abandoned</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1639311" target="_blank">1639311</a>] Attaching a file with emojis breaks them</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1639903" target="_blank">1639903</a>] Fix `Use of uninitialized value in pattern match (m//) at /app/Bugzilla/App.pm line 71`</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1639902" target="_blank">1639902</a>] Fix `Use of uninitialized value in string eq at /app/Bugzilla/Bug.pm line 4674`</li>
</ul>
=> Bumped version to 20200526.1

Bugzilla/BugUrl.pm, Bugzilla/BugUrl/MozSentry.pm, template/en/default/global/user-error.html.tmpl
Test with different format Sentry URLs. Examples:
https://sentry.prod.mozaws.net/operations/fenix/issues/8252183/ (PASS)
https://sentry.prod.mozaws.net/operations/issues/8252183/ (FAIL)
https://sentry.prod.mozaws.net/operations/fenix/issues/825abc/ (FAIL)
etc.
=> Bug 1641117 - Add Sentry to the list of See Also URLs.

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1641249" target="_blank">1641249</a>] Enable the crash signature field for the Focus and Fenix Stability components</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1641897" target="_blank">1641897</a>] Cleanup old severity values in custom forms and other places</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1641117" target="_blank">1641117</a>] Add Sentry to the list of See Also URLs.</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1642654" target="_blank">1642654</a>] Add ability for users to reactivate their own account when disabled from inactivity</li>
</ul>
=> Bumped version to 20200603.1

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1643821" target="_blank">1643821</a>] Add code to generate_conduit_data.pl to create an oauth2 client for Phabricator when used for development</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1645455" target="_blank">1645455</a>] Can't attach some text, 500 internal server error</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1646559" target="_blank">1646559</a>] Phabricator to BMO OAuth2 authentication fails to work properly due to CSP protections</li>
</ul>
=> Bumped version to 20200624.1

Bugzilla/App/Plugin/OAuth2.pm
The callback jwt_claims is called in list context.
Without an explicit return, when the if (!...) does not match it will
return a single false item. This causes the "Odd number of elements..."
perl warning.
Adding a `return` will prevent the warning and is also probably the
intent of the code.
=> no bug - remove warning "Odd number of elements"

Bugzilla/CGI.pm
Font preloading has been broken for more than a year, and doesn't appear
to work correctly even when provided URLs which exist; removed.
google-analytics likely does little to improve page load time
performance against all the other assets, is loaded async, and exists
outside of the GoogleAnalytics making it easy to miss when updating that
extension (eg. the preloading doesn't honour DNT); also removed.
=> Bug 1651591 - remove preloading of fonts and ga; r=dkl

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl, extensions/EditComments/Extension.pm, extensions/EditComments/lib/WebService.pm, extensions/EditComments/template/en/default/hook/admin/params/editparams-current_panel.html.tmpl, extensions/EditComments/template/en/default/hook/bug_modal/activity_stream-comment_action.html.tmpl, extensions/EditComments/template/en/default/hook/bug_modal/header-end.html.tmpl, extensions/EditComments/template/en/default/hook/global/header-start.html.tmpl, extensions/EditComments/template/en/default/pages/comment-revisions.html.tmpl, js/util.js
Allow any member of the `edit_comments_group` and insiders to edit the
description (comment 0) of any bug.
- adds new `allow_global_initial_comment_editing` parameter
- consolidates permissions check into a single location
- fixes Bugzilla.API error handling to return the error message instead
of always "Unexpected Error" (all errors are unexpected; this message
is meaningless).
- adds new `edit_comments_admins_group` parameter
- reference `edit_comments_admins_group` group membership instead of
`insider` for global edit comments and revision hiding features
- fix issues caused by a comment body that returns a falsy value (eg. "0")
=> Bug 1535000 - Allow anyone with edit-comments to edit any bug's comment 0; r=dkl

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1645768" target="_blank">1645768</a>] Please add 'See Also' support for GitLab</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1651591" target="_blank">1651591</a>] BMO attempts to preload FiraSans, which was replaced with FiraGO in May 2019</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1535000" target="_blank">1535000</a>] Make Description (Comment 0) editable by everyone with edit_comments rights</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1652863" target="_blank">1652863</a>] setting the needinfo flag when filing a new bug in Core or Toolkit does not cause the textbox for user information to pop up</li>
</ul>
=> Bumped version 20200722.1

extensions/Splinter/template/en/default/pages/splinter.html.tmpl
Same fix was need as in pr #1595
=> Bug 1647642 - when commenting on patch or reviewing one, bugzilla clears other (review, ui-review) flags

js/attachment.js, template/en/default/attachment/edit.html.tmpl
This adds simple code to attachment.js to set the markdown_off value to either 1 or 0 based on whether we are adding a normal comment or editing the patch itself as a comment. Editing a patch as a comment will disable markdown which is proper behavior IMO.
=> Bug 1643526 - Attachment comments don't render markdown, but their preview does

extensions/Needinfo/template/en/default/hook/request/email-after_summary.txt.tmpl
This commit adds a conditional section to the template that catches the case where the requestee of a needinfo is the bug's reporter, and describes why their assistance has been requested. 
For other cases, the text is modified to indicate that assistance is needed to help move the bug forward. 
The changes do not attempt to discern if the requestee is staff, other contributors, or 'drive-by' bug reporters.
=> Bug 1654456 - needinfo? request email enhancements

extensions/GuidedBugEntry/template/en/default/guided/guided.html.tmpl, extensions/GuidedBugEntry/template/en/default/guided/products.html.tmpl
This pull request modifies the Guided Bug Entry extension:
The product selector has been changed such that when a user clicks Firefox for Android or iOS they are redirected to the corresponding GitHub projects' issue pages.
=> Bug 1655808: send users in guided bug flow to GitHub for Android and iOS bug reports

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1643526" target="_blank">1643526</a>] Attachment comments don't render markdown, but their preview does</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1654456" target="_blank">1654456</a>] [needinfo] Provide instructions and guidance when needinfo is requested of the bug's reporter</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1654370" target="_blank">1654370</a>] Remove remaining code that references Firefox OS from BMO code base</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1655808" target="_blank">1655808</a>] Send guided bug flow users to GitHub for Fenix issues</li>
</ul>
=> Bumped version to 20200805.1

extensions/Review/Extension.pm, extensions/Review/lib/Util.pm
I lumped the data-review flag count in with the normal review count so I would not need to create a new database column in the profiles table. They are essentially similar and the count is the correct in the header of each BMO page.
=> Bug 1649841 - Include data-review? requests in notification count

extensions/GuidedBugEntry/template/en/default/guided/products.html.tmpl
This PR updates the template in guided bug entry for Fenix and iOS. So that security issues are filed in Bugzilla, this adds links to the guided bug entry workflow for the respective mobile components.
=> Bug 1657778 - Offer link to Bugzilla for filing security issues in Fenix and iOS

Bugzilla/Attachment.pm, extensions/BMO/Extension.pm, extensions/BMO/template/en/default/hook/bug_modal/attachments-row.html.tmpl, extensions/BugModal/template/en/default/bug_modal/attachments.html.tmpl, extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl, template/en/default/attachment/list.html.tmpl
This will allow most bug bounty recipients to view the amount of their bounty. It will not show it to reporters if we filed the bug for them, however those are less likely to be repeat filers.
=> Show Bounty Attachments to the Bug Reporter

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1657542" target="_blank">1657542</a>] During recent bmo deployment, emails were delivered to a file instead of SES which caused interruption of email service</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1658622" target="_blank">1658622</a>] "product responsibilities" on editusers should include Triage Owner</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1588661" target="_blank">1588661</a>] Design for WebHooks</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1659177" target="_blank">1659177</a>] Replace mozillians.org with people.mozilla.org in Reps Mentorship From</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1649841" target="_blank">1649841</a>] Include …
=> Bumped version to 20200828.1

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1657542" target="_blank">1657542</a>] During recent bmo deployment, emails were delivered to a file instead of SES which caused interruption of email service</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1658622" target="_blank">1658622</a>] "product responsibilities" on editusers should include Triage Owner</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1588661" target="_blank">1588661</a>] Design for WebHooks</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1659177" target="_blank">1659177</a>] Replace mozillians.org with people.mozilla.org in Reps Mentorship From</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1649841" target="_blank">1649841</a>] Include …
=> Bumper version to 20200908.1

extensions/Push/lib/Connector/Webhook.pm, extensions/Push/lib/Serialize.pm, extensions/Webhooks/Extension.pm, extensions/Webhooks/template/en/default/account/prefs/webhooks.html.tmpl
@dklawren I'm trying to use the `HTML::Strip` module but it throws me an error to remove html, I think I need to install the module on the project but I'm not sure.
Here I took the message when a comment is created and modify it in order it seems as current change event message from webhooks, and also are sent as part of change event, as you suggest.
And the description is sent as a parameter that changes but not as part of the bug body, because it is sent as a comment too, and for that reason is sent in another message when a bug is created not in the same:
```
"event": {
"action": "change",
"time": "2020-07-24T20:11:22",
"user": {
"id": 1,
"login": "admin@bmo.test",
"real_name": "Vagrant User"
},
"changes": [
{
"field": "description",
"removed": "",
"added": "This is a my description"
} …
```
=> Bug 1658841 - Webhooks should include comments added to a bug

Bugzilla/User.pm, buglist.cgi
Removed all use of BUGLIST cookie for non-authenticated users. Logged in users still use the DB for storing last buglist.cgi queries.
=> Bug 1668308 - Unauthenticated searches can generate massive cookies

Bugzilla/Bug.pm, t/model.t, t/report-ping-simple.t, template/en/default/global/user-error.html.tmpl
We are currently blocking from creating/updating a bug via API/UI but not if the bug_type is '--' which in the DB is a legal value. What we mean when we set the 'require_bug_type' data/params setting, we do not want '--' to be allowed. Now enforcing this properly.
=> Bug 1669330 - Should not be possible to override bug type requirement when submitting a bug using API

Bugzilla/User.pm, token.cgi
Use Bugzilla::User->update instead of direct DB which will store login_name change in audit_log and also clear memcache for the userid.
=> Bug 1669755 - Email address changes are not being stored on profiles activity for some reason

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1670319" target="_blank">1670319</a>] Allow use of OAuth2 bearer token as authentication for API calls same as API keys</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1674166" target="_blank">1674166</a>] Note that created bugs will be private for the blocklist form</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1673348" target="_blank">1673348</a>] request for possibility to prevent auto-assignment of bug to author of submitted patch if bug is leave-open or only disables tests</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1675466" target="_blank">1675466</a>] using browser's feature to got back one page in history from intermittent failures page for a bug goes to to blank …
=> Bumped version to 20201116.1

Bugzilla/API/V1/Configuration.pm, Bugzilla/API/V1/Teams.pm, Bugzilla/API/V1/User.pm, Bugzilla/App/API.pm, qa/t/rest_bugzilla.t
Missed adding CORS headers for new API endpoints. Added _insert_rest_headers() function. This will not be needed in as many places once everything resides under a single /rest path.
=> Bug 1678128 - Additional CORS headers are missing in the new versioned MOJO based REST API

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1678128" target="_blank">1678128</a>] Additional CORS headers are missing in the new versioned MOJO based REST API</li>
</ul>
=> Bumped version to 20201119.1

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1678513" target="_blank">1678513</a>] The request_uri column in the user_request_log table is not being populated properly</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1679081" target="_blank">1679081</a>] Global symbol "$C" requires explicit package name (did you forget to declare "my $C"?)</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1675625" target="_blank">1675625</a>] Refactor error handing in Mojolicious to allow for native mojo code to something other than Bugzilla::Error</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1677419" target="_blank">1677419</a>] Token cancellation and verification should take an extra step to confirm</li>
</ul>
=> Bumped version to 20201130.1

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1680302" target="_blank">1680302</a>] Under certain conditions, user will not be abe to login using header login form if path is /home</li>
</ul>
=> Bumped version to 20201202.1

template/en/default/account/prefs/mfa.html.tmpl, template/en/default/mfa/duo/verify.html.tmpl, template/en/default/mfa/totp/verify.html.tmpl
Actually, BMO on mobile uses `<input type="number">` to input verify code by MFA. This is incorrect to input it. `type=number` won't input "0" as head character.
Best practice for 2FA is `type="tel"` (https://web.dev/sign-in-form-best-practices/) or use `inputmode` attribute. All modern mobile browsers (inc. Fenix) support `inputmode` attribute, so we should use `inputmode` instead of `type=tel` or `type=number`.
=> Bug 1677416 - Use inputmode attribute for MFA.

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1677416" target="_blank">1677416</a>] Don't use &lt;input type="number"&gt; for MFA form on mobile</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1680775" target="_blank">1680775</a>] Hover position wrong</li>
</ul>
=> Bumped version to 20201215.1

extensions/Push/lib/Connector/Webhook.pm, extensions/Webhooks/Extension.pm
- Also update line in Extension.pm sub user_preferences to always set $push->set_config_last_modified() when changes are made to user webhooks as some cases were being missed.
=> Bug 1693860 - [WEBHOOKS] The Webhook push connector needs to return more details when an error occurs instead of just the code

.circleci/config.yml, Bugzilla/Component.pm, Bugzilla/Install.pm, Bugzilla/User.pm, admin.cgi, docs/en/rst/administering/users.rst, docs/en/rst/using/preferences.rst, editcomponents.cgi, enter_bug.cgi, extensions/ComponentWatching/Extension.pm, extensions/ComponentWatching/template/en/default/hook/admin/components/edit-common-rows.html.tmpl, extensions/Review/template/en/default/hook/admin/components/edit-common-rows.html.tmpl, qa/t/test_bug_edit.t, template/en/default/admin/admin.html.tmpl, template/en/default/admin/components/edit-common.html.tmpl, template/en/default/admin/components/edit.html.tmpl, template/en/default/admin/components/footer.html.tmpl, template/en/default/admin/components/list.html.tmpl, template/en/default/bug/create/create.html.tmpl, template/en/default/global/header.html.tmpl, template/en/default/global/messages.html.tmpl
Details:
- Create new edittriageowners system group and wrap the triage owner related fields with the new permission.
- Fixed work around for input_params and the ComponentWatching extension.
- Originally ComponentWatching relied on input_params for setting watch_user from editcomponents.cgi. Since a person who only has edittriageowners cannot edit watch_user, an error would be generated on update. 
- Also fixed some issues related to new bug description templates
- The way bug description templates were implemented, if a product has template defined and a component also had a template defined, the product template would always win out which was not as designed.
=> Bug 1708052 - Create edittriageowners group allowing specific users to edit triage owners of components but nothing else

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1690202" target="_blank">1690202</a>] Automatically set severity to S2 for all new bugs with the crash keyword</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1705743" target="_blank">1705743</a>] Make frequently reported bugs more obvious for enter bug form and duplicates.cgi more intuitive</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1708052" target="_blank">1708052</a>] Create edittriageowners group allowing specific users to edit triage owners of components but nothing else</li>
</ul>
=> Bumped version to 20210517.1

Bugzilla.pm
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1690203" target="_blank">1690203</a>] Automatically set priority to P1 when severity is set to S1</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1712619" target="_blank">1712619</a>] [GITHUBAUTH] Use authorization header instead of access_token query parameter when retrieving email addresses</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1713054" target="_blank">1713054</a>] Add "see also" support for ideas.mozilla.org</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1713599" target="_blank">1713599</a>] Add a card to the bug-creation flow directing user feedback to ideas.mozilla.org</li>
</ul>
=> Bumped version to 20210601.1

Bugzilla/Bug.pm, extensions/MozChangeField/lib/Post/ClearTrackingPriorityS1.pm, extensions/MozChangeField/lib/Post/CrashKeywordSetSeverity.pm, extensions/MozChangeField/lib/Post/SeverityS1PriorityP1.pm, extensions/Voting/Extension.pm, template/en/default/global/code-error.html.tmpl
When a comment is added it is not good idea to run $bug->update multiple times are it will try to add the same comment over again giving the duplicate key error. This change update Bugzilla::Bug::update to be able to be ran again and not try to re-add the comments.
=> Bug 1727027 - bug is not a valid parameter for the Bugzilla::Comment::create function

extensions/MozChangeField/Extension.pm, extensions/MozChangeField/template/en/default/hook/bug_modal/header-end.html.tmpl
- Disabled the requirement of comment on severity changes for now
=> Bug 1729270 - When changing severity from -- to something, bugzilla complains that a comment is needed

extensions/BMO/lib/Data.pm
This adds "Data Platform and Tools" product to the the `cf_crash_signature`
structure so that field is returned in the bug REST API.
=> Bug 1734463 - Add Data Platform and Tools to cf_crash_signature

.readthedocs.yaml, Bugzilla/DB/Schema.pm, Bugzilla/Install/DB.pm, docs/en/rst/requirements.txt, docs/en/rst/using/finding.rst
This is just the schema change related code copied over from the main PR so should be a quick check over.
What we do is merge this one first, do a deploy to production, run checksetup.pl and then do a second deploy with the rest of the application code. Minimizes risk of downtime.
=> Bug 1729091 - [GCP] Move as much as possible of data/params parameters to a table in the database (schema only)

extensions/BugModal/Extension.pm, extensions/BugModal/template/en/default/bug_modal/new_comment.html.tmpl, extensions/BugModal/template/en/default/hook/global/setting-descs-settings.none.tmpl, extensions/BugModal/web/bug_modal.js
for https://bugzilla.mozilla.org/show_bug.cgi?id=1742725
Add "User Interface" setting to enable/disable "attach pasted text" feature
=> Bug 1742725 - Add an option to disable the feature that converts long paste into attachment file.

skins/standard/global.css
STR:
0. set bugzilla to have the comment field at the top
1. open [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1741104) or any other bug with sufficient comments to cause scrolling
STR-A:
2. put the cursor in the comment field
3. scroll down with the mouse scroll wheel, without leaving the focus in the comment field
4. type any letter to bring the comment field back into view
STR-B:
2. scroll down to a comment near the bottom, then click the +/- button on the right-hand side of any comment to focus it
3. repeatedly hit shift-tab on the keyboard.
Expected: focused elements are always fully visible
Pre-patch: the header obscures focused elements and/or the top of the comment field
I tested this patch by just using the inspector to add the scroll-padding-top, and that seems to be …
=> no bug - Fix header interacting with scrolling using scroll-padding-top

extensions/PhabBugz/Extension.pm
While technically next works it is not the preferred way to return from a sub and is causing a warning in the logs over and over when a user object is changed. I can roll this fix out in the next normal deployment.
=> Bug 1751090 - Exiting subroutine via next at /app/extensions/PhabBugz/Extension.pm line 71.

extensions/BMO/Extension.pm
This just sets the component value to '' if not provided to eliminate the Perl warning from going to the logs.
=> Bug 1751596 - Use of uninitialized value $component in string ne at /app/extensions/BMO/Extension.pm line 2266.

Bugzilla/Search.pm, template/en/default/global/field-descs.none.tmpl, template/en/default/search/custom-search.html.tmpl
Adds two new advanced search operators:
- is disabled
- is not disabled
These operators only work with user fields.
=> Bug 1753429 - add ability to search for disabled/enabled users

scripts/build-bmo-push-data.pl
This allows us to commit a secure bug to github, deploy live and then verify that the fix works. All before the bug is made publicly available. This was a request of the security team.
=> Bug 1757970 - For private bugs, add placeholder to release announcement text instead of failing

extensions/BugModal/template/en/default/bug_modal/field.html.tmpl, extensions/BugModal/web/bug_modal.js
I agree that the Add button is a nuisance and we should just show single line text fields by default when clicking Edit. This is what happens in this patch for the see also field.
=> Bug 1191821 - The Add button when trying to add something to the See Also field is pointless

Bugzilla/App/OAuth2/Provider/Clients.pm, Bugzilla/App/Plugin/OAuth2/Provider.pm, Bugzilla/DB/Schema.pm, Bugzilla/Install/DB.pm, Bugzilla/Test/Util.pm, scripts/generate_conduit_data.pl, template/en/default/admin/oauth/provider/confirm-delete.html.tmpl, template/en/default/admin/oauth/provider/create.html.tmpl, template/en/default/admin/oauth/provider/edit.html.tmpl
This pull request adds another value to the client data stored in Bugzilla. The new value is a hostname that the client will have Bugzilla redirect back to once the user has approved the login request. This will allow Bugzilla to verify that the redirect hostname provided in the URL has not been changed to a different location which could steal the users token. If the redirect URL and its hostname has been altered, then the user is redirect back to the client site as if access request was not granted at all.
We can also put this change on bugzilla-dev for extra testing in addition to code review here.
=> Bug 1761594 - Bugzilla should reject redirect_uri tampering when being used for authentication with Phabricator

extensions/Bitly/template/en/default/hook/list/list-links.html.tmpl
In  general the order= parameter is stripped away (along with a few others) when creating URLs on the bug results page due to the way they are used for navigation. This patch adds the order= parameter and its value back just for the URL used to create the Bitly link so that when someone shares the short link, it retains the proper order as well.
=> Bug 1765286 - Creating a short URL of a bug list sorted by number of votes doesn't keep the sorting order in the short URL

Bugzilla/API/V1/Teams.pm, Bugzilla/App/API.pm
Fallout from a recent change with error handling.
1. Bugzilla/App/API.pm change to include the actual module loading error in the warning log message.
2. Include Bugzilla/Constants.pm module in Teams.pm to import the USAGE_MODE_MOJO_REST constant properly.
=> Bug 1766393 - https://bugzilla.mozilla.org/rest/config/component_teams returns `A REST API resource was not found`

Bugzilla/App.pm, Bugzilla/App/Plugin/OAuth2/Provider.pm, Bugzilla/Error.pm, template/en/default/global/user-error.html.tmpl
1. Bugzilla/App.pm sets the usage mode and stores away the universal controller for use by native Mojo code and routes.
2. Provider.pm now throws a user exception when  the redirect_uri hostname does not match the one configured for the OAutht2 client instead of just returning a false value as before. Before, when a false is returned, BMO just redirected to whatever redirect_uri had set and gave a request denied error to the client which was the incorrect solution in this case.
3. Error.pm removes the message value from stash as it was interfering with a different message value that is used sometimes in the templates and various BMO pages. In this case, message was unused and not needed.
=> Bug 1765917 - Open Redirectionwhen using OAuth2 authentication

extensions/Push/lib/Connector/Webhook.pm, extensions/Push/template/en/default/pages/webhooks_config.html.tmpl, extensions/Webhooks/Extension.pm, extensions/Webhooks/lib/Config.pm, extensions/Webhooks/lib/Webhook.pm, extensions/Webhooks/template/en/default/account/prefs/webhooks.html.tmpl, extensions/Webhooks/template/en/default/admin/params/webhooks.html.tmpl, extensions/Webhooks/template/en/default/hook/global/user-error-errors.html.tmpl, qa/t/test_webhooks.t
1. Update table schema to allow product_id column to be NULL which means any product.
2. Update product_name() and component_name() in Webhooks.pm to return 'Any' if product_id and/or component_id are NULL values in the DB.
3. Update the Push connector for Webhooks to allow all messages if product equals 'Any'.
4. Create a new permission group configuration option to limit amount of users who can select 'Any' as a product choice. Defaults to 'admin'.
5. Extended current test_webhooks.t test script to test for the 'Any' product support.
6. Fixed a current bug in the edit webhooks form where the component field name was incorrectly set to 'api_key'.
=> Bug 1752191 - [WEBHOOKS] Allow Webhook Setup with "Any" Product

Bugzilla/WebService/User.pm, docs/en/rst/api/core/v1/user.rst
The Docker development setup does not support my machine (Mac M1), so fully reling on the CI and the reviewer.
This PR is following @globau hints on [Slack](https://mozilla.slack.com/archives/C5F7KFJ4R/p1651586330688789?thread_ts=1651574356.938399&cid=C5F7KFJ4R).
=> Bug 1767484 - Expose `last_seen_date` in the `/rest/user` endpoint

docs/en/rst/api/core/v1/user.rst
The Docker development setup does not support my machine (Mac M1), so this PR is not tested yet. I will check the preview produced by `docs/readthedocs.org:bmo` to verify the fix.
=> Bug 1767563 - Fix the response table for the /rest/user endpoint

extensions/Voting/Extension.pm, extensions/Voting/lib/Vote.pm, extensions/Voting/template/en/default/hook/global/code-error-errors.html.tmpl
* Create a new Vote.pm class that stores the current vote data for a given user and bug id. By subclassing Object.pm we get the create() and remove_from_db() methods.
* Since there is not currently a table to track vote changes per user/bug over time, I decided to use the audit_log table to record the changes since they do not need to be visible in the UI. The audit_log table was not exactly compatible so I overrode the audit_log() method to use the bug_id as the identifier instead of the object id (normally the primary key of the table).
* Extension.pm changes are mostly to remove the direct SQL calls where appropriate and use the object methods for storing instead.
=> Bug 1767526 - Add auditing to the Voting extension to record changes to votes for bug and user

skins/standard/global.css
`.new-changes-link` has `z-index: 10`, so header should have higher z-index, so that `.dropdown-content` inside it is shown above `.new-changes-link`
=> Bug 1769246 - Make the header always above main content, in order to show request menu above other notifications.

Bugzilla/WebService/User.pm, docs/en/rst/api/core/v1/user.rst
If a user is a member of `mozilla-employee-confidential` then they are by default able to see the groups a user is a member of. This should be ok for employees to see but not the general public. The old group was `editusers` which was too narrow and a group we cannot just add people to for no good reason. Another part that used the `editusers` group was viewing whether a user was disabled or not and if they had email turned off. I changed that to be `disabledusers` instead which is the permission group allowed to edit those fields for any user in BMO anyway.
=> Bug 1769541 - Update group permission needed to view the groups a user is a member of using the REST API

extensions/PhabBugz/Extension.pm, extensions/PhabBugz/lib/WebService.pm, extensions/PhabBugz/web/js/phab_user.js, extensions/UserProfile/template/en/default/pages/user_profile.html.tmpl
This adds 2 links in the `user_profile` page in new "Phabricator" section, under "Review Queue" section.
One link for user's profile page that shows recent activity: [example](https://phabricator.services.mozilla.com/p/arai/)
Other link for user's open revisions: [example](https://phabricator.services.mozilla.com/differential/?responsiblePHIDs[0]=PHID-USER-ovlr37yfp3loy53g6wgo&statuses[0]=open()&order=newest&bucket=action)
~~The data is retrieved during showing the user_profile page, with 2 requests, 5 seconds timeout for each.~~
~~If any error happens (including the user not found on phabricator), or if phabricator is not configured, nothing is shown.~~
=> Bug 1769284 - Show phabricator links in user_profile

Bugzilla/Attachment/Archive.pm, t/001compile.t
Mainly this added some code to create a temp test DB using SQLite to allow the compiling of the Bugzilla/Model/* modules which require a DB. Also some critic warnings fixed in Archive.pm and 001compile.t
This does not *yet* test extension modules as there is added complexity to get them to load without lots of redefined warnings. I will address extensions as a separate bug.
=> Bug 1678376 - Make t/001compile.t Great Again

Bugzilla/Report/SecurityRisk.pm, scripts/secbugsreport.pl, template/en/default/reports/email/security-risk.html.tmpl
This PR basically just removes code that in the past attached 3 png charts to the security emails that are sent weekly. I have tested the code locally to make sure that the removals did not break the normal HTML tables that are generated in the email bodies.
=> Bug 1772402 - Remove chart attachments from the Security Bug Reports

Bugzilla/API/V1/Component.pm, Bugzilla/App/Plugin/Login.pm, docs/en/rst/api/core/v1/component.rst, docs/en/rst/api/core/v1/index.rst, qa/t/rest_components.t, qa/t/rest_triage_owners.t, template/en/default/global/user-error.html.tmpl
This PR introduces new API endpoints to the current REST API for managing components for products. It covers getting a component, editing a component and creating a new component. This API is in the new versioned area for adding REST API functionality that everything else will eventually be migrated to. I had to change some other non-related code such as API login to fix some error handling issues found during testing. This PR came about due to others wanting to update the triage owner field of components. Rather than make a special endpoint just for doing that one edit, I thought better to go ahead and make a more robust way of editing components that needed to be done eventually anyway. Please let me know if you have any specific questions related to these changes.
=> Bug 1773137 - New API endpoints needed for creating new components and editing current ones

Bugzilla/BugUrl/GitHub.pm
Adds the ability to add github project links to the see also field. The links take the form of https://github.com/USER_OR_TEAM_OR_ORGANIZATION_NAME/REPOSITORY_NAME/projects/111 which the regex will check for.
=> Bug 1774351 - Allow adding GitHub projects to "See Also"

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl, extensions/BugModal/web/bug_modal.js, skins/standard/global.css
for https://bugzilla.mozilla.org/show_bug.cgi?id=1775350
This adds drop down menu next to the current "Copy Summary" button (see the attachment).
The menu provides multiple kinds of text + format combination.
=> Bug 1775350 - Add dropdown menu to Copy Summary button that allows different text and format.

Bugzilla/Bug.pm, buglist.cgi, enter_bug.cgi, extensions/BMO/Extension.pm, extensions/BMO/lib/Data.pm, extensions/BMO/template/en/default/hook/bug/edit-after_op_sys.html.tmpl, extensions/BMO/template/en/default/hook/global/user-error-errors.html.tmpl, extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl, extensions/BugModal/template/en/default/bug_modal/header.html.tmpl, extensions/BugModal/web/bug_modal.css, extensions/BugModal/web/bug_modal.js, extensions/MozChangeField/web/js/severity-s1-priority-p1.js, qa/t/test_bug_edit.t, scripts/bug1764246.pl, scripts/generate_bmo_data.pl, skins/standard/global.css
Note: requires manual creation of a `can_triage_bugs` group, and a
`triaged` keyword.
- limits most features to products that follow Firefox triage processes
- adds "Mark as Triaged" button to show_bug, visible only to
can_triage_bugs members
- adds an indicator on show_bug when a bug is not triaged
- requires a severity to be set when adding the triaged keyword
- prevents users that are not in can_triage_bugs from being able to add
or remove the triaged keyword
- removes the triaged keyword when cloning bugs
- adds "is triaged" as a search field
- to find untriaged bugs use either:
- "is triaged" "is empty"
- "is triaged" "equals" "false" (or "no")
- add "is triaged" as an optional column to search results
- displays as "Yes" or "No"
- add migration script
- adds triaged keyword to all …
=> Bug 1764246 - Use "triaged" keyword to track bug's triaged state instead of severity

Bugzilla/App.pm, Bugzilla/App/BMO/NewRelease.pm, Bugzilla/Config/NewRelease.pm, qa/t/test_new_release.t, template/en/default/admin/admin.html.tmpl, template/en/default/admin/params/newrelease.html.tmpl, template/en/default/pages/new_release.html.tmpl
This new form will allow for quickly adding a new Firefox related milestone/version to the products selected. More details are in the bug.
To test:
```bash
$ docker compose down && docker compose build && docker compose up
```
Set your browsers proxy to localhost:1080. Go to http://bmo.test and login as the admin@mozilla.bugs user. Password is in the README.  You can then add a previous milestone and version to the Firefox product of 'Firefox 100' and '100 Branch' respectively. Then access the new release form from the Administrative menu. You should be able to select Firefox from both selects and add 101 to the test fields. When looking at the versions and milestones list, you should see the new 'Firefox 101' and '101 Branch' values create.
Ping me for any questions.
=> Bug 1776503 - [SELF-SERVICE] New form to add new version and milestone to select products when a new Firefox release comes out

extensions/BugModal/web/bug_modal.css, extensions/BugModal/web/bug_modal.js
- returns resolution buttons to aligning horizontally rather than
vertically
- hides 'mark as duplicate' button in main edit form when value is
RESOLVED or VERIFIED to avoid it dropping down to the next line and
pushing the bottom resolution buttons off the screen
=> Bug 1778930 - Fix alignment of resolution buttons

extensions/MozChangeField/lib/Pre/Graveyard.pm
Bugs in the 'Invalid Bugs' product _are_ allowed to be edited by the
reporter.  This allows them to move the bug should it be incorrectly
classified as invalid.
This carve-out also allows bugs to be created in the 'Invalid Bugs'
product by anyone.
=> Bug 1778935 - Allow reporters to edit bugs in the `Invalid Bugs` product

extensions/BMO/lib/Reports/Triage.pm
Adds  Developer Infrastructure to the default list of Firefox related products part of the Triage Owners form.
https://bugzilla.mozilla.org/page.cgi?id=triage_owners.html
=> Bug 1780043 - Please add "Developer Infrastructure" in the triage owner list

enter_bug.cgi, extensions/BMO/lib/FakeBug.pm, extensions/MozChangeField/Extension.pm, extensions/MozChangeField/lib/Post/TypePriSevEditbugs.pm, extensions/MozChangeField/template/en/default/hook/global/user-error-errors.html.tmpl, qa/t/test_bug_edit.t, template/en/default/bug/field.html.tmpl
These changes allow BMO to filter the priority and severity values on the new bug form. Also priority and severity are not cloned from another bug as we will need to triage the new bug just as if it was entered fresh. Also A new post rule is added to catch updating of the fields by non-permitted users using REST API calls.
=> Bug 1772408 - Not properly forbidding reporters to set the priority, severity and type fields unless they have editbugs privs for new bugs

Bugzilla/Install.pm, attachment.cgi, qa/t/test_bug_edit.t, template/en/default/attachment/edit.html.tmpl
Change the required group permissions from admin to new can_delete_attachments when showing the option to delete an attachment contents.
=> Bug 1780308 - Allow a group of users to delete attachments when needed due to sensitive information

extensions/PhabBugz/web/style/phabricator.css, skins/standard/global.css
Fore [bug 1780693](https://bugzilla.mozilla.org/show_bug.cgi?id=1780693)
=> Bug 1780693 - Use selected-control-background-color for the hovered phabricator revision row.

extensions/PhabBugz/lib/WebService.pm, extensions/PhabBugz/web/js/phabricator.js
This patch sorts the revisions by the stack order.
This patch does not show any graph, so if there's branch, that information is not shown, but at least the revisions table shows revisions in the order that reviewer needs to look.
On the server side, use `edge.search` API to get child revisions (in `_get_children_map` function), and add the info into the response,
by adding `"children": ["D1111", "D1112"],` property to the revision data (in `bug_revisions` function).
I've used dummy data during testing the feature, instead of actually calling `request` function.
So there might be some bug in the `request` function call.
On the client side, use the `children` property to sort the revisions in the stack order (in `sortRevisions` function).
The sort algorithm first sorts the revisions as …
=> Bug 1780733 - Sort phabricator revisions by stack order.

docs/en/rst/api/core/v1/component.rst, qa/t/rest_components.t
Update test script and documentation to better reflect the data returned from updating a component using the REST API. Looking at other APIs outside of BMO, it is more common to just return a 200 and the current object with the updated values. No need to add a 'changes' list as the client already knows what was changed.
=> Bug 1774673 - The new component API introduced by bug 1773137 has incorrect documentation about data returned from a component update

extensions/PhabBugz/template/en/default/phabricator/table.html.tmpl, extensions/PhabBugz/web/js/phabricator.js
This is a simple patch that reorders the columns in the Phabricator Revisions table so that the (possibly long) summary is the last column.
=> Bug 1781121 - moving both the status and reviewer columns before the summary for phabricator list make it more readable

Bugzilla/API/V1/Component.pm, docs/en/rst/api/core/v1/component.rst, qa/t/rest_components.t
Updated the routing for the /rest/component API endpoints to allow for component names with / in the name. If the product has a / in the name, then named query parameters must be used.
=> Bug 1782257 - /rest/component endpoint - handle cases where a component name has `/`

extensions/PhabBugz/template/en/default/phabricator/table.html.tmpl, extensions/PhabBugz/web/js/phabricator.js
A stack of:
* Reverse the revision order ([bug 1523847](https://bugzilla.mozilla.org/show_bug.cgi?id=1523847))
* de-jQuery
* some code cleanup
* Fix "Show Abandoned Revisions" checkbox handling
* Show graph in phabricator revisions ([bug 1782341](https://bugzilla.mozilla.org/show_bug.cgi?id=1782341))
=> Bug 1782341 - Show graph in phabricator revisions

js/productform.js
Code snippet removed as it is not strictly necessary and when removed, it fixes the issue where the component list is filtered based on Classifications selected on initial page load.
=> Bug 1782670 - In advanced search, some components are visible in the list when they shouldn't

extensions/BMO/template/en/default/email/bugmail.html.tmpl
This patch creates links instead of plain text values if the field that is changes is the See Also field. bugmail.html.tmpl is the template generates the HTML version of a bug change email. Text versions do not change.
=> Bug 1324011 - "See also" elements should be links in emails

Bugzilla/Bug.pm, extensions/BMO/Extension.pm
This issue was only occurring when changing component via the REST API and not through the UI, This was due the team name changing and using del_keyword(). del_keyword() had not yet initialized $self->{keyword_objects} to the real list so it assumed it was empty which essentially removed any keywords that were there. I updated del_keyword() to initialize by calling $self->keyword_objects in the for each loop which fixes this issue for API calls.
I also remove two unused variables in the extension hook as well as return early if not using triaged keyword for the product.
=> Bug 1782806 - move of bug to different component shouldn't drop its keywords

Bugzilla/App/Plugin/OAuth2/Provider.pm, Bugzilla/Token.pm, template/en/default/account/auth/confirm_scopes.html.tmpl
When running code under fully native Mojo code instead of the Mojo wrapper around legacy cgi scripts (all files with .cgi) we should not use the cgi method of printing the HTTP headers. The OAuth2 authentication process uses native Mojo code but yet calls a utility function in Token.pm that assumes it is running under a cgi environment. So when it tries to do `print $cgi->header` an error is thrown about the header() call masking the actual page that is supposed to be displayed explaining the real error. 
So I have update the utility function in Token.pm to check if it is running under Mojo native or cgi and return a data structure instead if running Mojo. Otherwise it prints the warning page as usual.
Provider.pm is updated to receive the result from the utility function and display a …
=> Bug 1783044 - Unable to link profile to People due to error page not being rendered properly

Bugzilla/Bug.pm, scripts/generate_bmo_data.pl
This PR changes the way we handle product changes when using the API (non-browser) when checking for the version field. It basically will fill choose the default version for the new product if the version value was omitted or was invalid. We already did this for milestones. Component values will still throw an exception if not valid as we do not have a default value for components like we do version and do not plan to.
Comments in the _set_product() function of Bug.pm will also explain more of what is happening here.
Note: Also had to fix a bug in generate_bmo_data.pl that was not populating the default version for a new product being INSERTed into the products table. This was missed in the earlier PR that added default version support.
Thanks!
=> Bug 1532985 - Changing the product fails because of mismatch in version, should just use default

Bugzilla/API/V1/Component.pm, qa/t/rest_components.t
This PR updates the permissions checking in the component update API code to also look for edittriageowners membership instead of the all encompassing editcomponents group. This supports the change we did a while back to the component admin UI that allowed those less privileged members to edit just the triage owner field. I also updated the rest_components.t test script to check this new behavior change.
=> Bug 1785454 - Update component editing API to not required full editcomponents to just update triage owner

whine.pl
Current behavior is we ignore whether an user is disabled or not and continue to send their whine events indefinitely. As you can imagine, this not ideal. This patch just skips the current event, resets the timer and does not send out the email. Then when the account is no longer disabled, the next schedule event will execute and send the email.
The other option was to delete the events when a user has been disabled, but that is not ideal as some accounts only get disabled temporarily and we do not want them to have to recreate the whines all over again.
=> Bug 1555583 - Remove whine queries owned by disabled users no longer with the company

Bugzilla/WebService/User.pm, docs/en/rst/api/core/v1/user.rst
This PR adds  a new `permissive` parameter which is similar to what we already have for getting a list of bugs. This parameter allows for ignoring errors when passing in a list of names to query for user information. If one or more cause an error such as not found, etc. it will just add the error to a `faults` list and return the ones that were found. This does not change the API in a way that would break any current clients so it should not be an issue.
=> Bug 1787294 - Allow optional tolerance in the /rest/user endpoint when querying users that are not exist

Bugzilla/Bug.pm, Bugzilla/Config/BugFields.pm, Bugzilla/WebService/Bug.pm, docs/en/rst/administering/parameters.rst, docs/en/rst/api/core/v1/bug.rst, qa/config/selenium_test.conf, qa/t/rest_last_change_time_non_bot.t, scripts/generate_bmo_data.pl, template/en/default/admin/params/bugfields.html.tmpl
This PR adds a new field that can be returned if explicitly requested with the get bug API endpoint. It is NOT returned by default. It is called `last_change_time_non_bot` and is the last time the bug was changed by a non-bot Bugzilla account. There is a new config parameter that allows storing a comma or space separated list of email addresses that are considered *bot* accounts. Any account in the list, their change will be ignored when returning the last_change_time_non_bot value. A test cases has also been added that tests to make sure the right timestamps are returned depending on which account updated the bug last.
=> Bug 1783576 - Add field to REST API that returns timestamp of bug last change by an actual person

Bugzilla/WebService/User.pm, extensions/Gravatar/Extension.pm, extensions/Review/Extension.pm, extensions/TagNewUsers/Extension.pm, extensions/UserProfile/Extension.pm
When a client was using `include_fields=requests` to get request information on one or more users, the data was not present as expected. This was due to the old way that extension code was looking for the `id` value for each user to look up request data, which was not there since it was not included. For example `include_fields=id,requests` would work but is a workaround. 
These changes pass the user objects as well as the result data along to the webservice_user_get extension hooks so that the objects can be used if needed to look up additional information. Using a for loop, we the result data and the user objects should line up one to one. 
Since the user_objects are now being passed along, I was also able to simplify the code in the other webservice_user_get sections in a few other …
=> Bug 1787954 - Certain fields missing from get user API when added by extensions and specifically requested with include_fields

Bugzilla/WebService/User.pm, extensions/Gravatar/Extension.pm, extensions/Review/Extension.pm
I failed to notice that the /rest/user/suggest API endpoint internally calls the same function that the /rest/user endpoint uses which I changed the data passed in bug 1787954.
So this changes /rest/user/suggest to match the data structure needed by the webservice_user_get hook function and also removed some redundant code.
=> Bug 1789654 - User matching for user related fields in the web UI is broken due to regression caused by bug 1787954

extensions/BMO/lib/Reports/Triage.pm, extensions/BMO/template/en/default/pages/triage_owners.html.tmpl
This PR adds a new column to the existing triage owners reporter. The column shows Yes or No if the triage owner for the component is in the default security group for the product the component belongs to. Triage.pm is the module that generates the data for the template and does the heavy lifting of checking for membership, etc. Only viewers who are in the mozilla-employee-confidential group should be able to see the column in the table. 
Thanks!
=> Bug 1790623 - Extend the Triage Owners report to include an indication if the Triage Owner is a member of the default security group

scripts/bug1789259.pl
I am going to run this script on bugzilla-dev obviously before running on production to make sure nothing bad happens.
=> Bug 1789259 - Convert trivial, minor, normal, major+ (for crashes) severities to new style severity

skins/standard/global.css
Update markdown table CSS to render correctly in any width.
Final result:
=> Bug 1726504 - Markdown tables are rendered incorrectly

Bugzilla/API/V1/Github.pm, Bugzilla/Config/Attachment.pm, qa/t/rest_github_pull_request.t, scripts/generate_bmo_data.pl, template/en/default/admin/params/attachment.html.tmpl, template/en/default/global/code-error.html.tmpl
Disregard the title changes in this PR as I was testing the webhooks with code on bugzilla-dev.allizom.org
This PR adds a new special API endpoint that can be used to add links to github pr to a bug report based on a bug id in the PR title. A webhook just needs to be created in the repository settings that points to https://bugzilla.mozilla.org/rest/github/pull_request for any pull request related changes. Also a shared secret will need to be obtained from the Bugzilla admin for authentication. A test script was added that tests to make sure the endpoint is working properly. Let me know if you have any questions or comments.
=> Bug 1792986 - Add Github API endpoint to be used for automatically linking PRs to bug attachments

extensions/PhabBugz/lib/Repository.pm, extensions/PhabBugz/lib/Revision.pm, extensions/PhabBugz/lib/Types.pm, extensions/PhabBugz/lib/WebService.pm, extensions/PhabBugz/template/en/default/phabricator/table.html.tmpl, extensions/PhabBugz/web/js/phabricator.js
This PR allows a revision to get more detailed repository information than before by creating a new Repository class with accessors. The new class does not allow for creating or updating, just retrieving. This allows for a new column in the Phabricator Revisions table of show bug to show the call sign of the repo for the revision.
=> Bug 1790883 - Bugzilla Phab attachments should include the repo callsign

extensions/BMO/template/en/default/global/choose-product.html.tmpl, extensions/GuidedBugEntry/template/en/default/guided/guided.html.tmpl, extensions/GuidedBugEntry/template/en/default/guided/products.html.tmpl
This PR updates the Fenix (Firefox for Android) selections for the standard enter bug page as well as the Guided bug entry form that new, non-empowered users see. Fenix no longer uses Github issues and now just files all bugs in BMO. Firefox for iOS still uses Github issues for general bugs but uses BMO for security bugs. As part of this, I fixed a bug in the Firefox for iOS selection on the Guided bug page that would still redirect to Github even if a security bug was being entered.
=> Bug 1795748 - Add the `Fenix` product in BMO's "choose from the following selections" list

Bugzilla/Bug.pm, Bugzilla/Field.pm, extensions/BugModal/lib/ActivityStream.pm, extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
Before this, when a bug is resolved as a duplicate of another bug, a comment was added to the duplicated bug but an entry was not added to the bugs_activity table with the bug id of the dupe. If someone looking a bugs history using the UI or the API, it would not show the new bug id entry in the history and the client would need to also look in the comments to parse out the bug id from the comment. This PR adds the duplicate bug id to the activity table so it will show up properly in the history API. The comment text of a the comment stays the same.
=> Bug 1795329 - Add dupe of and duplicates entries to bugs_activity table instead of just adding a comment

docs/en/rst/api/core/v1/github.rst, docs/en/rst/api/core/v1/index.rst
Restructured text documentation for setting up the new github linking feature added recently. Please review, making sure it is easy to understand and not a confusing mess :)
You can view a test build of the current version here: https://bmo--1944.org.readthedocs.build/en/1944/api/core/v1/github.html#github-setup-instructions
=> Bug 1797167 - Add documentation to the REST API detailing how to make a github PR work with BMO auto linking

Bugzilla/API/V1/Github.pm, qa/t/rest_github_pull_request.t
Once this lands I will need to update the docs in #1944 to describe the ping event being accepted. I can do the change as a no-bug type PR.
=> Bug 1797177 - Allow github linking API endpoint in BMO to also parse a ping event when someone first sets up the webhook

Bugzilla/Bug.pm, qa/t/test_security.t, qa/t/webservice_bug_get.t, qa/t/webservice_bug_get_bugs.t
This PR allows a user who has editbugs to still see private bugs in the dependencies/regressions lists even if they cannot see the full bugs. If the user does not have editbugs, then they don't display at all. This is true for the show activity page as well. Some adjustments were made to the test scripts to adapt to the new policy.
=> Bug 1692222 - Show bug ids in reference fields when user has editbugs even if the user cannot see the actual bugs

extensions/PhabBugz/lib/Feed.pm, extensions/PhabBugz/lib/Revision.pm
Teaches `phab-bot` to set `#release-managers!` review when
the uplift request form is submitted. Parses feed story text
for an uplift request change and uses the `stackGraph` field
to request review on each revision in the stack.
=> Bug 1791629: teach `phab-bot` to set `#release-managers!` review when uplift form submitted

extensions/BugModal/template/en/default/bug_modal/new_comment.html.tmpl, extensions/MozChangeField/Extension.pm, extensions/MozChangeField/lib/Pre/CommentClosedBugs.pm
This PR adds a new module that blocks adding a comment to a CLOSED bug if the user is not in editbugs, or does not have a direct role in the bug such as reporter, assignee, or qa contact. The template will show text in place of the comment field if they are blocked with a reason. This also blocks adding comments via the API if the user is not allowed. Let me know if you have any questions.
=> Bug 1196291 - Prevent users without editbugs from commenting on resolved bugs, unless they are already involved in the bug

Bugzilla/API/V1/Github.pm, qa/t/rest_github_pull_request.t
This patch will make the description of the new attachment to show more detail about the PR. The format will be `[$repo_name] $title (#$pr_number)`.
=> Bug 1799924 - Include repository name and pr number in description of Github PR

userprefs.cgi
Oh the careless mistakes :( This properly passes in the CGI param 'mfa' into `Bugzilla::MFA->new_from($user, $mfa)` instead of the value for $mfa_token which is totally different than what new_from is expecting. $mfa can only be 'TOTP' or 'Duo' and not a token hash string.
Same for `SaveMFAupdate($event->{action}, $mfa);`. It is expecting either 'TOTP' or 'Duo'. 
This fixes the issue locally and I will reconfirm on staging once it reaches it.
=> Bug 1801026 - 504 Gateway time-out while configuring Duo 2FA

Bugzilla/API/V1/Github.pm, Bugzilla/Config/Attachment.pm, scripts/generate_bmo_data.pl, template/en/default/admin/params/attachment.html.tmpl, template/en/default/global/code-error.html.tmpl
Adds a config parameter to disable github pr linking if necessary.
=> Bug 1801343 - Need a way to disable the github PR linking if needed 

scripts/remove_idle_group_members.pl
Also removed the ORDER BY portion since 1) it was causing the script to fail with `Expression #1 of ORDER BY clause is not in SELECT list, references column 'bugs.profiles.login_name' which is not in SELECT list; this is incompatible with DISTINCT' and 2) any kind of order for this particular script doesn't really matter.
=> Bug 1802735 - Quoting groups in remove_idle_group_members script

Bugzilla/Report/SecurityRisk.pm
WIth the change to GCP MySQL, the error about aggregate functions and GROUP BY under mysql strict mode popped up. This change fixed the SQL that was causing the error by removing the GROUP BY and CONCAT functions which are not even needed in this code. Not sure why they were being used in the first place.
=> Bug 1804082 - Cron jobs require sql_mode=only_full_group_by

Bugzilla/Config/MTA.pm, Bugzilla/Mailer.pm, template/en/default/admin/params/mta.html.tmpl
This allows for more configurability of SMTP for connecting to a remote server. Some require TLS and some do not and sometimes the port can be different than the standard.
=> Bug 1803867 - Add SMTP config options for enabling tls and specifying port number

Bugzilla/WebService/User.pm, docs/en/rst/api/core/v1/user.rst
This is needed for https://github.com/mozilla/relman-auto-nag/issues/1807
=> Bug 1805179 - Expose `creation_time` in the `/rest/user` endpoint

Bugzilla/API/V1/Github.pm, docs/en/rst/api/core/v1/github.rst, qa/t/rest_github_pull_request.t
This PR changes to code to show 400 failures only if the JSON is invalid or the signature is invalid. All other errors should return 200 even though they are non-fatal errors. I have added a new key/value called `error` that is a boolean. If true, then a `message` is provided with the error message but the status code is 200. This should show green results in the webhook log in Github unless something serious happens.
=> Bug 1805681 - github pull request webhook returns 400

.perlcriticrc, extensions/PhabBugz/lib/Feed.pm, extensions/PhabBugz/lib/Revision.pm
Re-implements the Bugzilla updating logic in the Phabricator Uplifts extension into BMO PhabBugz feed reader.
First add the uplift request form to `Revision.pm` so it is accessible from the feed. The form is either an empty
array or a `Dict` of `Any` keys, where the keys are the form questions and the values are the answers.
Move uplift request form processing into its own function to avoid a massive `process_revision_change` function.
Add A function `format_uplift_request_as_markdown` to render the form as a markdown comment, and add a
`readable_answer` function to convert `1` and `0` values to `yes` and `no` respectively. Use the markdown rendering
function as the contents of a comment on the bug when the form is submitted. Add a check for the `Needs manual QE test` question to set …
=> Bug 1805453: implement Bugzilla-updating logic from Phab uplift extension in Phab Feed reader

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
The expand/collapse code needs for a `<pre id="ct-X"></pre>` to be present for the code to execute properly. So when we attach an attachment without a comment, the `<pre>` was missing. This patch adds it back but leaves it empty so that expand/collapse can still work properly.
=> Bug 1811786 - Unable to expand an attachment comment after it has been tagged with `admin`

extensions/PhabBugz/lib/Feed.pm
Simplified the flag code which also fixes the multiple flag error we are getting sometimes. Also check $revision->uplift_request to make sure it is a HASH and not empty before proceeding.
=> Bug 1812384 - Error occurring when $revision->uplift_request in Phabbugz is being interpreted as true when it is really empty

Bugzilla/API/V1/Github.pm
This pull request looks for attachments with the same pull request number in the filename but then also does a comparison of the attachment data containing the html url of the pull request. If they match then it is skipped, otherwise it moves the attachment to the different bug as before. Before this change we were only looking at the pull request number which causes issues when two repos have the same number.
=> Bug 1812606 - github pull request with the same number but from different repos get confused

Bugzilla/API/V1/Github.pm, docs/en/rst/api/core/v1/github.rst
This pull request gets rid of the more complex regex for finding IDs in commit titles and just simplifies it down to just looking for a specific format. In the past we were mistakenly linking to non bug IDs if an integer was found in the title such as a pull request id. This change will require the titles to contain "Bug XXX", "bug XXX", or "bug - XXX".
=> Bug 1803374 - Numbers in PR descriptions are considered bug numbers by the Bugzilla GitHub integration

extensions/PhabBugz/lib/API/V1/Lando.pm, qa/config/selenium_test.conf, qa/t/rest_lando_uplift.t, scripts/generate_bmo_data.pl, scripts/generate_conduit_data.pl, template/en/default/global/code-error.html.tmpl
I tried to keep the API the same as what you code currently expects so that all you would need to do is update the actual endpoint and nothing else. 
Implemented GET and PUT functions. The first should return the id, the whiteboard, and current tracking flag values. The PUT just allows updating the whiteboard and status flags. The return data from both should be the same as the normal API endpoints. 
Let me know if you want me to throw this on bugzilla-dev.allizom.org for testing.
=> Bug 1814226 - create a custom API endpoint for uplift automation bug changes

Bugzilla/Util.pm, extensions/BMO/Extension.pm
* Wrap the call to the product versions API in a try block.
* This allows bug page and search page to load properly in the even the endpoint is unavailable or misconfigured.
* Code in BMO extension needed updating to not check for a hash key before determining if the hash has values..
=> Bug 1820859 - Wrap code that looks for a latest nightly/stable versions of Firefox in try/catch block in case of failure

js/global.js, template/en/default/global/header.html.tmpl
- move `<h2>` outside of the quicksearch combo role; it being there breaks the ability for screen readers to navigate to the search field
- add a keyboard shortcut to focus quicksearch: alt+s / opt+s
=> Bug 1821251 - fix accessibilty to search field in header, and add a shortcut to focus it

Bugzilla/API/V1/Github.pm, qa/t/rest_github_push_comment.t
According to https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#push, author.name is required but author.username is not required to be included in the event JSON. So no need to use the committer object as a last resort.
If we have to user author.name, then we omit the `https://github.com/<username>` part in the comment.
=> Bug 1821478 - [GITHUB] Fall back to author.name if author.username is missing

Bugzilla/API/V1/Github.pm, qa/t/rest_github_push_comment.t, scripts/generate_bmo_data.pl
* If a bug is being closed and it is firefox-android, then we also set the milestone to the latest nightly branch
* generate_bmo_data.pl adds the 111 Branch milestone needed for testing.
* Update the test script to check that the milestone has been set properly if bug is closed.
=> Bug 1821386 - Set the Milestone field when resolving bugs after PR merges

Bugzilla/API/V1/Github.pm, qa/t/rest_github_push_comment.t
* Update the test script to look for proper history entries to make sure we are adding them properly and no duplicates
* Switch to using $bug->set_all before $bug->update. This is how process_bug.cgi work and we should us that so as to not duplicate by performing update steps manually. This also allows to use the LogActivityEntry that is in TrackingFlags extension instead of logging ourselves as before causing the duplicate issue.
=> Bug 1825848 - LogActivityEntry is be called twice instead of once when the github push comment API code is executed

extensions/BugModal/Extension.pm
This PR adds some debugging entries to the log under specific circumstances so we can get a better view in to the flag data when an error occurs. See bug 1825846 for more detail. I will be able to search the logs for occurrences of the bug.
=> Bug 1825846 - Add debugging statements to BugModal code to log when incorrect tracking flags are detected

Bugzilla/API/V1/Github.pm, qa/t/rest_github_push_comment.t
For a better idea of why this change is being made and what the flow should be now with the latest fix, see https://bugzilla.mozilla.org/show_bug.cgi?id=1825899#c1 Thanks!
=> Bug 1825899 - BMO push hook shouldn't set the status flag to fixed if the leave-open keyword is set

extensions/BMO/web/js/edituser_menu.js, extensions/BugModal/template/en/default/bug_modal/user.html.tmpl, extensions/BugModal/web/bug_modal.js, template/en/default/global/user.html.tmpl
Adds a new entry in the user menu that drops down when you click on a user name on the show bug page. The menu entry simply copies the user's real name to the clipboard which can then pasted into the comment area. A notification is also displayed briefly that indicates the text was copied.
=> Bug 1827272 - Add Copy Name command to user's menu

Bugzilla/WebService/Group.pm, qa/t/rest_group_get.t
This change makes it where anyone in mozilla-employee-confidential can see information about any group in BMO. Otherwise the user can only see if they are able to bless others into the group or have the empowered 'editusers' group.
=> Bug 1824111 - Update group permission needed to view the groups using the `/rest/group` endpoint

Bugzilla/Util.pm, extensions/BugModal/Extension.pm, extensions/BugModal/template/en/default/bug_modal/header.html.tmpl
- flags.js was not loading properly which controls the flag comments
- We need to run template_before_process when bug_modal/header.html.tmpl is loaded since the code that loads flags.js in in that template and not bug_modal/edit.html.tmpl.
- Removed an leftover debug statement from Bugzilla/Util.pm
=> Bug 1828653 - relnote form is not added when setting the relnote flag for nomination

extensions/PhabBugz/lib/Feed.pm
https://stackoverflow.com/questions/59998409/error-code-3685-illegal-argument-to-a-regular-expression
"This question will probably become more popular as adoption of MySQL 8.0 increases and previously-stored SQL queries using REGEXP start to break.
According to [MySQL 8.0 Reference Manual / ... / Regular Expressions](https://dev.mysql.com/doc/refman/8.0/en/regexp.html), "MySQL implements regular expression support using International Components for Unicode (ICU)."
According to [MySQL 5.6 Reference Manual / ... / Regular Expressions](https://dev.mysql.com/doc/refman/5.6/en/regexp.html), "MySQL uses Henry Spencer's implementation of regular expressions."
Therefore, since you are using MySQL 8.0, rather than using [[:<:]] and [[:>:]], you can now use \b."
We are using 8.0 now with the move …
=> Bug 1828677 - Invalid regex in BMO feed reader: `The regular expression you provided ':?:phab\\-bot[[:>:]]' is not valid`

extensions/PhabBugz/lib/Repository.pm, extensions/PhabBugz/lib/Util.pm
When a new Phabricator revision attachment is being added to a bug,
check if the repo associated with the revision is an uplift repo and
set the appropriate `approval-mozilla-{repo}` flag if necessary.
To determine if a repo is an uplift repository, we add the `projects`
attachment from Phabricator to the Conudit API query which returns
repository data. We add a `projects_raw` and `projects` field which
is the raw API response and an array of built `Project` objects in
Bugzilla, respectively. Then we add an `is_uplift_repo` function which
iterates over the `project` attribute and checks for a project with
the name matching `uplift`.
=> Bug 1825961: set `approval-mozilla-{repo}` flags on uplift revision attachments

extensions/PhabBugz/lib/Revision.pm
In suite it is possible to hit an edge case where the stack_graph_raw
attribute is not defined in the Phabricator API response. While we
investigate this problem we should make the stack_graph_raw attribute
a Maybe.
=> Bug 1830152: make the `stack_graph_raw` attribute a `Maybe`

extensions/BMO/Extension.pm, extensions/BMO/template/en/default/bug/create/create-web-bounty.html.tmpl
Added messages (from bug report) to the web bounty form to inform about HackerOne. I also changed the product from mozilla.org to Websites in Extension.pm since Websites is not the proper product and was not changed when the restructuring happened a while back.
=> Bug 1831576 - Modify web bug bounty form

.readthedocs.yaml, Bugzilla/Mailer.pm, docker-compose.yml
Simple change that adds a special SES header to all emails that has a value that can be set with an environment variable. This allows for BMO emails to be uniquely identified in SES when grouped with other sites and dealing with bounces, etc.
=> Bug 1832364 - Add support for AWS SES configuration sets to Mailer

.readthedocs.yaml, extensions/PhabBugz/lib/Feed.pm, extensions/PhabBugz/lib/Util.pm, extensions/PhabBugz/lib/WebService.pm
This patch adds the '?' status for revisions that are also in the draft state which is the state the revision is set initially when it is first created. THis error occurred when a new revision was created against a repository (mozilla-beta) in Phabricator that had the uplift tag associated with it.
=> Bug 1832391 - Phabricator feed process crashes when a revision is in draft status and setting approval-mozilla-* flag on the new attachment

.readthedocs.yaml, extensions/PhabBugz/lib/Feed.pm
While processing new users in Phabricator, phabbugz would hit an account in Phabricator that had a bugzilla user id stored that did not for some reason exist in the Bugzilla database. Phabbugz would die on this error and start over and then hit the same user again. This had been going on for quite some time :( This change will skip the bogus bugzilla user id and go to the next.
=> Bug 1832408 - New user code in Phabbugz is failing on a specific account and starting over each time from the last successful id

extensions/PhabBugz/lib/Feed.pm
…uest_as_markdown still tries to generate a comment causing hash error
=> Bug 1833441 - If revision->uplift_request is empty, format_uplift_request_as_markdown still tries to generate a comment causing hash error

Bugzilla/Group.pm, extensions/BMO/lib/Reports/Groups.pm, extensions/BMO/template/en/default/pages/group_members.html.tmpl
* Some cleanup of the group member report by adding a table for the different query fields
* Extend Bugzilla::Group->members_complete to take an argument that will filter results based on search type
* non-mozilla search type filters the users to only show email addresses that do not match the groups regex if one exists.
* The regex is used by Mozilla to automatically place users in specific confidential groups.
* Figured this would be better than hard-coding '.*@mozilla(foundation)?\.(org|com)' and all of the other possibilities.
=> Bug 1831632 - Update group membership report to more prominently display users are in groups that not Mozilla email addresses (i.e. personal accounts)

extensions/SiteMapIndex/Extension.pm, extensions/SiteMapIndex/bin/rebuild_index.pl, extensions/SiteMapIndex/lib/Config.pm, extensions/SiteMapIndex/lib/Util.pm, extensions/SiteMapIndex/template/en/default/admin/params/sitemapindex.html.tmpl, extensions/SiteMapIndex/template/en/default/hook/robots-end.txt.tmpl, template/en/default/robots.txt.tmpl
This PR updates the SiteMapIndex extension to no longer dynamically generate the needed sitemap xml files needed for search engine indexing. Instead the robots.txt file will not redirect the indexer to the xml files located on an AWS S3 bucket. The sitemap xml files will be generated by a cron container that will run once per day and be set up by Cloud Ops.
* Added a SiteMapIndex configuration panel for setting the aws credentials and bucket name.
* robots.txt has been updated to display the `Sitemap: url` if enabled and the bucket name exists. instead of checking for hostname.
* A new script `rebuild_index.pl` has been added that generates the xml files and uploads to S3.
=> Bug 1839929 - Need to update SiteMap extension to upload xml files to S3 and to do nightly as a cron task

extensions/BMO/Extension.pm, extensions/BMO/lib/Reports/WhatsNext.pm, extensions/BMO/template/en/default/hook/reports/menu-end.html.tmpl, extensions/BMO/template/en/default/pages/whats_next.html.tmpl, extensions/BMO/web/js/whats_next.js, extensions/BMO/web/styles/reports.css, qa/config/generate_test_data.pl, qa/t/1_test_whats_next.t, scripts/generate_bmo_data.pl, skins/standard/global.css, template/en/default/global/header.html.tmpl
Follow goals for this PR:
* New report that shows several tables listing what bugs a developer should focus on next according to requirements laid out in https://docs.google.com/document/d/1X3VU0ggVKAFdnUSls3pcwpnrZa_Eb_-5tVj1rRvN1p8/edit#heading=h.8z0sho6pod67
* Report is accessible to users with editbugs or higher from the standard Reports page
* Each table is generated with a custom SQL instead of using Search.pm in order to match specific fields not possible with Search.pm
* The bugs are filtered based on permissions so nothing sensitive can be leaked.
* The report defaults to the current user, but another user can be entered and show their results instead.
* The SQL can be tweaked if we need finer detail or the results are not what is expected.
* There is a new …
=> Bug 1835941 - Create a new report for "What should I work on next?" to help engineers see bugs matching a specific search criteria

Bugzilla/Series.pm
* additional place where the code needed to be changed to allow non-admins to make a chart series publicly viewable.
=> Bug 1844801 - Updates charting UI to allow users in special chartpublicgroup to allow setting charts as public

template/en/default/account/prefs/account.html.tmpl, userprefs.cgi
To make it case insensitive like it is the case for login. See https://bugzilla.mozilla.org/show_bug.cgi?id=1849069
=> Bug 1849069 - Real name change doesn't work if "New email address" is pre-filled with different email by password manager

extensions/MozChangeField/lib/Pre/CommentClosedBugs.pm
* Updates the code that blocks commenting on closed bugs for those without editbugs
* Allow someone who is the needinfo on the bug to comment. 
* Once the comment is made that clears the needinfo, the same user cannot then comment again.
=> Bug 1847640 - Users cannot clear their needinfo in a bug that's closed, if they lack editbugs

template/en/default/global/header.html.tmpl
Adds a new link to the main header drop down that takes user to page where there are quicksearch docs. We used to have these in  a different place and was removed without a new link added.
=> Bug 1848882 - Add a link to the quick search help from the main header drop down

extensions/Push/lib/Daemon.pm, extensions/Push/template/en/default/hook/global/messages-messages.html.tmpl
This adds additional checking code to the Push extension daemon. When running the command with the `check` parameter, instead of just returning a PID as is the default, we also check to make sure the database is up and accessible. In the recent past, the database disappeared and the daemon continued to run and checkout but the log was full of MySQL connection errors. This code change allows for Kubernetes to do a liveness check and restart the POD if the daemon can no longer access the database.
=> Bug 1861260 - Update the Push extension to add additional status check code in order to restart the pod if an error is occurring

extensions/BMO/Extension.pm, extensions/SecureMail/Extension.pm
Several small fixes to remove uninitialized value warnings from logs and automated tests.
=> Bug 1866162 - Fix several 'use of initialized value...' errors when running the automated UI tests

extensions/PhabBugz/lib/Feed.pm, extensions/PhabBugz/lib/Util.pm
Add a new positional argument to `set_attachment_approval_flags` that represents the
Bugzilla user making a change to the approval flag status. Use the Bugzilla user of
the revision changer instead of deriving the flag setter from the author of the
revision.
=> Bug 1825961: set approval flags as the revision changer instead of author

extensions/BugModal/template/en/default/bug_modal/field.html.tmpl
Fix https://bugzilla.mozilla.org/show_bug.cgi?id=1870044
What the code comment says. We don’t need the asterisk for Type on the show_bug page.
=> Bug 1870044 -  Red star next to the Type field when viewing bugs

.circleci/config.yml, .github/workflows/ci.yml, .github/workflows/deploy.yml, Bugzilla/DaemonControl.pm, Bugzilla/Test/Selenium.pm, Dockerfile, Dockerfile.bmo-slim, docker-compose.test.yml, qa/config/selenium_test.conf, qa/t/lib/QA/Util.pm, scripts/entrypoint.pl, t/bmo/bounced-emails.t, t/bmo/passwords.t
This allows our tests to use Mozilla Firefox 115.5.0esr instead of the older version in selenium/standalone-firefox
=> Bug 1871414 - Update Selenium test suite to use a more recent version of Firefox to support new features

extensions/PhabBugz/lib/Feed.pm, extensions/PhabBugz/lib/Util.pm, extensions/PhabBugz/t/feed-daemon-guts.t
This PR updates the subroutine that is used to get the next list of feed stories from Phabricator based on the last successful feed ID stored. It will try the next ID but if it fails with the familiar `does not identify a valid object` then it will increment and try the next ID up to 5 increments. If after 5 then it will just return an empty list like we do currently and an admin will need to step in.
=> Bug 1870549 - When grabbing the next story id, sometimes it is invalid so we should try to grab the next one up to 5 tries

extensions/BugModal/web/bug_modal.js
[Bug 1873447 - On the new bug form, can't use control-E on Mac to go to the end of fields](https://bugzilla.mozilla.org/show_bug.cgi?id=1873447)
This is not actually a regression but due to a typo in `nodeName`. I’m simply replacing it with modern DOM 🙂
=> Bug 1873447 - On the new bug form, can't use control-E on Mac to go to the end of fields

Bugzilla/Test/Selenium.pm, extensions/BugModal/template/en/default/bug_modal/create.html.tmpl, extensions/BugModal/template/en/default/bug_modal/field.html.tmpl, extensions/BugModal/template/en/default/bug_modal/flags.html.tmpl, extensions/BugModal/template/en/default/bug_modal/header.html.tmpl, extensions/BugModal/template/en/default/bug_modal/tracking_flags.html.tmpl, extensions/BugModal/web/bug_modal.css, extensions/BugModal/web/bug_modal.js, extensions/BugModal/web/create.js, js/components/select.js, qa/t/1_test_bmo_retire_values.t, qa/t/1_test_bug_edit.t, qa/t/1_test_choose_priority.t, qa/t/2_test_flags.t, qa/t/2_test_flags2.t
[Bug 1870891 - Replace native `<select>` with custom element with search bar](https://bugzilla.mozilla.org/show_bug.cgi?id=1870891)
This PR replaces most of the native `<select>` elements on the enter_bug and show_bug pages with new custom elements. A search bar appears when there are 10 or more options for easier filtering. The component dropdown displays the component description in a popover.
Implementation note: These dropdown lists and popovers are created using `<dialog>` (modal [top layer](https://developer.chrome.com/blog/what-is-the-top-layer)) instead of the [Popover API](https://developer.chrome.com/blog/introducing-popover-api/) (non-modal top layer) because the latter is [not yet enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1866993) in Firefox other than Nightly. …
=> Bug 1870891 - Replace native <select> with custom element with search bar

extensions/BugModal/web/bug_modal.js
[Bug 1873913 - The request information feature no longer autofills the selected person's email into the text box](https://bugzilla.mozilla.org/show_bug.cgi?id=1873913)
There are two “dirty field tracking” functions in `bug_modal.js`. I’m not fully understanding what’s happening there, but in #2157 I forgot to update one to match the custom element, and it caused  an error.
> Uncaught TypeError: that.data(...) is undefined at bug_modal.js:1609:47
=> Bug 1873913 - The request information feature no longer autofills the selected person's email into the text box

skins/standard/global.css
[Bug 1873826 - Scrollbar gets hidden when opening dropdown menu](https://bugzilla.mozilla.org/show_bug.cgi?id=1873826)
This PR supersedes #2165 using a CSS-only approach. Tested on my macOS Sonoma + Firefox, and worked nicely.
=> Bug 1873826 - Scrollbar gets hidden when opening dropdown menu

js/components/select.js
[Bug 1874015 - Can no longer open-select-close bugzilla dropdowns in a single drag gesture](https://bugzilla.mozilla.org/show_bug.cgi?id=1874015)
This mimics the behaviour of the native `<select>` element, allowing to select an option with mouse down + mouse move + mouse up, not just click + click.
=> Bug 1874015 - Can no longer open-select-close bugzilla dropdowns in a single drag gesture

Bugzilla.pm, Bugzilla/Config/Auth.pm, Bugzilla/User.pm, Bugzilla/WebService/User.pm, editusers.cgi, qa/t/1_test_duo_requirement.t, template/en/default/account/prefs/mfa.html.tmpl, template/en/default/admin/params/auth.html.tmpl, template/en/default/global/messages.html.tmpl, template/en/default/global/user-error.html.tmpl, userprefs.cgi
* This pull request adds two new config parameters, `duo_required_group` and `duo_required_excluded_group`. 
* Any user that is added to the `duo_required_group` will automatically be redirected to the MFA preferences page if their current MFA is not set to `Duo`.
* There they will be able to configure `Duo` for their account using the standard enrollment procedure.
* If the user account is a member of the `duo_required_excluded_group`, then they will not be redirected to the MFA page and will operate normally.
* Only bot accounts (addresses ending in tld or bugs) should be allowed to be added to the excluded group.
* If a member of the required group is removed from that group, they are logged out, their password is cleared, and their MFA is cleared. They can then reset their password …
=> Bug 1861888 - Requiring Staff To Use Duo 2FA On Bugzilla

Bugzilla/Net/Storage.pm, scripts/migrate-attachments.pl
- Adds --class option to migrate-attachments.pl to just update the class names in the atachment_storage_class table from one value to another.
- This is useful for when the data is already migrated from net storage to another using external means and we just want the data to be loaded from the new location
- Also made some fixes to the migration script that properly calculates the number of attachments that will be affected. Before if was mistakenly just counting all attachments regardless of source.
- Updated Storage.pm to properly encode the returned content into UTF8 to fix a bug with using the fake GCS server as test platform.
=> Bug 1875961 - Update attachment migration script by adding option to only update the class and not actually copy the data

js/components/select.js
Reverts mozilla-bteam/bmo#2171
=> Revert "Bug 1874037 - Type to search options doesn’t work with custom <bz-select> element having no search bar"

extensions/BugModal/web/bug_modal.js
Reverts mozilla-bteam/bmo#2163
=> Revert "Bug 1873447 - On the new bug form, can't use control-E on Mac to go to the end of fields"

Bugzilla/App/BMO/NewRelease.pm, qa/t/3_test_new_release.t, template/en/default/pages/new_release.html.tmpl
When adding new version and milestone using the admin new release UI, it should be able to automatically disabled the proper older ones at the same time.
- Adds new text fields for old milestone and version to disable. Automatically defaults values to new release - 10.
- Updates test script to test for disabling of old versions and milestones.
=> Bug 1877294 - When adding a new version and mileston when new Firefox is released, disabled old versions and milestones 10 releases or older

Bugzilla/Auth.pm, Bugzilla/Config/Auth.pm, Bugzilla/User.pm, docs/en/rst/administering/parameters.rst, docs/en/rst/administering/users.rst, index.cgi, qa/config/generate_test_data.pl, qa/t/1_test_create_user_accounts.t, template/en/default/account/auth/login.html.tmpl, template/en/default/account/create.html.tmpl, template/en/default/account/email/request-new.txt.tmpl, template/en/default/admin/params/auth.html.tmpl, template/en/default/global/header.html.tmpl, template/en/default/welcome-admin.html.tmpl
* Remove the unused createemailregex parameter which was originally also used for disabling new account creation.
* Added a new allow_account_creation parameter which is a boolean and defaults to on.
* Now we can disable quickly and re-enable quickly account creation when needed for spammers, etc.
* Update test cases to use the new parameter.
=> Bug 1881309 - Create new admin parameter to disabled new account creation

extensions/BMO/Extension.pm, qa/t/1_test_bmo_autolinkification.t
The new CVE website from mitre is https://www.cve.org/, replacing https://cve.mitre.org/. From https://cve.mitre.org/:
>    NOTICE: Transition to the all-new CVE website at WWW.CVE.ORG and CVE Record Format JSON are underway.
>
>    NOTICE: Legacy CVE download formats deprecation is now underway and will end on June 30, 2024. New CVE List download format is available now.
As far as I know, new CVEs also have a delay before they appear on https://cve.mitre.org/, while they appear instantly on https://www.cve.org/. The autolinks from BMO for CVE-IDs should probably be updated to that new site.
=> Bug 1882734 - Use new CVE website for linking CVE-IDs

Bugzilla/App/BMO/NewRelease.pm
Disabling n-10 version/milestone was disabling releases that Thunderbird still cared about. So I am increasing to 15 as this should still be fine for other products as well such as Firefox.
=> Bug 1886266 - Change the number of old releases to go back and disable from 10 to 15

Bugzilla/BugMail.pm, Bugzilla/Mailer.pm, Bugzilla/Util.pm, t/007util.t
Similar to addresses @.(bugs|tld) we should also not send email to the [nobody@mozilla.org](mailto:nobody@mozilla.org) (default assignee, etc.) address as it is only a placeholder and isn't meant to be delivered to.
=> Bug 1886289 - Never attempt to send mail to nobody@mozilla.org

extensions/BugModal/web/attachments_overlay.js, js/field.js
[Bug 1887999 - Approval request dropdowns sometimes not visible with modal Details dialog](https://bugzilla.mozilla.org/show_bug.cgi?id=1887999)
The problem could be reproduced if there were multiple attachments with and without flags.
Remove an unnecessary check for cloned rows, which is actually done by `foundTypeIds`. Also, fix user autocomplete on requestee fields not working on these cloned rows.
=> Bug 1887999 - Approval request dropdowns sometimes not visible with modal Details dialog

extensions/PhabBugz/lib/Feed.pm
Add an array which contains the correct order of uplift request form
fields to ensure they are always presented in the correct order in
the comment. Add the repo's short name to the header so it is more
obvious which request the form corresponds to. Use a smaller header
size to more closely align with the existing Bugzilla uplift request
form.
=> Bug 1861776: improve usability of the uplift request form comment

extensions/BugModal/web/attachments_overlay.js
[Bug 1888524 - javascript error when creating and viewing some bugs: can't access property "querySelector", $overlay is null](https://bugzilla.mozilla.org/show_bug.cgi?id=1888524)
If the overlay doesn’t exist, the code shouldn’t be processed.
=> Bug 1888524 - javascript error when creating and viewing some bugs: can't access property "querySelector", $overlay is null

extensions/Needinfo/template/en/default/bug/needinfo.html.tmpl, js/field.js
[Bug 1157227 - redesign the "attachment details" page](https://bugzilla.mozilla.org/show_bug.cgi?id=1157227)
The `needinfo` class name was somehow missing in the template. Also, change the position of the user autocomplete dropdown to make sure it doesn’t go outside of the overlay.
=> Bug 1888481 - checkbox for NI is no longer automatically checked when picking myself or any other choice

extensions/BugModal/web/attachments_overlay.js
[Bug 1888550 - Ctrl+click on attachments no longer opens in new tab, with new attachment UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1888550)
Implement a simple solution for handling Ctrl+click. Instead of opening the legacy attachment page, open the bug page and show the overlay with the attachment loaded. This way, the UX will be the same as when the overlay is displayed normally in the same tab.
=> Bug 1888550 - Ctrl+click on attachments no longer opens in new tab, with new attachment UI

skins/standard/global.css, template/en/default/account/auth/login-small.html.tmpl
[Bug 1888761 - Mobile view of a bug: Login fields not fully visible](https://bugzilla.mozilla.org/show_bug.cgi?id=1888761)
- Make the mini login dropdown responsive. 
- Fix the style of the GitHub and OAuth2 login buttons.
- Also, make the Request dropdown narrower.
=> Bug 1888761 - Mobile view of a bug: Login fields not fully visible

Bugzilla/MFA/Duo.pm, template/en/default/account/prefs/mfa.html.tmpl
* Do not display the Duo Security option for MFA choices unless the user is 1) required to use Duo (config param) or 2) the user is a Mozilla employee (member of mozilla-employee-confidential group).
* Also block in enroll() in vase they try to bypass.
=> Bug 1886504 - Hide Duo as an option unless the current user is an employee

extensions/BMO/lib/Reports/Attention.pm
This pull request uses caches to make sure that a bug is only displayed once per page load of the attention report. The local cache is for removing duplicates for a single section and the global cache is for all sections of the page. The way the cache works is the duplicates will be removed for the lower sections which are the least important and display them in the upper more critical sections.
=> Bug 1887858 - What needs my attention: remove duplicate needinfos

extensions/BMO/web/js/edituser_menu.js
Since the values are now considered strings instead of boolean values from vcard.dataset, we use strict value checking to see if the value is "0' or "1".
=> Bug 1888810 - Hide editing option of user profiles for users without corresponding authorization

Bugzilla/Bug.pm, extensions/BugModal/template/en/default/bug_modal/create.html.tmpl
When a user who does not have canconfirm, normally they see the guided bug entry form by default. The guided form has a drop down for selecting product version. If they click the link at the bottom to switch over to the standard bug form, they are unable to select a version as it is hidden.
This PR changes the standard bug form to no longer consider the version drop down to be an *advanced* field and also make it required. Users without canconfirm cannot show advanced field so they always see a very simple version of the standard bug entry form.
=> Bug 1884724 - Standard bug entry form  for non-canconfirm users is missing fields that are available from the guided form

report.cgi, template/en/default/reports/report-table.html.tmpl
The previous removal of YUI javascript datatables broke rendering of values for tabular reports. This change fixes that.
=> Bug 1893924 - Tabular reports return blank tables

Bugzilla/App.pm, Bugzilla/App/Controller/API.pm, Bugzilla/App/Controller/BMO/AntiSpam.pm, Bugzilla/App/Controller/BMO/NewRelease.pm, Bugzilla/App/Controller/BouncedEmails.pm, Bugzilla/App/Controller/CGI.pm, Bugzilla/App/Controller/MFA/Duo.pm, Bugzilla/App/Controller/Main.pm, Bugzilla/App/Controller/OAuth2/Provider/Clients.pm, Bugzilla/App/Controller/SES.pm, Bugzilla/App/Plugin/Glue.pm, Bugzilla/CGI.pm, Bugzilla/Error.pm, Bugzilla/Template.pm, extensions/BzAPI/Extension.pm
Currently in Bugzilla/App.pm whenever a new Mojo controller module is added to add new functionality, we have to include the loading of the specific module and call its setup_routes() function. This bug is to create a new Bugzilla/App/Controller directory that we can place new controller modules and they will be loaded automatically instead of being hard coded. The change will create the code to auto load the modules as well as move the existing modules to the new location.
=> Bug 1895526 - Create Bugzilla/App/Controller directory where modules are auto loaded instead of being hard coded in the App.pm module

Bugzilla/Reminder.pm
Use of memcache needs to be disable for Bugzilla::Reminder as it is not appropriate use of the cache for that type of code. It is causing intermittent errors such as columns are not found during match, etc. I have tested disabling of memcache for the reminders table on bugilla-dev and the issue is no longer occurring.
=> Bug 1901825 - Use of memcache causing intermittent errors in Bugzilla Reminders feature

extensions/BugModal/web/bug_modal.js
- Replaces spaces with + in the needinfo string
- Use window.location.assign instead of replace so that back button works properly
=> Bug 1901945 - Can't go back to bug number page in the browser history after clicking on the Add reminder button

Bugzilla/Bug.pm
Need to filter out the reminder in is_reminded if sent = 1
=> Bug 1903627 - "Remove reminder" button is still shown despite no reminders remaining on bug

Bugzilla/API/V1/BugGraph.pm, Bugzilla/Report/Graph.pm
- Use breadth first instread of depth first for generating the JSON tree for /rest/bug/123/graph
- https://metacpan.org/pod/Graph::Traversal::BFS
- Move the code that filters secure bugs and resolved bug to Bugzilla/Report/Graph.pm
- This will allow later for showdependencytree.cgi and showdependencygraph.cgi to switch over to using Bugzilla/Report/Graph instead of each generating the trees themselves. This will remove duplication.
- Will file separate bugs for the work in above
=> Bug 1904151 - Updates and improvements to Bugzilla/Report/Graph.pm and Bugzilla/API/V1/BugGraph.pm

extensions/PhabBugz/lib/Util.pm
In `set_attachment_approval_flags` we check for several conditions
that indicate the flag cannot be updated by the user, but we do not
immediately `return` when these conditions are hit. This causes the
code to attempt to create the flag once it exits the loop, which
is not allowed since approval flags are not multiplicable. Add `return`
statements to branches which indicate the flag should not be updated.
Since we are now returning early from these branches, we can reverse the
logic of the main `if` branch to clean up the loop by de-denting the code.
=> Bug 1904753: return immediately when approval flag should not be changed

template/en/default/account/prefs/permissions.html.tmpl, userprefs.cgi
This change revamps the permissions page in user preferences. It uses the css for other reports so it is consistent. Also it now shows which groups someones permission is inherited from.
I also put this change on bugzilla-dev if you want to see it in action:
https://bugzilla-dev.allizom.org/userprefs.cgi?tab=permissions
=> Bug 1200286 - The permissions section in user preferences should distinguish between assigned and inherited groups

template/en/default/email/ses-complaint.txt.tmpl
In the templates [% urlbase %] always contains a / at the end (ex: https://bugzilla.mozilla.org/) so adding another / is not needed and causes //. This patch  removes the extra / from the link in the complain email sent to admins.
=> Bug 1907893 - Malformed URL in SES complaint emails sent to bugzilla maintainers

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
This patch skip the rendering of comments that have spam tag to users without editbugs permissions.
=> Bug 1905292 - Hide spam content to discourage spammers

template/en/default/global/header.html.tmpl
=> Bug 1907906 - Show indicator in Bugzilla header that a users email is currently disabled

Bugzilla/Auth/Login/CGI.pm, Bugzilla/CGI.pm, token.cgi
Quite a few automated tests and a few places in the code were relying on the referer header change that was put in place long ago. I have fixed up the tests and places where it will instead (properly) rely on cookies instead of referer to validate a request is legitimate.
=> Bug 1908265 - cannot log in unless HTTP Referer request header is enabled

showdependencygraph.cgi
I added quotes around the bug id and summaries which should with future special characters that Mermaid treats as special.
=> Bug 1909798 - Large dependency graphs do not work

template/en/default/account/auth/verify_account_creation.html.tmpl, token.cgi
This change adds an input field to the github (and other oauth2) login flow that allows a user to set a Real Name when the new account is created.
=> Bug 1909777 - Require new users to set their username during the GitHub account creation flow

extensions/AntiSpam/Extension.pm, extensions/ComponentWatching/Extension.pm, extensions/SecureMail/Extension.pm, scripts/sanitizeme.pl
This pull request removes additional user specific data from the DB when doing a sanitized dump.
Tables cleared:
component_watch
anstispam_*
reminders
whine_*
watch
series_*
email_rates
email_bug_ignore
secbugs_*
Also the following:
Clears MFA values from the profiles table
Clears user public gpg keys from the profiles table
=> Bug 1910693 - Update sanitizeme script to remove more sensitive user data from dump file

extensions/AntiSpam/Extension.pm, extensions/AntiSpam/bin/spam_cleanup.pl
- Create a antispam_comment_cleanup table for recording comment ids
- Hook into comment tag hooks to add comment ids to the table when spam is added and remove if tag removed
- Create a cron script to run every 30 mins to process the comment ids in the cleanup queue.
- Currently the script will just remove a needinfo that was added at the same time as a spam comment
- We can add other cleanup changes to the script in future pull requests.
=> Bug 1905296 - Clear needinfo if comment is marked as spam

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl, extensions/BugModal/template/en/default/bug_modal/attachments.html.tmpl, extensions/BugModal/web/attachments_overlay.js
- aligns behaviour with opening via the context menu
- the details link can be meta-clicked for the current behaviour
=> Bug 1891378 - meta-clicking on attachment name should open the attachment, not the details page

Bugzilla/Comment.pm
[Bug 1916637 - Fix order of names for emoji comment reactions](https://bugzilla.mozilla.org/show_bug.cgi?id=1916637)
The `longdescs_reactions` table doesn’t store the date/time for each reaction, but since the `id` column is auto-incrementing, it can be used to sort the reactions by date instead of user id.
This change may make the API response slightly slower because the `id` column is not included in the index, but it shouldn’t be critical since user names are fetched only when an emoji is hovered.
=> Bug 1916637 - Fix order of names for emoji comment reactions

extensions/GuidedBugEntry/template/en/default/guided/guided.html.tmpl, extensions/GuidedBugEntry/web/style/guided.css
Convert the html/css that is used in the Guided form for the preliminary questions to use the same as the home page of BMO. This allows for consistency and reuse instead if duplication.
=> Bug 1916586 - Color of the icon for Report an issue with a website that I use

extensions/BugModal/web/bug_modal.css
[Bug 1917008 - Emoji Reaction Button Off-Centered](https://bugzilla.mozilla.org/show_bug.cgi?id=1917008)
Remove unnecessary line from CSS to fix the vertical alignment of the emoji.
=> Bug 1917008 - Emoji Reaction Button Off-Centered

extensions/BugModal/Extension.pm, extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl, extensions/BugModal/template/en/default/hook/global/setting-descs-settings.none.tmpl
[Bug 1916765 - add preference to not display emoji](https://bugzilla.mozilla.org/show_bug.cgi?id=1916765)
Add a new user preference to the User Interface section that allows users to hide emoji comment reactions if they want.
=> Bug 1916765 - add preference to not display emoji

extensions/BugModal/template/en/default/bug_modal/comment_reactions.html.tmpl, extensions/BugModal/web/bug_modal.css, extensions/EditComments/web/styles/inline-editor.css
[Bug 1916787 - Extra empty space in each bugzilla comment when there are no emoji reactions to it](https://bugzilla.mozilla.org/show_bug.cgi?id=1916787)
Hide the reactions wrapper element if the user is signed out and there are no reactions logged on the comment, so there would be no CSS padding on it.
Sidealongs (I’ve actually added those changes to #2307 but it’s better to have them here instead):
- Add an extra space after a private comment with a red border
- Hide the reactions when the inline comment editor is open
=> Bug 1916787 - Extra empty space in each bugzilla comment when there are no emoji reactions to it

Bugzilla/Bug.pm, Bugzilla/WebService/Bug.pm, Bugzilla/WebService/Constants.pm, extensions/BugModal/template/en/default/bug_modal/comment_reactions.html.tmpl, extensions/BugModal/web/comments.js, template/en/default/global/user-error.html.tmpl
[Bug 1916929 - Prevent emoji reactions on old, closed bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1916929)
Compare `cf_last_resolved` and the current timestamp to see if comment reactions are accepted. If not, hide the emoji picker button and raise an error in case the API is used.
Not sure if we could test this time lapse thing but you can test it by changing `months => 3` to `minutes => 1` 😅
=> Bug 1916929 - Prevent emoji reactions on old, closed bugs

Bugzilla/WebService/Bug.pm, Bugzilla/WebService/Constants.pm, extensions/BugModal/template/en/default/bug_modal/comment_reactions.html.tmpl, extensions/RestrictComments/template/en/default/admin/params/restrictcomments.html.tmpl, extensions/RestrictComments/template/en/default/hook/bug/edit-after_comment_commit_button.html.tmpl, extensions/RestrictComments/template/en/default/pages/restrict_comments_guidelines.html.tmpl, qa/t/1_test_bug_edit.t, qa/t/rest_bug.t, template/en/default/global/user-error.html.tmpl
[Bug 1917167 - Disable emoji reactions for users without editbugs on bugs that have commenting restricted](https://bugzilla.mozilla.org/show_bug.cgi?id=1917167)
Restrict emoji reactions as with bug comments. The reaction button will be hidden from non-editbugs users, and the API usage will also fail.
=> Bug 1917167 - Disable emoji reactions for users without editbugs on bugs that have commenting restricted

extensions/SiteMapIndex/template/en/default/hook/robots-end.txt.tmpl
After waiting a while for Google to finally get around to indexing bugzilla-dev.allizom.org to test this fix, it seems like this is now working. Please review.
=> Bug 1917348 - Update robots.txt hook for SiteMapIndex to add 'Allow: /sitemap/' to fix blocked sitemap issue

extensions/BugModal/template/en/default/bug_modal/comment_reactions.html.tmpl
[Bug 1919237 - Extra empty space in each bugzilla comment when there are no emoji reactions to it and logged in on old bugs that disallow reactions](https://bugzilla.mozilla.org/show_bug.cgi?id=1919237)
Fix the `IF` condition for showing the emoji wrapper element.
=> Bug 1919237 - Extra empty space in each bugzilla comment when there are no emoji reactions to it and logged in on old bugs that disallow reactions

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
[Bug 1919687 - Collapse/Expand buttons have inconsistent style](https://bugzilla.mozilla.org/show_bug.cgi?id=1919687)
Fix the CSS class name to make them ghost 👻
=> Bug 1919687 - Collapse/Expand buttons have inconsistent style

extensions/BugModal/web/bug_modal.css, extensions/BugModal/web/comments.js
[Bug 1919692 - Avatars on collapsed comments are tiny](https://bugzilla.mozilla.org/show_bug.cgi?id=1919692)
Stop changing the avatar size on collapsed change sets. Also, make sure the username is vertically aligned next to an avatar.
=> Bug 1919692 - Avatars on collapsed comments are tiny

extensions/BugModal/template/en/default/bug_modal/new_comment.html.tmpl
[Bug 1919789 - `comment` parameter to prefill bug from URLs is ignored](https://bugzilla.mozilla.org/show_bug.cgi?id=1919789)
Restore the default `comment` removed by mistake in #2307. 😓
=> Bug 1919789 - `comment` parameter to prefill bug from URLs is ignored

extensions/BugModal/template/en/default/bug_modal/create.html.tmpl, extensions/BugModal/web/bug_modal.css, extensions/BugModal/web/create.js
[Bug 1919849 - Some features on modal new bug page are not working as expected](https://bugzilla.mozilla.org/show_bug.cgi?id=1919849)
jQuery in [`bug_modal.js`](https://github.com/mozilla-bteam/bmo/blob/master/extensions/BugModal/web/bug_modal.js) has some `$('#comment', '#changeform')`, meaning the `<form>` has to have `id="changeform"` to match the comment `<textarea>`. 
The modal bug details page has `id="changeform"` for sure, but somehow the modal new bug page  has `id="create-form"`, which breaks the following features. This PR makes the ID consistent so that the shared script will work.
- Add Description button
- Comment draft auto saving in local storage
- Comment `<textarea>` auto resize
- Make comment private checkbox that makes the comment text red
=> Bug 1919849 - Some features on modal new bug page are not working as expected

Bugzilla/Search.pm, qa/t/1_test_bug_edit.t, template/en/default/search/form.html.tmpl
This backports some old fixes from upstream that allows for use of pronouns (%self%, %user%, etc.) for the cc and commenter fields of email searches.
=> Bug 1918771 - Support pronouns such as %user% in "changed by" searches

js/util.js
[Bug 1921383 - Bugzilla rich text editor shortcuts don't respect user layout](https://bugzilla.mozilla.org/show_bug.cgi?id=1921383)
Fix the keyboard event handler to support different keyboard layouts. Tested with [Dvorak](https://en.wikipedia.org/wiki/Dvorak_keyboard_layout), [Colemak](https://en.wikipedia.org/wiki/Colemak) and QWERTY.
Actually this code originated from my Sveltia UI library. I made the change in https://github.com/sveltia/sveltia-ui/commit/9dc5d25d0f7e7a8cb95306642b1839ad9c34ee76 but don’t remember why...
=> Bug 1921383 - Bugzilla rich text editor shortcuts don't respect user layout

extensions/BugModal/web/attachments_overlay.js
[Bug 1921668 - Inline attachment details button no longer works if attachment is on another bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1921668)
Disable the attachment overlay for attachments on another bug because it’s doesn’t work well as [explained in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1921668#c3).
=> Bug 1921668 - Inline attachment details button no longer works if attachment is on another bug

extensions/BMO/template/en/default/hook/flag/type_comment-form.html.tmpl
Bug 1921295 - Update wording on uplift request form to include urgency for beta and release
Leaving ESR, geckoview, and security approval forms as is.
=> Bug 1921295 - Update wording on uplift request form to include urgency for beta and release

js/text-editor.js, js/util.js
[Bug 1921383 - Bugzilla rich text editor shortcuts don't respect user layout](https://bugzilla.mozilla.org/show_bug.cgi?id=1921383)
Sorry, #2331 was incomplete and broke shortcuts with non-alphanumeric keys like Space and Enter. Now I remember why I said “keyboard shortcuts not working sometimes” in my Sveltia UI change 😓 This does the right thing.
=> Bug 1921383 - Bugzilla rich text editor shortcuts don't respect user layout (revised)

js/text-editor.js
[Bug 1921966 - List ending by double enter wipes rest of comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1921966)
#2336 has to be merged first because the Enter key handler is broken 😶
=> Bug 1921966 - List ending by double enter wipes rest of comment

Dockerfile, README.rst, docker-compose.test.yml, docker-compose.yml
- Add size_limit setting with higher than default to allow proper functionality on OSX and Docker
- Updated dockerfile to remove warnings 
- Update targets in docker-compose*.yml to only install Firefox and lsof when tests are being ran
=> Bug 1923415 - Update Dockerfile and docker-compose*.yml to optimize build times and remove warnings

extensions/BugModal/template/en/default/bug_modal/user.html.tmpl, extensions/EditComments/web/js/inline-comment-editor.js
If multiple people edit the first comment (description) then editing it again will fail due to JS error. This fixes the issue for that use case.
=> Bug 1923931 - Editing a comment breaks when two different people have previously edited the same comment

Bugzilla/Search.pm
When selecting a search include Mentors, it is using a non-existent function _commenter_pronoun and needs to instead use _contact_pronoun. This was missed in an earlier commit back porting pronoun support to more places.
=> Bug 1923840 - Searching for bugs containing a mentor times out (504 Gateway timeout)

Bugzilla/DB/Schema.pm, Bugzilla/Install/DB.pm, Bugzilla/User.pm
The PR #2345  will need to have the schema change deployed first then the rest of the code later.
=> Bug 1926081 - Add modification_time datetime column to profiles table denoting when the profile was last updated (schema only)

extensions/BugModal/lib/WebService.pm
This change updates the webservice API that BugModal (show_bug.cgi) page uses to fetch a list of components when a user changes the product. If the new product selected only contains one component (i.e. Invalid Bugs) then it pre-selects the single component. If it has more than one, then it does the old behavior of adding a block component value and requires the user to select the proper component before submitting.
=> Bug 1926574 - When changing product of a bug and the destination product only has one component, pre-select the one component

skins/standard/global.css
[Bug 1928077 - Bugzilla comment/description font bigger on desktop](https://bugzilla.mozilla.org/show_bug.cgi?id=1928077)
Changing the base font sizes affects many places... Restore the variables to the original.
=> Bug 1928077 - Bugzilla comment/description font bigger on desktop

extensions/BugModal/web/bug_modal.css, extensions/BugModal/web/comments.js
[Bug 1928083 - Bugzilla’s emojis are displayed on the bottom of the page when activated creating a new scroll bar](https://bugzilla.mozilla.org/show_bug.cgi?id=1928083)
The cause is due to a change in page layout (fixed global header) in #2334, but reverting the change would rather introduce other problems (I don’t remember exactly, but I saw several problems while working on mobile optimization).
The solution to detect the CSS Anchor Positioning API, which is not yet implemented in Firefox and Safari, and fall back to the legacy implementation if the API is not available.
This also fixes the anchor positioning itself. My initial implementation hardcoded `anchor-name` in CSS, but it doesn’t work well because there are usually multiple comments in a bug, and `anchor-name` needs to be …
=> Bug 1928083 - Bugzilla’s emojis are displayed on the bottom of the page when activated creating a new scroll bar

extensions/BugModal/web/bug_modal.js
This simple fix just checks to make sure that the comment textarea is empty before pre-filling the stored comment text in localStorage.
=> Bug 1929001 - Saved data for comment 0 overrides "comment" parameter

skins/standard/global.css
[Bug 1929501 - Double scroll-bar in search bugs list, preventing easy scrolling](https://bugzilla.mozilla.org/show_bug.cgi?id=1929501)
Optimize the scrollable area in the quick search dropdown. Now the Saved Search header and the Help footer are fixed at the top and bottom of the dropdown, as only the saved search list is scrollable.
=> Bug 1929501 - Double scroll-bar in search bugs list, preventing easy scrolling

extensions/BMO/template/en/default/bug/create/bugzilla-admin.html.tmpl
=> Bug 1931232 - Add BMO vs Bugzilla warning block at top of new bug page for Bugzilla product

.circleci/config.yml, .github/workflows/ci.yml, .github/workflows/deploy.yml, Bugzilla.pm, Bugzilla/Config.pm, Bugzilla/DB/Schema/Mysql.pm, docker-compose.test.yml, extensions/BMO/Extension.pm, extensions/Voting/Extension.pm, extensions/Voting/template/en/default/hook/admin/products/updated-changes.html.tmpl, scripts/build-bmo-push-data.pl, scripts/entrypoint.pl, t/hash-sig.t, t/mojo-example.t, template/en/default/bug/process/bugmail.html.tmpl
Rather than junk up the other pull request for the ETL work with these minor fixes, I am making them here instead. These are changes to the way images are built in CircleCI for running the automated tests as well as some code cleanup to remove unused code and get rid of some warnings in the test output that looks bad.
In order to build the bigquery-emulator container for testing in the ETL pull request, we need to build the images from the docker-compose.test.yml file instead of doing docker builds outside of docker-compose. Instead of `docker build -t bmo . ; docker-compose run bmo.test test_webservices`, I do `docker run --build bmo.test test_webservices`.
For github, I still need to do the `docker-compose build` before the test run since for some reason their implementation did not …
=> Bug 1932257 - CircleCI configuration cleanups and removal of un-used code in entrypoint.pl

Bugzilla/App/Controller/BouncedEmails.pm
This change adds some missing necessary code to the BounceEmails.pm controller that to handle logins properly. With this change, the in_group error will go away as the user will need to login properly first.
=> Bug 1931772 - Can't call method "in_group" on an undefined value at Bugzilla/App/Controller/BouncedEmails.pm line 27.

skins/standard/login.css, template/en/default/mfa/totp/verify.html.tmpl
I haven’t filed a bug, but I believe this is a fallout from #2334. When you sign in, you’ll probably enter a 6-digit verification code on the Account Verification page. Currently, the Submit button is displayed in full width, which is not an intended layout. This PR fixes it.
(The UI could be [better than this](https://www.google.com/search?q=otp+input&udm=2), but it’s out of scope 😉)
=> Bug 1933585 - Fix TOTP form layout on Account Verification page

.circleci/config.yml, docker-compose.test.yml
before these changes, the `/app/version.json` file had empty values for CIRCLE_SHA1 and CIRCLE_BUILD_URI. This fixes the issue.
=> Bug 1936911 - Add back CIRCLECI_SHA1 AND CIRCLE_BUILD_URL back to the build and deploy steps for CircleCI

extensions/BMO/template/en/default/bug/create/bugzilla-admin.html.tmpl
=> Bug 1937614 - Typo "reature" in the warning for Bugzilla vs. bugzilla.mozilla.org

Bugzilla/Search.pm
To help pin-pointing where some long running MySQL queries are coming from, we can add comment strings to the SQL statements that will show up in the long running query logs. The extra information will be helpful in finding out where/who they are coming from and we can work with them to find more efficient ways of getting the data they need like bespoke API calls using the Search API support we have.
=> Bug 1934616 - Add comment to SQL that is generated by buglist.cgi to add userid, query string, and user agent

extensions/BugModal/web/bug_modal.css, skins/standard/global.css, skins/standard/text-editor.css
Disable font ligatures where URLs are provided or displayed.
=> Bug 1706715 - disable font ligatures to avoid mangling URLs

template/en/default/robots.txt.tmpl
Unfortunately in my earlier changes for the robots.txt I was looking at the incorrect variable name for determining if running on production. `urlbase` is the proper variable to look at when comparing.
=> Bug 1941468 - Sitemap robots.txt template is looking at the wrong variable to determine if running on production bugzilla.mozilla.org

scripts/remove-non-public-data.pl
- Added $dbh->quote_identifier() for tables which have names that are reserved words in MySQL
- Fixed code that was referencing column name that was not case-insensitive.
- Added reaction to whitelisted columns for longdescs_reactions as it was being referenced by other indexes and cannot be dropped.
=> Bug 1941913 - Bug fixes for scripts/remove-non-public-data.pl that prepares a sanitized DB snapshot for researchers

.circleci/config.yml, .github/workflows/ci.yml, conf/checksetup_answers.txt, docker-compose.test.yml, docker-compose.yml, docker/bigquery/Dockerfile, docker/bigquery/data.yaml, extensions/BMO/Extension.pm, extensions/BMO/bin/export_bmo_etl.pl, extensions/BMO/t/bmo/bmo_etl.t, extensions/BMO/template/en/default/hook/admin/params/editparams-current_panel.html.tmpl
Sorry this so late. Lots of moving pieces had to be coordinated with webservices-infra, etc. just so I could test and then small changes one after another to get to this point. 
- Added config options for BMO ETL settings such as base url, project id, dataset id, etc.
- A export script that will run nightly at 11pm and export daily snapshot of specific bug data to BigQuery
- A test BQ emulator and test script that can be used to do basic testing of exporting bug data to the emulator locally. There is a data.yml file that creates the same schema as what will be in production before exporting.
- Small change to circleci and github ci to run the tests in the extensions directory.
Let me know if you have any questions as it is a lot.
=> Bug 1922986 - Create script that exports BMO data as JSON suitable for import into a BigQuery instance in GCP

Bugzilla/API/V1/Github.pm, qa/t/rest_github_push_comment.t
Before deployment, I will get with the Fenix and Focus people to add the ?no-qe-verify=1 to their webhooks.
=> Bug 1930197 - Add an option (or config) to not set the qe-verify+ flag when a GitHub push closes a bug in a given product

extensions/BMO/bin/export_bmo_etl.pl
The new BMO ETL export script has a bug in that it does not properly increment the $count variable when encountering bugs that are to be skipped in the export. These include Legal bugs, etc. Then the while() loop runs forever as $count is always less than $total.
Bad code:
```perl
if (any { $obj->product eq $_ } EXCLUDE_PRODUCTS) {
$excluded_bugs{$obj->id} = 1;
next;
}
```
This should be instead:
```perl
if (any { $obj->product eq $_ } EXCLUDE_PRODUCTS) {
$excluded_bugs{$obj->id} = 1;
$count++;
next;
}
```
I didn't not catch this unfortunately til we tried it in production as bugzilla-dev does not have any bugs to be excluded so the count was always correct. 
Any other functions where we skip excluded bugs will also need to be update to increment $count so I will fix those as well.
=> Bug 1946805 - Count is not being incremented properly when excluding bugs from the full list and therefore the export script is hanging

extensions/BugModal/web/bug_modal.js
With the changes to suppose cookie banner, the old code was looking for the string 'true' instead of a proper true/false boolean.
=> Bug 1941032 - "Always Enable Edit Mode" is broken

extensions/BMO/bin/export_bmo_etl.pl
Currently the export script looks for a modification_ts value to exist in the profiles table when caching the profile in the bmo_etl_cache table. But due to the migration script, implemented by [bug 1926081](https://bugzilla.mozilla.org/show_bug.cgi?id=1926081), failing to complete for various reasons, some values are still NULL in the profiles table.
I am working on getting the migration to complete now and it is very slow going. In the meantime I want to update the export script to use an arbitrary timestamp, say 1970-01-01 12:00:00 for example, in place of the NULL timestamp which will allow the script to work fully and also to cache the profile in a useful way until the real timestamp is filled in by the migration script.
=> Bug 1947216 - BMO ETL: Update export script to add arbitrary timestamp for profiles modification_ts if one is not yet set for the actual profile

template/en/default/global/footer.html.tmpl
New wording has been approved for now by nneka https://bugzilla.mozilla.org/show_bug.cgi?id=1951989#c8
=> Bug 1951989 - Update cookie banner wording to be more explicit that non-essential cookies are NOT used for tracking and/or analytics in Bugzilla

extensions/BMO/bin/export_bmo_etl.pl
Add parameters to the export script that allows for disabling caching of specific tables in case issues are found with regard to specific data causing the export script to fail consistently.
=> Bug 1951739 - BMO ETL: Add parameters to export script to turn off cache for one or more tables

.github/workflows/deploy.yml
This will ensure Docker images are build and pushed to GAR when the `development` branch is updated.
=> Bug 1954571 - Add development branch to CI build triggers

Bugzilla/Search.pm
Adding back as I understand now what manual operations need to be done to allow the change to now happen.
=> Bug 1954833 - Change product name from "Fenix" to "Firefox for Android"

extensions/BMO/bin/export_bmo_etl.pl, extensions/BMO/t/bmo/bmo_etl.t
- Removes --verbose and prints standard output when no arguments
- Adds --debug to print even more verbose output than normal.
- New logger function to handle the printing of all output.
=> Bug 1954310 - BMO ETL: Add more verbose debugging output to what is already logged

relogin.cgi
You get an error every time that a password was not provided after performing the MFA check. This fixes the sudo code in relogin.cgi to honor the mfa_verification_token cookie and not check for password twice allowing sudo to work correctly.
=> Bug 1956154 - When impersonating another user (sudo) from admin, it fails when using MFA due to not honoring the mfa_verification_token cookie

Dockerfile, Makefile.PL, cpanfile, cpanfile.snapshot
Sub::Identify needs to be explicitly required now that a previous dependency stopped needing it and we no longer get it automatically.
=> Bug 1956957 - Update docker base image to bmo-perl-slim:20250328

Bugzilla/Mailer.pm
Set the encode_check_set() value to 0 which changes from the default behavior of throwing an exception to replaces the malformed characters with a special harmless replacement character. This allows the email with the unknown unicode characters to still be delivered.
=> Bug 1959325 - Malformed characters in email bodys can cause email delivery to fail and backup in the jobqueue

extensions/OrangeFactor/template/en/default/hook/bug/edit-after_custom_fields.html.tmpl, extensions/OrangeFactor/template/en/default/hook/bug_modal/edit-details_rhs.html.tmpl, extensions/OrangeFactor/web/js/orange_factor.js
The graph was already using the failure occurrences from all trees.
=> Bug 1960350 - [orangefactor] link to view with all intermittent failure occurrences

extensions/BugModal/template/en/default/bug/create/create-modal.html.tmpl, extensions/BugModal/template/en/default/bug_modal/header.html.tmpl
The util.js is loaded for every page already, and the BugModal code (enter bug, show bug) was also loading util.js which caused the redeclaration error so I fixed to only load util.js once.
=> Bug 1947837 - Uncaught SyntaxError: redeclaration of const formatDate

extensions/BMO/bin/export_bmo_etl.pl
When I started loading Bugzilla::Logging in the previous commit, the DEBUG method from that module conflicted with the DEBUG constant in the export script. So I renamed the constant DEBUG to DEBUG_OUTPUT.
=> Bug 1960366 - BMO ETL: Prototype mismatch errors introduced in recent change to add more debugging information

attachment.cgi, extensions/BugModal/template/en/default/bug_modal/attachments_overlay.html.tmpl, extensions/BugModal/template/en/default/bug_modal/new_comment.html.tmpl, template/en/default/attachment/create.html.tmpl
This change adds the Add me to CC option for attachments similar to the bug page. It also will use the preferences of the user to determine if it is automatically checked or not.
=> Bug 1959361 - Adding attachments doesn't add you to the bug's CC list

extensions/PhabBugz/lib/Util.pm
Create a mapping table of new repo short names to old so that approval flags continue to work.
=> Bug 1963838 - Bugzilla flag setting for uplift approval requests and release branch pushes no longer works

Bugzilla/DB/Mysql.pm, Bugzilla/Search.pm, Bugzilla/WebService/Bug.pm, Bugzilla/WebService/Constants.pm, buglist.cgi, template/en/default/global/user-error.html.tmpl
- Removed the MySQL setting ONLY_FULL_GROUP_BY due to some BMO code still not listing full group by column list. MySQL changed to checking by default in recent versions and this change now crashes certain queries that worked before.
- Created a single _sql_execute() function in Search.pm that can be used in multiple places to check for time out error instead of doing in both buglist.cgi and REST API.
=> Bug 1967336 - The error message generated by timeout of long running searches needs to also work with REST API in addition to the web UI

Bugzilla/Bug.pm
~~This change simply checks first to see if the destination bug as a reverse see_also back to the source bug. This is instead of before of just assuming that a reverse relationship exists which can cause error if it doesn't.~~
Turns out a shorter fix was all that was necessary after some more testing. My reordering of the conditions in the if block was all that was needed. Before the code was accessing `$removed_bug_url->ref_bug_url->bug_id` before checking if `$removed_bug_url->ref_bug_url` even existed which was causing a fatal error loop. By reordering, it not just short circuits before the line causing the error.
=> Bug 1974359 - Cannot remove see-also from bug when user can edit the other bug and the other bug doe not have a see-also back

t/docker.t
Updating the docker.t test to remove the part that looks for the CircleCI config.
=> Bug 1978644 - With the removal of circleci config in bug 1977941, the t/docker.t test is failing as it looks for those files

extensions/PhabBugz/lib/Comment.pm, extensions/PhabBugz/lib/Revision.pm, extensions/PhabBugz/lib/Util.pm
Add a comment to the revision stating that an individual reviewer could not be found from a rotation pool. Also allow a way to get current comments for a revision that can be queried up on the next time the revision is changed so that we only add the comment once. We do not want to keep looping and re-adding the comment.
=> Bug 1980977 - When looking for a reviewer from rotation group and run out of choices, add a comment to the revision stating a reviewer was not found

extensions/GuidedBugEntry/template/en/default/guided/guided.html.tmpl, extensions/GuidedBugEntry/web/style/guided.css
=> Bug 1982101 - Add a note that markdown is supported with a link to help on the Guided bug entry page

skins/standard/buglist.css, skins/standard/global.css
[Bug 1933892 - missing/misplaced horizontal scrollbar on bug lists](https://bugzilla.mozilla.org/show_bug.cgi?id=1933892)
This change ensures that the horizontal scrollbar is always displayed when the page overflows due to a large bug table while keeping the header fixed at the top and centre of the page. It also adjusts the bug table’s style for mobile so that a large number of bugs (blockers, etc.) do not overflow the table.
=> Bug 1933892 - missing/misplaced horizontal scrollbar on bug lists

skins/standard/dependency-tree.css
[Bug 1971059 - Dependency tree items are misaligned](https://bugzilla.mozilla.org/show_bug.cgi?id=1971059)
Fix an unexpected style override.
=> Bug 1971059 - Dependency tree items are misaligned

extensions/MyDashboard/lib/WebService.pm, extensions/MyDashboard/web/js/query.js
[Bug 1983944 - My dashboard should render updated comments in markdown](https://bugzilla.mozilla.org/show_bug.cgi?id=1983944)
Return rendered HTML with the API, and use it as-is.
=> Bug 1983944 - My dashboard should render updated comments in markdown

extensions/PhabBugz/lib/Feed.pm
After reviewing [bug 1985621](https://bugzilla.mozilla.org/show_bug.cgi?id=1985621), I discovered a few places which can cause a object corruption issue due to updating a bug multiple times instead a single time. This patch fixes this issue.
=> Bug 1986495 - Optimize bug updates in Phabbugz by converting to a single update

skins/standard/global.css
for https://bugzilla.mozilla.org/show_bug.cgi?id=1987016
This does:
* apply dedicate styling for disabled checkboxes
(we may need to do the same for other controls, but I'd leave it for other bugs, as I haven't bumped into other disabled controls)
=> Bug 1987016 - Apply better styling for disabled checkboxes.

extensions/UserProfile/template/en/default/pages/user_profile.html.tmpl
For https://bugzilla.mozilla.org/show_bug.cgi?id=1988707
This does:
* Add "(Updated daily)" after the "User Statistics" section name, to clarify the delay
=> Bug 1988707 - Clarify the User Statistics is updated daily.

extensions/BMO/Extension.pm, extensions/BMO/template/en/default/pages/get_permissions.html.tmpl, extensions/BMO/template/en/default/pages/triage_request.html.tmpl
If the user is new (is_new() provided by the TagNewUser extension) then do not allow them to give themselves canconfirm permissions.
=> Bug 1989605 - Don't allow brand-new accounts to use the Triage Request Form to self-grant `canconfirm`

extensions/GuidedBugEntry/web/style/guided.css
This fixes: [Bug 1985464](https://bugzilla.mozilla.org/show_bug.cgi?id=1985464) by switching the card layout to flex. This way we can avoid having a fixed height on the cards, but retain the equal height/grid look of the cards. I also removed the min-height as it seems unnecessary with the new setup.
Previous:
Fixed:
=> Bug 1985464 - Switch guided bug entry cards to flex layout to avoid a fixed height
