mozilla-bteam/bmo

extensions/REMO/Extension.pm

[1308934](https://bugzilla.mozilla.org/show_bug.cgi?id=1308934)

Bug 1308934 - Change csv file attachment on Mozilla Reps Swag Request

---

Bugzilla/Memcached.pm

Creating pull request for discussion purposes. This is just the algorithm. The final version would probably need a utility function that throws a ratelimit UserError or something.

Bug 1299855 - Implement token-bucket rate limiting on top of memcached

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl

This changes the text for the Edit button and also adds a tooltip to explain what it does.

Bug 1330449 - Change Edit button text and add a tooltip

---

extensions/BugModal/web/bug_modal.css

Set #bugzilla-body to have em based widths so they scale with font size.

Bug 1343663 - Comments are too wide

---

scripts/resolve_bugs.pl

Repurpose an old script as a bug resolving implement.

Bug 1360619 - Move Firefox OS to graveyard

---

Vagrantfile

I faced this issue and accordingly @dylanwh opened a PR: #80.
My reasoning is that, it was because of network change in my case, as modifying the vm with natdns options worked for me.

Ensure internet connectivity in vagrant

---

README.rst

This fixes a number of typos, formatting errors, and awkward phrasings.

Fix and improve wording in README.rst.

---

extensions/BMO/template/en/default/bug/create/create-recruiting.html.tmpl
extensions/BMO/template/en/default/bug/create/vp-authority.html.tmpl

https://bugzila.mozilla.org/enter_bug.cgi?product=Recruiting

Bug 1372693 Update to Recruiting Bugzilla Custom Form 

---

Bugzilla/Elastic/Search.pm

Bug 1376850 - Add special case for substring searches on whiteboard status field

---

Bugzilla.pm
Bugzilla/Extension.pm
Bugzilla/Install/Requirements.pm
Bugzilla/Install/Util.pm
extensions/BMO/Extension.pm
mod_perl.pl

You don't need to verify that the code in bug 1352907 is good (because it was reviewed), merely that this un-reverts the damage inflicted in https://github.com/mozilla-bteam/bmo/commit/38b13ae3f1885faa0da1d0040a0dda87dc786515 :-)

Bug 1376023 - Undo accidental reversion of bug 1352907

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl

@dylanwh There are a lot of them where we would need this, if we can discuss over chat.

Bug 1379483 - Required fields in bug_modal

---

template/en/default/global/common-links.html.tmpl
template/en/default/global/header.html.tmpl

Revert "Bug 1380064 - Remove references to Mozilla skin to prevent problems w…"

---

extensions/PhabBugz/lib/Util.pm
extensions/PhabBugz/lib/WebService.pm
extensions/Push/lib/Connector/Phabricator.pm

Posting as a WIP for discussion.

Bug 1380727 - Implement security group features for Phabricator 

---

Bugzilla/Component.pm

No bug, as this is just a documentation change (that causes sanity test failures)

No Bug - fix pod syntax in Bugzilla/Component.pm

---

extensions/PhabBugz/lib/WebService.pm

- minor fix needed in extensions/PhabBugz/lib/WebService.pm

Bug 1380727 - Update BMO Push Connector to Make Revisions Public when Bug Made Public

---

scripts/resolve_bugs.pl

Allow resolve_bugs.pl to run from command line.

Bug 1381567 - wrap heredoc in an if

---

extensions/PhabBugz/lib/Util.pm
extensions/PhabBugz/lib/WebService.pm
extensions/Push/lib/Connector/Phabricator.pm

https://bugzilla.mozilla.org/show_bug.cgi?id=1383108

Bug 1383108 - Sync security groups with Phabricator push connector

---

extensions/Push/lib/Connector/Phabricator.pm

Fix #1386675 - Update user comparison in Phabricator push connector

---

extensions/PhabBugz/lib/Util.pm
extensions/PhabBugz/lib/WebService.pm
extensions/Push/lib/Connector/Phabricator.pm

Will open a bug in a moment.
Want to get dkl's opinion on this quick.

WIP: Bug 1399593 - Add sync group comments during new revision creation as well as push connector

---

Bugzilla/ModPerl/StartupFix.pm

Patch to address the documentation issue

no bug - document code and fix single-arg bless()

---

.circleci/checksetup_answers.txt
.circleci/config.yml
.perlcriticrc
Bugzilla/Install/Filesystem.pm
README.rst
auth.cgi
heartbeat.cgi
scripts/entrypoint.pl
scripts/generate_conduit_data.pl

These fixes allow bmo-extensions to directly use the normal bmo container.

Conduit fixes

---

vagrant_support/checksetup_answers.j2

Fix problem noted by @SebastinSanty in #289.

no bug - set docs_urlbase to production value in vagrant setup

---

extensions/BugModal/template/en/default/bug_modal/field.html.tmpl
extensions/BugModal/template/en/default/bug_modal/header.html.tmpl

Removing the datetimepicker plugin is left.

Bug 1424940 - Support HTML5 datepicker

---

new_bug.cgi

This PR discusses everything that needs to be done, in order to release new-bug interface to the public.

Bug 1425119 - Release new-bug interface

---

extensions/PhabBugz/Extension.pm
extensions/PhabBugz/bin/phabbugz_feed.pl
extensions/PhabBugz/bin/update_project_members.pl
extensions/PhabBugz/lib/Constants.pm
extensions/PhabBugz/lib/Daemon.pm
extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/Logger.pm
extensions/PhabBugz/lib/Project.pm
extensions/PhabBugz/lib/Revision.pm
extensions/PhabBugz/lib/Util.pm
extensions/PhabBugz/lib/WebService.pm
extensions/Push/lib/Connector/Phabricator.pm

This restores the previously reverted commit.

Bug 1409957 - Create polling daemon to query Phabricator for recent transcations and update bug data according to revision changes

---

Bugzilla/Config.pm

Some infra code looks for urlbase in data/params, so let's make sure it is there.

no bug - ensure urlbase is always present in data/params

---

contrib/nagios_blocker_checker.pl

https://bugzilla.mozilla.org/show_bug.cgi?id=1326233
Changes mostly follow dylan's suggestions; The 'catch' takes some quick liberties with error text to try to mold it into nagios' preferred structure.

nagios_blocker_checker.pl update to gracefully fail with bad inputs

---

extensions/TrackingFlags/template/en/default/hook/global/user-error-errors.html.tmpl

no bug - spelling error in user-error-errors.html.tmpl

---

contrib/nagios_blocker_checker.pl

Per https://bugzilla.mozilla.org/show_bug.cgi?id=1330293, defaulting to 300s and having the nagios check self-immolate rather than stay around hung and collecting swap space.
I don't know that my sentry_handle_error is correct, and edits are totally welcome toward that end.  I cribbed shamelessly from Bugzilla/Error.pm and didn't test the sentry piece, since I didn't want to start logging false errors.  _Personally_ I am far less interested in sentry getting a log than I am with the script dying-instead-of-lingering; I just added it since the original bug called for it.

Bug 1330293 - Prevent nagios_blocker_checker.pl from running longer than 5 minutes (and log to sentry if it does)

---

extensions/BugModal/web/bug_modal.css
extensions/BugModal/web/bug_modal.js
extensions/BugModal/web/common_bug_modal.css
extensions/BugModal/web/common_bug_modal.js
js/global.js
js/instant-search.js
skins/standard/global.css
skins/standard/page.css
template/en/default/bug/summarize-time.html.tmpl
template/en/default/global/footer.html.tmpl
template/en/default/global/header.html.tmpl
template/en/default/search/field.html.tmpl
template/en/default/search/form.html.tmpl
template/en/default/search/search-instant.html.tmpl
template/en/default/search/search-specific.html.tmpl

Fix [Bug 1426685 - Fix regressions from fixed-positioning global header](https://bugzilla.mozilla.org/show_bug.cgi?id=1426685)
* Fixing these issues:
* The Top button on bug modal is no longer working
* The global header overlaps with the attached image overlay
* The global header overlaps with the Vote For This Bug checkbox

Bug 1426685 - Fix regressions from fixed-positioning global header

---

extensions/PhabBugz/lib/Revision.pm

Remove the hack by using a type union for #312

use a type union and new EmptyStr type

---

skins/standard/global.css

Fix [Bug 1428079](https://bugzilla.mozilla.org/show_bug.cgi?id=1428079). This does the right thing.

Bug 1428079 - No horizontal scrollbar when bug summary is very long or narrow browser width

---

qa/t/lib/QA/Util.pm
qa/t/test_bug_edit.t
qa/t/test_qa_contact.t
qa/t/test_shared_searches.t
skins/standard/global.css
template/en/default/global/header-search-dropdown.html.tmpl
template/en/default/global/header.html.tmpl

Fix [Bug 1428642 - Fix minor bugs on new global header](https://bugzilla.mozilla.org/show_bug.cgi?id=1428642)
* Prevent the magnifier icon on the search bar from triggering searches
* Add Saved Searches Edit link
* Fix some style issues

Bug 1428642 - Fix minor bugs on new global header

---

extensions/BugModal/template/en/default/bug_modal/groups.html.tmpl

This error can be observed in show_bug.cgi's source.

no bug - Fix a markup error

---

js/dropdown.js

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1429449

Bug 1429449 - Do not handle non-primary click on dropdown menu.

---

extensions/BugModal/web/bug_modal.css

Re-did this PR to focus on the sub-900 widths on bug modal

Make bug modal usable at less than 900px

---

js/global.js

Fix [Bug 1429785 - In-page back navigation broken](https://bugzilla.mozilla.org/show_bug.cgi?id=1429785)
This mimics the browser's scroll position auto saving behaviour, so in-page navigation with the back and forward buttons will work as expected.

Bug 1429785 - In-page back navigation broken

---

template/en/default/account/prefs/mfa.html.tmpl

Red Hat OTP App moved to GitHub per bug 1433993

Bug 1433993 Update link to Red Hat OTP App

---

extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/Policy.pm

I had wanted to do this with the other code but it was too big. Policy
is a nice small use case where we can see about making it tidy.
If these changes *work* then I've understood part of this code
correctly.

I found this a bit hard to review, so I've tried to tidy a bit

---

scripts/remove_idle_group_members.pl

[Bug 1436301](https://bugzilla.mozilla.org/show_bug.cgi?id=1436301)

Bug 1436301 - Exempt bot accounts from idle group removal

---

vagrant_support/playbook.yml

creating a new vagrant dev environment failed due to the ntp package not being installed.

Add missing ntp package

---

extensions/BMO/template/en/default/bug/create/create-mdn.html.tmpl

Update custom bug form for the product change to developer.mozilla.org.

Bug 1439693 - Update form.mdn

---

vagrant_support/playbook.yml

Add missing python-sphinx10 package and link.

Bug 1384313 - Can't build the docs from within the vagrant box

---

scripts/generate_bmo_data.pl

Create missing automation@bmo.tld user.

Bug 1441569 - remove_idle_group_members.pl fails on vagrant box

---

jobqueue.pl

Dear reviewer, please compare this to what we do in the BEGIN { } block of checksetup.pl to verify if it is sane or conventional for us.

Bug 1441181 - Step 2 - Fix jobqueue header and @INC

---

Bugzilla/JobQueue.pm
Bugzilla/JobQueue/Runner.pm
jobqueue.pl

Dear reviewer, please especially consider if this patch returns the code to its state prior to Bug 832893

Bug 1441181 - Step 1 - Remove old subprocess code

---

.circleci/config.yml
Dockerfile
Makefile.PL
jobqueue-worker.pl

man prctl and search for DEATHSIG for details on this syscall.

Bug 1441181 - Step 9 - use pdeathsig to prevent workers running without supervision

---

conf/httpd.conf

Overlooked that in prod, timeout is 120 seconds and the max request line size is 35000

no bug - increase httpd limits

---

extensions/OpenGraph/template/en/default/hook/global/header-start.html.tmpl
template/en/default/index.html.tmpl

@dylanwh does this look OK? :-)

Bug 1451960 - Improve opengraph metadata for access-denied bugs

---

extensions/MyDashboard/template/en/default/pages/mydashboard.html.tmpl
extensions/MyDashboard/web/js/flags.js
extensions/MyDashboard/web/js/query.js
extensions/MyDashboard/web/styles/mydashboard.css
extensions/PhabBugz/lib/Util.pm
extensions/PhabBugz/lib/WebService.pm
t/008filter.t

Adds a new table to the top of the right hand column that shows reviews from phabricator.

Bug 1440828 - Phabricator review requests should show up on the BMO dashboard

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1454647" target="_blank">1454647</a>] Mirror all BMO groups as Phabricator projects and keep them in sync</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1452984" target="_blank">1452984</a>] double-check new accounts with BMO to catch and notify of username squatting</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1453759" target="_blank">1453759</a>] Port OrangeFactor extension to treeherder</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1413328" target="_blank">1413328</a>] Use tct (tocotrienol on npm) to encrypt bugmail</li>
</ul>

bump version to 20180508.1

---

extensions/PhabBugz/Extension.pm
extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/Project.pm
extensions/PhabBugz/lib/Revision.pm
extensions/PhabBugz/lib/User.pm
extensions/PhabBugz/lib/Util.pm
extensions/PhabBugz/lib/WebService.pm

Revert "Bug 1440086 - Refactor PhabBugz extension code to use new User.pm module for better type checking"

---

extensions/PhabBugz/lib/Feed.pm

Bug 1460466 - Phab bot does not create r+ for acceptance when there are still blocking reviewers

---

extensions/PhabBugz/Extension.pm
extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/Project.pm
extensions/PhabBugz/lib/Revision.pm
extensions/PhabBugz/lib/User.pm
extensions/PhabBugz/lib/Util.pm
extensions/PhabBugz/lib/WebService.pm

Bug 1440086 - Refactor PhabBugz extension code to use new User.pm module for better type checking

---

ses/index.cgi

Removes branching logic for bounce types and disables e-mail for any bounce.

Bug 1463199 - Treat all SMTP bounce notifications as permanent

---

Bugzilla/Search/Quicksearch.pm

See any negative consequences from this change, @dklawren ?

Bug 1464226 - quicksearch can't search for "Resolution:---"

---

extensions/PhabBugz/lib/Policy.pm

…all list projects when setting up security policies for revisions

Bug 1470485 - Create new policies using PhabricatorProjectsAllPolicyRule instead of PhabricatorProjectsPolicyRule

---

.vscode/tasks.json
README.rst

I'd like to share this [Visual Studio Code task configuration file](https://code.visualstudio.com/docs/editor/tasks) because it's useful for everyone. It allows to update the local server just by hitting Command+Shift+B while making changes in VS Code ✨

no bug - Add VS Code task configuration file

---

extensions/PhabBugz/lib/Feed.pm

Felt the need to simplify the code that is syncing the groups from BMO to Phabricator to see if this problem can be smoked out.

Bug 1472326 - group member syncing is currently broken on production bmo

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1473726" target="_blank">1473726</a>] WebExtensions bugs missing crash reports when viewed</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1469911" target="_blank">1469911</a>] Make user autocompletion faster</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1328659" target="_blank">1328659</a>] Add support for utf8=utf8mb4 (switches to dynamic/compressed row format, and changes charset to utf8mb4)</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1472896" target="_blank">1472896</a>] Update to Gear Store inventory dropdown</li>
</ul>

bump version to 20180712.1

---

extensions/PhabBugz/lib/WebService.pm

Implements https://bugzilla.mozilla.org/show_bug.cgi?id=1478983 and some related cleanups.

Phabbugz can_enter_bug WebService endpoint

---

template/en/default/list/list.html.tmpl

This is my first PR! I hope it works, haha

Bug 1374266 - Improve the "Zarro Boogs found" message

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl

* Add "File New Bug in This Product" menu item to the product hovercard
* Add "File New Bug in This Component" menu item to the component hovercard
[Bug 1480599 - Add "File new bug" menu to product/component hovercard](https://bugzilla.mozilla.org/show_bug.cgi?id=1480599)

Bug 1480599 - Add "File new bug" menu to product/component hovercard

---

Bugzilla.pm
Bugzilla/Install/Localconfig.pm
extensions/Push/lib/Push.pm
template/en/default/setup/strings.txt.pl

Add Datadog metrics monitoring for the Push job scheduler queue and the
job scheduler queue backlogs for each Push connector.

Bug 1480878 - Monitor the health of Push connector job processing

---

js/attachment.js

Use the `text/plain` MIME type instead of `text/markdown` for Markdown to work around a Firefox bug that forces this kind of files to be downloaded.
[Bug 1421032 - Detect Markdown attachment files as text/plain so Firefox can display the content](https://bugzilla.mozilla.org/show_bug.cgi?id=1421032)

Bug 1421032 - Detect Markdown attachment files as text/plain so Firefox can display the content

---

Bugzilla/Quantum.pm
Bugzilla/Quantum/CGI.pm
Bugzilla/Quantum/Home.pm
Bugzilla/Quantum/Plugin/BlockIP.pm
Bugzilla/Quantum/Plugin/Glue.pm
Bugzilla/Quantum/Plugin/Helpers.pm
Bugzilla/Quantum/Plugin/Hostage.pm
Bugzilla/Quantum/SES.pm
Bugzilla/Quantum/Static.pm
Bugzilla/Quantum/Stdout.pm

All the files in the Quantum namespace have been reformatted using the revised perltidyrc.
I'll do this additionally for any files that I've added and have no other changes in later PRs

reformat all new quantum files using new standard

---

extensions/BMO/template/en/default/hook/flag/type_comment-form.html.tmpl

Change the label on the custom approval request form. 
[Bug 1496233 - "Dunno" -> "Don't know" in approval request form](https://bugzilla.mozilla.org/show_bug.cgi?id=1496233)

Bug 1496233 - "Dunno" -> "Don't know" in approval request form

---

README.rst

Update the description as Tasks menu has been merged to Terminal menu.
Also mention an extension bundle made by @dylanwh.

no bug - Update README on VS Code integration

---

Bugzilla/Quantum/Plugin/Hostage.pm

This small change is required to run bugzilla on GKE (google's k8s implementation).
It can be expanded to handle other health checks that are too stupid to send the right Host header.

add simple hack to work in GKE

---

template/en/default/admin/params/query.html.tmpl
template/en/default/bug/dependency-graph.html.tmpl
template/en/default/bug/dependency-tree.html.tmpl

Replace a couple more links missing in #817.

Bug 1497077 followup - Convert links to absolute path

---

Bugzilla/Report/SecurityRisk.pm
scripts/secbugsreport.pl
template/en/default/reports/email/security-risk.html.tmpl

Some additional changed added by the linter.

Bug 1501966 - Warn when there are outdated products or components in the teams list

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1487171" target="_blank">1487171</a>] Allow setting bug flags when creating/updating attachment with API</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1497077" target="_blank">1497077</a>] Convert links, redirects, image/iframe sources, form actions to absolute path</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1469733" target="_blank">1469733</a>] Fix scrolling glitch on Safari</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1496057" target="_blank">1496057</a>] Security bugs report october update</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1499905" target="_blank">1499905</a>] Update BMO …

bump version to 20181029.1

---

docs/en/rst/api/core/v1/flag-activity.rst

Add doc file accidentally left out of previous commit.

Bug 1384230 - Document flag_activity API (part 2).

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1503162" target="_blank">1503162</a>] Approval request form is incomplete in some cases</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1503408" target="_blank">1503408</a>] Remove extensions/PhabBugz/t/review-flags.t as no longer needed</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1503182" target="_blank">1503182</a>] Fix data type of native bug count API return value</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1436619" target="_blank">1436619</a>] http:// in URL field</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1503705" target="_blank">1503705</a>] Stop serving HTML-prettyprinted JSON as …

bump version to 20181106.1

---

Bugzilla/WebService/Bug.pm
docs/en/rst/api/core/v1/bug.rst

As per @dylanwh #891 increases memory usage. Back it out and find a better way to implement.

Revert "Bug 1505793 - Add triage owner in /rest/bug"

---

Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm

These are the schema changes from #820
Since dkl wrote this, and I created this PR,  I can't review it. Also I've stared at it so long I might be missing something. So I know @purelogiq has worked a little bit with oauth2 (but not from this angle) and so I'll let that be the final set of eyes on this.

Bug 1354589 - schema changes only

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1505793" target="_blank">1505793</a>] Add triage owner in /rest/bug</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1506754" target="_blank">1506754</a>] Group Membership report "include disabled users" doesn't seem to work</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1328665" target="_blank">1328665</a>] Two issues with Project Review form for RRAs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1505050" target="_blank">1505050</a>] make the request nagging script more robust</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1504325" target="_blank">1504325</a>] Mozilla Gear Request form broken: The …

bump version to 20181115.1

---

Bugzilla.pm
Bugzilla/Quantum.pm
Bugzilla/Quantum/OAuth2.pm
Bugzilla/Test/Util.pm
t/mojo-oauth2.t
template/en/default/account/auth/confirm_scopes.html.tmpl
template/en/default/global/messages.html.tmpl

This PR only contains the Plugin code and route changes needed to support OAuth2. The t/mojo-oauth2.t test script should still pass with this limited code. Although you will need to first apply the PR #906 before testing.

Bug 1354589 - Implement OAuth2 on BMO

---

Bugzilla/Quantum/OAuth2.pm
Bugzilla/Quantum/OAuth2/Clients.pm
template/en/default/admin/admin.html.tmpl
template/en/default/admin/oauth/confirm-delete.html.tmpl
template/en/default/admin/oauth/create.html.tmpl
template/en/default/admin/oauth/edit.html.tmpl
template/en/default/admin/oauth/list.html.tmpl

 Bug 1354589 - Implement OAuth2 on BMO (Client Admin)

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1484892" target="_blank">1484892</a>] Modify EditComments extension to let anyone use it conditionally and support inline editing</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1354589" target="_blank">1354589</a>] Implement OAuth2 on BMO</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1452018" target="_blank">1452018</a>] Remove remaining Firefox OS and Marketplace references</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=324535" target="_blank">324535</a>] Allow the use of relative dates in charts</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1508201" target="_blank">1508201</a>] Allow bulk edits …

bump version to 20181127.1

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1354589" target="_blank">1354589</a>] Implement OAuth2 on BMO</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1511158" target="_blank">1511158</a>] Enhance comment action button style</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1506725" target="_blank">1506725</a>] Update form.doc to direct reporters to GitHub</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1512424" target="_blank">1512424</a>] Comment Reply button is not working properly on Chrome</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1511466" target="_blank">1511466</a>] The /api/user/profile API should provide the user's MFA …

bump version to 20181207.1

---

extensions/UserProfile/template/en/default/pages/user_profile.html.tmpl

Bug 1516188 : Fixed offside for rowspan of image.

Bug 1516188 : Redesigned the logic of rowspan of image

---

extensions/BMO/Extension.pm

So this obviously fixes the test -- but I'd like a stronger proof that the new code is equivalent to the old code for valid inputs.

Bug 1517606 - Infinite loop in Bugzilla::Extension::BMO::_inject_headers_into_body()

---

Bugzilla/Markdown.pm

This is a bit ugly, but it is more usable than stripping out the html tags.

Bug 1518350 - Allow literal html tags to stand for themselves

---

Bugzilla/Install/Requirements.pm

Features can sometimes have no description.

no bug - silence a warning

---

t/quicksearch.t

Reviewing #1075  made me want some unit tests on this.

no bug - add some quicksearch unit tests

---

vagrant_support/start_morbo

Needs a little something to adjust the urlbase to include https, and documentation. But look!
@kyoshino @purelogiq @dklawren !

no bug - allow morbo to run with ssl

---

extensions/BMO/lib/Reports/Triage.pm

Add GeckoView and Remote Protocol

Bug 1525451 - Update triage owner report defaults

---

extensions/BugModal/template/en/default/bug_modal/attachments.html.tmpl
extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/PhabBugz/Extension.pm

This reverts commit 89fbd49cbee4b3b564b000ce193fd2111938962c.

Revert "Bug 1534084 - Hide Phablicator requests from Attachment list"

---

scripts/secbugsreport.pl

This will save the state of the report class to the data directory.
Take a look at what it stores and see if that will help debug -- do we want to record anything else?

Bug 1538957 - Add debugging information to emails for investigating in more detail later.

---

extensions/BMO/Extension.pm

* Treat Phablicator, MozReview and GitHub pull requests as patches
* Add “Attachment is patch” column to search results
[Bug 1539302 - Add "attachment is patch" field to bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1539302)

Bug 1539302 - Add "attachment is patch" field to bug

---

Bugzilla/App/Command/report_ping.pm

Last one on this topic I promise. Probably.

no bug - allow dumping report ping documents

---

Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm

Bug 1541555 - Schema only

---

Bugzilla/App/Static.pm

This should expose just the new graphs.

Bug 1545269 - Request for Bug Dependency Graphs return a 404

---

extensions/BMO/template/en/default/bug/create/create-nda.html.tmpl

If there is a CASA ticket, use the ticket instead.

no bug - Update of the NDA form

---

extensions/MyDashboard/web/js/query.js
extensions/MyDashboard/web/styles/mydashboard.css

Make the Summary column on [My Dashboard](https://bugzilla.mozilla.org/page.cgi?id=mydashboard.html) a link to the bug, just like the Bug ID column.
[Bug 1552720 - Linkify bug summaries on My Dashboard query table](https://bugzilla.mozilla.org/show_bug.cgi?id=1552720)

Bug 1552720 - Linkify bug summaries on My Dashboard query table

---

Bugzilla/Install/Filesystem.pm
Bugzilla/Install/Localconfig.pm

I think this makes this code easier to read.

no bug - use Package::Stash to read in localconfig variables rather than using ugly native APIs

---

extensions/BMO/bin/migrate-bug-type.pl

no bug - Fix typo in bug type migration script

---

extensions/BugModal/web/bug_modal.css
template/en/default/bug/create/created.html.tmpl

…when email notifications are sent

Bug 1553893 - Remove horizontal rule from summary section as well as when email notifications are sent

---

extensions/BMO/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl
extensions/UserStory/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl
template/en/default/bug/create/create.html.tmpl
template/en/default/bug/field.html.tmpl

Bug Link
https://bugzilla.mozilla.org/show_bug.cgi?id=1556465

Bug 1556465 - When assigning to self on enter_bug.cgi, the (take) link should be a button instead of normal link to be consistent

---

Bugzilla/Bug.pm

Order bug history by `bugs_activity.id` so changes divided into multiple rows will be joined properly. Tested with all reported cases except for a recent bug not in my local DB snapshot.
Ideally 1 row should only have 1 item. Perhaps the change could be done as part of [Bug 1509332](https://bugzilla.mozilla.org/show_bug.cgi?id=1509332).
[Bug 1556178 - Extraneous comma in history due to wrong joins, e.g. depends_on field in bug 1369194](https://bugzilla.mozilla.org/show_bug.cgi?id=1556178)

Bug 1556178 - Extraneous comma in history due to wrong joins, e.g. depends_on field in bug 1369194

---

docs/en/rst/using/finding.rst

Adds documentation for relative searches

Bug 1557186 Document relative dates in searches

---

extensions/BMO/template/en/default/bug/create/create-client-bounty.html.tmpl
extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/web/bug_modal.css
extensions/MyDashboard/web/styles/mydashboard.css
extensions/PhabBugz/web/style/phabricator.css
skins/standard/attachment.css
skins/standard/buglist.css
skins/standard/dependency-tree.css
skins/standard/global.css

Make the new skin better.
[Bug 1558494 - Fix some more issues in the post-Sandstone skin](https://bugzilla.mozilla.org/show_bug.cgi?id=1558494)

Bug 1558494 - Fix some more issues in the post-Sandstone skin

---

docs/en/rst/using/finding.rst

* where saved searches go
* remove self-tagging references

No bug: update search documentation

---

Bugzilla/DB.pm
Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm

Bug 1546788 - schema only

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1546788" target="_blank">1546788</a>] Deselect bug type by default unless component-specific type is defined</li>
</ul>

Bump version to 20190627.2

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1562139" target="_blank">1562139</a>] "Edit Search" broken</li>
</ul>

Bump version to 20190628.1

---

.circleci/config.yml
scripts/entrypoint.pl

This reverts commit 0985893416bff1050a639dd09e22fb8aec307a47.

Revert "no bug - Do not create qa data if not running qa tests"

---

js/field.js

Fix a script error that prevents flag requestee autocomplete from being displayed. The issue happens with any requestable flags other than review, feedback and needinfo.
[Bug 1566079 - User autocomplete doesn’t work for requestee for certain flags](https://bugzilla.mozilla.org/show_bug.cgi?id=1566079)

Bug 1566079 - User autocomplete doesn’t work for requestee for certain flags

---

docs/en/rst/using/finding.rst

Add documentation for restricted bug search

Bug 1563868 update documentation for searching on bugs by group restriction

---

Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm

Bug 1252298 - schema only

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1524174" target="_blank">1524174</a>] Redirect to show_bug.cgi after creating bug or updating a bug</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1563269" target="_blank">1563269</a>] Stray "from" when redirecting needinfo</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1562804" target="_blank">1562804</a>] status NEW is not present in the status changed section in a bugzilla user profile</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1524175" target="_blank">1524175</a>] Redirect to show_bug.cgi after creating or updating an attachment</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1563312" target="_blank">1563312</a>] Needinfo links at top of bug goes to …

Bump version to 20190718.1

---

scripts/movecomponent-1565636.pl

Special one-off script that moves a component while reassigning version and milestones based on a hard coded mapping. If an entry on the map doesn't exist, it just leaves the version and milestone alone as they already exist in the destination product.

Bug 1565636 - Component description for "Firefox for Android :: Build Config & IDE Support" is out of date

---

Bugzilla/Component.pm
Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm
editcomponents.cgi
template/en/default/admin/components/edit-common.html.tmpl
template/en/default/bug/create/create.html.tmpl

Implement component-level bug description (comment) templates that can override product-level templates already implemented in #942.
[Bug 1252298 - Feature Request: Issue Templates for Components](https://bugzilla.mozilla.org/show_bug.cgi?id=1252298)

Bug 1252298 - Feature Request: Issue Templates for Components

---

Bugzilla.pm

* [[1566997](https://bugzilla.mozilla.org/show_bug.cgi?id=1568695)] Add Firefox Brand to New Bug Flow
* [[1565872](https://bugzilla.mozilla.org/show_bug.cgi?id=1565872)] Fix miscellaneous typos and spelling inconsistencies
* [[1565319](https://bugzilla.mozilla.org/show_bug.cgi?id=1565319)] FF Version selection does not update from client version, shows previous reported version
* [[1567571](https://bugzilla.mozilla.org/show_bug.cgi?id=1567571)] Make featured product list 3+ columns
* [[1568259](https://bugzilla.mozilla.org/show_bug.cgi?id=1568259)] Short URL generation isn't working
* [[1568863](https://bugzilla.mozilla.org/show_bug.cgi?id=1568863)] Prefilled comment will be wiped after changing component

Bump version to 20190725.1

---

query.cgi

Allow to edit custom fields including tracking flags on the Advanced Search page, when they’re passed through URL params as the shorthand syntax like `cf_status_firefox69=affected`. This internally converts the params into the custom search longhand syntax: `f1=cf_status_firefox69&o1=anyexact&v1=affected`.
[Bug 1568592 - Custom fields are lost when using Edit Search](https://bugzilla.mozilla.org/show_bug.cgi?id=1568592)

Bug 1568592 - Custom fields are lost when using Edit Search

---

Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm

Should be merged before #1402.

Bug 1565403 - schema only

---

extensions/BugModal/web/bug_modal.css

Fix the alignment issue mentioned by dkl on Slack.

no bug - Fix alignment of Save Changes button at the bottom of modal UI

---

Bugzilla/User/APIKey.pm

To test:
* Adding api keys should show up as __create__ entries  in bugs.audit_log table.
* Updating revoked and or sticky bit values for an api key should show up as field updates.
* Changes to last_used and last_used_ip values should not show up in the audit_log table.

Bug 1580371 - Audit changes to user api key changes to the audit log table (skip last_used information)

---

Bugzilla/Report/SecurityRisk.pm
scripts/secbugsreport.pl
t/security-risk.t
template/en/default/reports/email/security-risk.html.tmpl

At the request of the triage team.

Bug 1578965 - Security Bugs Report: Change median age of open bugs to # of bugs older than 45 days

---

extensions/BMO/template/en/default/account/create.html.tmpl
extensions/BMO/web/styles/create_account.css

Bug 1461358 - Add a dev server link to the account creation process.

---

scripts/secbugsreport.pl
template/en/default/reports/email/security-risk-moderate-low.html.tmpl

This augments the existing secbugsreport.pl script to also send a report
on sec moderate and sec low bugs in a separate email according to the
sec teams requests. Will run in the same script so no need for an extra
cron job.

Bug 1597800 - Send a sec bug report for moderate and low levels

---

Bugzilla/DB/Schema.pm
Bugzilla/DB/Schema/Mysql.pm
Bugzilla/DB/Schema/Oracle.pm
Bugzilla/DB/Schema/Pg.pm
Bugzilla/DB/Schema/Sqlite.pm
Bugzilla/Install/DB.pm
extensions/Review/Extension.pm

Schema changes only for bug 1588221

Bug 1588221 - Update current s3 storage controller to only upload attachments over a certain size (schema only)

---

.circleci/config.yml
.dockerignore
Bugzilla/DaemonControl.pm
Dockerfile
Dockerfile.bmo-slim
README.rst
conf/checksetup_answers.txt
docker-compose.test.yml
docker-compose.yml
docker/mysql/bmo.cnf
docker/tinyproxy/Dockerfile
docker/tinyproxy/tinyproxy.conf
scripts/auth-test-app
scripts/entrypoint.pl
scripts/start_morbo
t/db-error-cleanup.pl
t/markdown.t
t/mojo-example.t

You can sync new code changes locally into the running container using the following:
$ docker-compose exec bmo-web.vm rsync -avP --exclude .git --exclude local /mnt/sync/ /app/

Bug 1608491 - Improve docker environment for developers wanting to work on bmo code

---

qa/t/test_flags.t

I thought the tests for #1362 were passing, but the button on the modal bug UI is labelled as **Attach New File**, not Attach File. This should fix the current failures on master.

no bug - Fix Selenium tests for #1362

---

Bugzilla/Mailer.pm

Remove custom header encoding function from Mailer.pm and instead use Email::MIME::header_str_set which will handle special encoding for headers for us.

Bug 1611494 - Bugzilla custom email headers are getting mashed together

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1612290" target="_blank">1612290</a>] Provide self-service UI for users to reactivate their account after being disabled due to bouncing</li>
</ul>

Bump version to 20200226.2

---

CONTRIBUTING.md
extensions/BMO/template/en/default/pages/etiquette.html.tmpl

Update emails and links for contact and reporting.

1622956 Update contact URL and Address

---

extensions/MyDashboard/web/js/flags.js
extensions/MyDashboard/web/js/query.js

As an Outreachy applicant, I made the enhancement  Bug-849902 - my dashboard should be able to refresh on its own. Taking the suggestions from the comments it refreshes itself every 10 minutes.
@dklawren @emceeaich

Bug 849902 - My dashboard refreshes itself

---

extensions/BugModal/web/bug_modal.js
js/field.js
template/en/default/reports/keywords.html.tmpl

Made changes to the edit bug and add bug workflow.

Bug 1183759 :  Keyword suggestions should not show keywords which have been already selected 

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1621662" target="_blank">1621662</a>] Remove option for using Vagrant for BMO development and support Docker as primary method</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1621160" target="_blank">1621160</a>] First row of stagger column headers will be hidden when table header becomes sticky</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1621278" target="_blank">1621278</a>] Make bug IDs on search results proper bug links</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1622956" target="_blank">1622956</a>] Update contact emails and URLs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1344094" target="_blank">1344094</a>] Add a link to a wiki.mozilla.org page …

Bump version to 20200401.1

---

Bugzilla.pm
Bugzilla/Install/DB.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1622311" target="_blank">1622311</a>] For security bugs, link the security issue banner to https://wiki.mozilla.org/Security/Bug_Approval_Process</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1626543" target="_blank">1626543</a>] Some fields on enter bug page do not have associated labels</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1627601" target="_blank">1627601</a>] Copy Summary function doesn’t work properly if the bug summary contains HTML tags</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1628467" target="_blank">1628467</a>] Add a method to opt-out of auto-refreshing on my dashboard</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1202669" …

Bumped version to 20200416.2

---

extensions/PhabBugz/lib/Revision.pm
extensions/PhabBugz/lib/User.pm

Bug 1633848 - Fix possible areas where memory leak can occur in the PhabBugz daemon code

---

extensions/GuidedBugEntry/template/en/default/guided/guided.html.tmpl

The form still had the 'normal' severity.

Bug 1636549 Guided Bug Form incorrect severity

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1647642" target="_blank">1647642</a>] when commenting on patch or reviewing one, bugzilla clears other (review, ui-review) flags</li>
</ul>

Bumped version to 20200723.1

---

scripts/import_email.pl
t/.perlcritic-history

`$ perl scripts/import_email.pl data/mailer.testfile`

Bug 1657542 - During recent bmo deployment, emails were delivered to a file instead of SES which caused interruption of email service

---

extensions/Push/lib/Connector/Webhook.pm
extensions/Webhooks/Extension.pm
extensions/Webhooks/template/en/default/account/prefs/webhooks.html.tmpl
extensions/Webhooks/template/en/default/hook/global/user-error-errors.html.tmpl

@dklawren I made some little changes that I saw, and the UI is like this:

Bug 1658846 - Allow users to enable and disable their webhooks

---

extensions/Webhooks/Extension.pm
extensions/Webhooks/template/en/default/account/prefs/webhooks.html.tmpl
extensions/Webhooks/template/en/default/hook/global/user-error-errors.html.tmpl
extensions/Webhooks/template/en/default/pages/webhooks_queues.html.tmpl

The queue count is added as a column in the webhooks table and if exist a queue, is created a link to the webhooks_queues page.

Bug 1658845 - Allow users to see their own queue for their webhooks

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1661042" target="_blank">1661042</a>] Add a new table profile_iam to contain mappings between BMO accounts and LDAP accounts</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1656609" target="_blank">1656609</a>] Consider structuring show_bug.cgi in such a way that it's the &lt;html&gt; element that scrolls, not a descendant</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1664896" target="_blank">1664896</a>] checksetup.pl error when updating oath2_scope table to add detailed scope descriptions.</li>
</ul>

Bumped version to 20200916.1

---

extensions/BugModal/web/bug_modal.css
extensions/BugModal/web/bug_modal.js
extensions/BugModal/web/comments.js

- fix scrolling and overflow of lightboxed content
- remove duplicate element creation when clicking on in-comment images
- fix colouring of lightbox title
- fix missing lightbox title when clicking on in-comment images

Bug 1665891 - fix lightbox scrolling

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1665916" target="_blank">1665916</a>] Remove block severity from blocklist bug creation template</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1665891" target="_blank">1665891</a>] Overlaid image viewer is not full in height</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1666292" target="_blank">1666292</a>] Blue "New comments" popup not clickable</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1666917" target="_blank">1666917</a>] Remove code from PhabBugz extension dealing with auth delegation since it is no longer used</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1667201" target="_blank">1667201</a>] Replace Reps profile with Community Portal profile in …

Bumped version to 20200928.1

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1668308" target="_blank">1668308</a>] Unauthenticated searches can generate massive cookies</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1668439" target="_blank">1668439</a>] Overlaid image viewer is not full in height</li>
</ul>

Bumped version to 20201001.1

---

extensions/BugModal/web/bug_modal.css
extensions/BugModal/web/bug_modal.js

- reposition the lightbox's close button out from under the header

Bug 1670574 - The lightbox close button should be visible.

---

.dockerignore
Bugzilla/App/Plugin/OAuth2.pm
Bugzilla/Auth/Login/APIKey.pm
Bugzilla/Install/DB.pm
Bugzilla/Test/Util.pm
qa/t/rest_bug.t
t/mojo-oauth2.t

Second time around. This time with moar testing.

Bug 1670319 - Allow use of OAuth2 bearer token as authentication for API calls same as API keys

---

Bugzilla/API/V1/Teams.pm
Bugzilla/Config/Reports.pm
Bugzilla/Field.pm
Bugzilla/Search.pm
Bugzilla/Teams.pm
buglist.cgi
template/en/default/admin/params/reports.html.tmpl

Will not work without configuring the new `report_component_teams` parameter.

Bug 1673948 - Add "Team Name" as a search column

---

extensions/BugModal/web/bug_modal.js

- reverts db08f0cad7307eb7b42ddd858ed1f920675feb2a

Bug 1680775 - fix tooltip placement

---

Bugzilla/Search.pm

sigh. swore i tested this originally :/

Bug 1695739 - "Team Name" search doesn't work

---

Bugzilla/WebService/User.pm

Adds a `uuid` field to the `whoami` call, which is a SHA1 of the user's
ID using the site-wide-secret as the key.

Bug 1698430 - Add a per-user UUID for telemetry

---

extensions/MozChangeField/Extension.pm
extensions/MozChangeField/lib/Post/CrashKeywordSetSeverity.pm
extensions/MozChangeField/lib/Pre/CanConfirm.pm
extensions/MozChangeField/lib/Pre/CustomField.pm
extensions/MozChangeField/lib/Pre/Reopen.pm
scripts/generate_bmo_data.pl

- Refactored MozChangeField to support pre and post actions.

Bug 1690202 - Automatically set severity to S2 for all new bugs with the crash keyword

---

Bugzilla/Auth/Verify/DB.pm

Bug 1719378 - Fix bug in code that allows inactive users to reactivate their own accounts

---

showdependencygraph.cgi

Bug 1729495 - Update showdependencygraph.cgi to not create a png file in data/webdot and instead include as base64 data

---

scripts/bug1749479.pl

Reopening as the script needs additional changes to narrow down the query results to bugs where the 'Has Regression Range' field is enabled and not all bugs. I only updated a couple as a test when I realized this issue.

Bug 1749479 - Add "regression" keyword and set "Has Regression Range" to "yes" on all bugs with a non-empty "Regressed By" field

---

Bugzilla/User.pm
Bugzilla/WebService/User.pm
docs/en/rst/api/core/v1/user.rst

Bug 1767990 - Expose `last_activity_ts` in the /rest/user endpoint

---

Bugzilla/WebService/Server/XMLRPC.pm

Happens with XMLRPC calls only. REST is not affected. See bug for more detail.

Bug 1774872 - XMLRPC Error "->type(dateTime, undef) called from Bugzilla::WebService::User line 299"

---

extensions/Push/lib/Connector/Webhook.pm

review+ from @zzzeid using Splinter on bug report.

Bug 1778705 - Webhooks expose private bug details to users who do not have access to them

---

extensions/PhabBugz/web/js/phabricator.js

Sort reviewer names alphabetically.

Bug 1777640 - Make the order of the reviewers in the phabricator revisions section stable.

---

extensions/PhabBugz/web/js/phabricator.js

for https://bugzilla.mozilla.org/show_bug.cgi?id=1782398

Bug 1782398 - Linkify title of phabricator revision title

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/web/bug_modal.js

- adds WONTFIX and WORKSFORME to bottom-of-page resolution button set
- fixes focus and scrolling issues around the duplicate bug id field

Bug 1329271 - Add WONTFIX and WORKSFORME to bottom-of-page resolution button set

---

extensions/SecureMail/template/en/default/pages/securemail/help.html.tmpl

In addition to changing the Thunderbird link, I did some needed cleanup.

Bug 1794425 - Stop recommending Enigmail for Thunderbird

---

template/en/default/admin/oauth/provider/create.html.tmpl
template/en/default/admin/oauth/provider/edit.html.tmpl

- Increase size of field and maxsize for creation and editing
- Cleaned up formatting as well for edit form.

Bug 1795160 - OAuth2 client admin UI form field for description is too small and should be size of DB column

---

extensions/BMO/lib/Reports/Triage.pm

This PR mainly tweaks the way Yes/No is displayed if the products default security group is core-security. Other product/component rows will determine Yes/No the previous way. The core security team is a small group who then triage the bugs to other products/components which use other *-core-security groups. So if the triager owner is in one or more of the *-core-security groups (but maybe not in core-security itself) then treat it like they are in core-security.

Bug 1796692 - Update triage owners report to alter permitted status values depending on if the product belongs to core-security

---

Bugzilla/API/V1/Github.pm
qa/t/rest_github_pull_request.t

Bug 1799736 - Use title of Github Pull Request instead of generic "GitHub Pull Request" string

---

extensions/Webhooks/Extension.pm
extensions/Webhooks/template/en/default/account/prefs/webhooks.html.tmpl

Increase the size of the URL data field to 255 (what were we thinking? :) and also do some UI tweaks and cleanup.

Bug 1803939 - Webhook URL field is too short

---

Bugzilla/Report/SecurityRisk.pm

Bug 1806477 - Secbugsreport CronJob failing in latest release

---

extensions/PhabBugz/lib/API/V1/Lando.pm
qa/t/rest_lando_uplift.t
scripts/generate_bmo_data.pl

Adds keywords to the bug data returned.

Bug 1818541 - add bug keywords to Lando uplift GET response

---

extensions/Bitly/lib/WebService.pm

* Converted to use the v4 of the Bitly API.
* Using mojo_user_agent instead of LWP::UserAgent since this handles the setup work.

Bug 1822738 - Generating a Short URL (which uses bitly) no longer works - returns PERMANENTLY_REMOVED

---

extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/Util.pm

When processing revision attachments changes to bugs in phab-bot
feed reader, check if the attachment belongs to an uplift revision
and sync the approval flag statuses as appropriate. To do this
we make the `set_approval_flag_statuses` function more generic
by accepting a flag status instead of hard-coding the `?` status.
We also move the call to update the attachment to the caller.

Bug 1825961: sync revision status with `approval-mozilla-{repo}` flag

---

Bugzilla/Search.pm

Adds support for `order=bug_list`

Bug 1836202 - Add the ability to list bugs in the order provided by the `bug_id` parameter

---

extensions/SiteMapIndex/lib/Config.pm
extensions/SiteMapIndex/lib/Util.pm
extensions/SiteMapIndex/template/en/default/admin/params/sitemapindex.html.tmpl

Add new configuration parameter for the SiteMapIndex extension that allows changing the aws region in the future.

Bug 1842217 - Add configuration parameter to SiteMapIndex extension for configuring AWS S3 region

---

extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/Util.pm

- Add more debugging in places where it will be helpful to determine which conditions that approval flags are not being set
- Some small refactoring to make the code less complex in places such as attachment creation. create_revision_attachment will always return a single attachment such as when a new one is created or an old one is present.

Bug 1844183 - Cleanup and addition of additional debugging to Phabbugz code

---

extensions/BMO/lib/Reports/WhatsNext.pm
extensions/BMO/template/en/default/pages/whats_next.html.tmpl
extensions/BMO/web/js/whats_next.js
extensions/BMO/web/styles/whats_next.css

- tables should be full page width
- bug summary should wrap
- tables should be sortable by clicking on column headers
- show a count of the number of bugs
- add a link to buglist.cgi
- add total bug counter to favicon
- use css over table attributes (eg. nowrap -> white-space:nowrap)
- fix broken html (eg. duplicate ids)

Bug 1846398 - UI tweaks to the What Should I Work On Next page

---

js/components/select.js

[Bug 1874037 - Type to search options doesn’t work with custom <bz-select> element having no search bar](https://bugzilla.mozilla.org/show_bug.cgi?id=1874037)
Restore the native `<select>` element’s type-to-search functionality. For example,
- Click on the Platform field
- Hit the A key to select All
- Hit the A key again to select ARM

Bug 1874037 - Type to search options doesn’t work with custom <bz-select> element having no search bar

---

docs/en/rst/requirements.txt

Doing this change due to https://github.com/mozilla-bteam/bmo/pull/2172 but also had to pin some other sphinx add-ons due to the error described here https://github.com/biopython/biopython/issues/4581

no bug - Update to more recent sphinx versions

---

js/components/select.js

Reverts mozilla-bteam/bmo#2169

Revert "Bug 1874015 - Can no longer open-select-close bugzilla dropdowns in a single drag gesture"

---

skins/standard/global.css

Reverts mozilla-bteam/bmo#2167

Revert "Bug 1873826 - Scrollbar gets hidden when opening dropdown menu"

---

extensions/BugModal/web/bug_modal.js

Reverts mozilla-bteam/bmo#2166

Revert "Bug 1873913 - The request information feature no longer autofills the selected person's email into the text box"

---

Bugzilla.pm
qa/t/1_test_duo_requirement.t
template/en/default/account/prefs/mfa.html.tmpl
userprefs.cgi

- Fixed issue where required date was not being cleared properly.
- Added additional text to the MFA preference page explaining why MFA is required.

Bug 1879358 - Fix a few remaining issues with code changes enforcing duo 2fa for certain members

---

extensions/BMO/template/en/default/global/choose-product.html.tmpl
extensions/BMO/web/styles/choose_product.css
extensions/BugModal/template/en/default/bug_modal/attachments.html.tmpl
extensions/BugModal/template/en/default/bug_modal/create.html.tmpl
extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/template/en/default/bug_modal/header.html.tmpl
extensions/BugModal/web/bug_modal.css
extensions/ProdCompSearch/web/styles/prod_comp_search.css
extensions/Review/web/styles/badge.css
skins/standard/advanced-search.css
skins/standard/attachment.css
skins/standard/buglist.css
skins/standard/global.css
skins/standard/search_form.css
template/en/default/global/header.html.tmpl
template/en/default/global/tabs.html.tmpl
template/en/default/list/list.html.tmpl
template/en/default/list/table.html.tmpl
template/en/default/search/search-advanced.html.tmpl
template/en/default/search/search-specific.html.tmpl
template/en/default/search/tabs.html.tmpl

[Bug 1878813 - Make search pages and enter/show bug pages responsive](https://bugzilla.mozilla.org/show_bug.cgi?id=1878813)
This makes the following pages responsive for a better experience on mobile:
- Simple search
- Advanced search
- Search results
- Enter bug
- Show bug
The changes for the new attachment overlay are not included. I’ll work on it once #2186 is merged.

Bug 1878813 - Make search pages and enter/show bug pages responsive

---

extensions/BMO/web/js/edituser_menu.js
extensions/BugModal/web/bug_modal.js

Bug 1888462 - Since bug 1157227 landed Profile link is missing in the user drop down and also drop down is broken for cc list members

---

extensions/Push/lib/Connector/Webhook.pm

See [bug 1834454](https://bugzilla.mozilla.org/show_bug.cgi?id=1834454)
Caveat: I have no way to test this.

Bug 1834454 - Webhooks should fire if bug removed from matching product

---

extensions/UserProfile/lib/Util.pm
extensions/UserProfile/template/en/default/pages/user_profile.html.tmpl

for https://bugzilla.mozilla.org/show_bug.cgi?id=1891822

Bug 1891822 - Add "assigned to and fixed" field, and reword bugs statuses label

---

template/en/default/index.html.tmpl

Updated the BMO home page based on discussion in bug 1899323.

Bug 1899323 - Show "Report a new bug in a Mozilla product" to unauthenticated users on the home page

---

extensions/BMO/lib/Reports/Attention.pm

Bug 1898573 - "What Needs My Attention?" incorrectly classifies "Highest Priority Tasks" on bugs with multiple keywords

---

template/en/default/global/header.html.tmpl

Sorry for the extra review. I was supposed to remove this part before the last review and forgot. I took a different route than I was originally thinking. Thanks.

Bug 1908389 - Remove entry in user dropdown in header when a users email is currently disabled

---

extensions/GuidedBugEntry/web/js/products.js

Bug 1710271 - Add link to support as alternative to bugzilla for new Thunderbird bug reporters

---

Bugzilla/DB/Schema.pm

Extracted the `Schema.pm` change from #2293.

Bug 1421401 - Implement emoji comment reactions (schema only)

---

qa/t/1_test_custom_fields.t

See comment at https://bugzilla.mozilla.org/show_bug.cgi?id=1923674#c2

Bug 1923674 - qa/t/1_test_custom_fields.t failing in CI after recent updates

---

Bugzilla/Search.pm

The old implementation only added the metadata to supplemental queries, missing the main (and most important) query.

Bug 1948705 - add search metadata to all SQL queries

---

extensions/BMO/bin/export_bmo_etl.pl

Even with adding a default value for modification_ts, with the migration script from [bug 1926081](https://bugzilla.mozilla.org/show_bug.cgi?id=1926081) still running in the background (very slowly), when the script starts to export the profiles and hits a similar place in the profiles table that the migration script is hitting, it causes the script to crash.
So I want to temporarily not cache profile rows in the DB and just send the data directly. When the migration is complete, we can add the caching back in. I need this to get consistent nightly exports of BMO data without crashes. Also the profiles table is not huge like the other tables so it doesn't really effect the export time significantly.

Bug 1949285 - BMO ETL: Update export script to temporaily not cache profiles daat until migration is complete from bug 1926081

---

extensions/TrackingFlags/lib/Flag/Visibility.pm

make sure the component_id list is not empty before executing the SQL statement

Bug 1949988 - Bugzilla DB Error can occur under certain conditions when determining tracking flag visibility

---

extensions/BMO/web/js/edituser_menu.js
extensions/Needinfo/template/en/default/bug/needinfo.html.tmpl

Bug 1196803 - Add a needinfo option for a user drop down for quick needinfo

---

extensions/BMO/bin/export_bmo_etl.pl

This wraps two DB calls for getting and storing cached data in the BMO database when exporting to BigQuery. There have been intermittent crashes in the past during these operations that would cause the entire export to fail. At least now the error will be logged but the export will continue on. The critical part is just getting the data to BigQuery each day, whether it is cached or not. I will still be able to look at logs for any errors and address them as they appear.

Bug 1959485 - BMO ETL: Wrap DB calls for storing/retrieving cached data in try/catch to allow script to continue export to BQ if exception occurs

---

extensions/BMO/bin/export_bmo_etl.pl

- Wrapped entire export in transaction ensuring consistent read data in case rows are changed or deleted during export
- Added additional debugging output

Bug 1967247 - BMO ETL: Create transaction around entire export process with  REPEATABLE READ  isolation to ensure data integrity

---

extensions/BMO/bin/export_bmo_etl.pl

With the landing of [bug 1968044](https://bugzilla.mozilla.org/show_bug.cgi?id=1968044). I was trying to fix a looping issue for mainly the flag table where it would shrink while we were pulling blocks of data 1000 rows at at time. It would get stuck in an endless loop since the $total had decreased from when we first read the total count and so $count would never equal $total to break out.
Using transactions to give a snapshot of the flags table, which should have not seen any changes, did not work as it gave locking errors often.
The change in [bug 1968044](https://bugzilla.mozilla.org/show_bug.cgi?id=1968044) introduced a new logic bug of its own. We would select rows 100 blocks at a time and then loop as long as their were more rows available. When we hit a 1000, we then would reset …

Bug 1969307 - BMO ETL: Fix logic bug introduced by bug 1968044 that caused the looping of database rows to exit too early leaving out data

---

extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/Util.pm

Redo of pr #2441 This with proper references.

Bug 1965553 - Uplift approval set in bugzilla without relman approval

---

extensions/BMO/web/js/edituser_menu.js
extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/web/bug_modal.css
extensions/BugModal/web/bug_modal.js
extensions/ComponentWatching/web/js/overlay.js
extensions/MozChangeField/web/js/comment-on-severity.js
js/util.js
skins/standard/global.css

[Bug 1984006 - Copy name action doesn't copy](https://bugzilla.mozilla.org/show_bug.cgi?id=1984006)
Add utility methods to enable copy and toast notifications on all pages, not just the modal bug page.

Bug 1984006 - Copy name action doesn't copy
