mozilla-bteam/bmo

template/en/default/mfa/totp/verify.html.tmpl

An acquaintance of mine (@josephlhall) recently had something happen to his phone, and wasn't able to recover the seeds from his TOTP application.  He was frustrated at not being able to get into his account without his 2FA device, because we didn't have a fallback 2FA option.
It turns out that we do (and did) have a fallback option; he had just forgotten about it, because the signin page makes no mention of it.  Once I reminded him about them, he was able to use those codes to get into his account.
It would be great if our 2FA login page mentioned these recovery codes.

Bug 1321596 - Add verbiage about using recovery codes

---

extensions/BugModal/template/en/default/bug_modal/new_comment.html.tmpl
template/en/default/bug/comment.html.tmpl

Bug 1323244 - Make the link to Mozilla Community Participation Guidelines not participate in keyboard navigation

---

extensions/BugModal/web/bug_modal.js

Bug [1344769](https://bugzilla.mozilla.org/show_bug.cgi?id=1344769)

Bug 1344769 - Cancel editing button loads BugZilla homepage instead of current bug

---

extensions/BugModal/Extension.pm

Noticed this while looking for something else and now I can't stop seeing it.

Comment typo fix: INCOMPELTE > INCOMPLETE

---

extensions/BugModal/web/bug_modal.js

[Bug 1343845 - bug status summary does not work when logged out](https://bugzilla.mozilla.org/show_bug.cgi?id=1343845)
Move the block of code which updates the Readable Bug Status field above the point where we return from the anonymous function in the case of no login session.

Bug 1343845 - bug status summary does not work when logged out

---

Bugzilla/Hook.pm
Bugzilla/Template/Context.pm
extensions/BMO/Extension.pm
extensions/BugModal/Extension.pm
extensions/BzAPI/Extension.pm
extensions/ComponentWatching/Extension.pm
extensions/FlagDefaultRequestee/Extension.pm
extensions/FlagTypeComment/Extension.pm
extensions/InlineHistory/Extension.pm
extensions/MozReview/Extension.pm
extensions/OrangeFactor/Extension.pm
extensions/SecureMail/Extension.pm
extensions/ShadowBugs/Extension.pm
extensions/SiteMapIndex/Extension.pm
extensions/TrackingFlags/Extension.pm
extensions/Voting/Extension.pm

We can skip a lot of method calls if extensions must declare what
templates they act on.

Bug 1352913 - Extensions must register for template_before_process()

---

Bugzilla/Template.pm

Bug Desc: [Bug 1355100](https://bugzilla.mozilla.org/show_bug.cgi?id=1355100)
Refer https://support.google.com/webmasters/answer/96569\?hl\=en

Bug 1355100 - Add rel=nofollow to all external links in bug comments

---

Bugzilla.pm

Instead of setting the request cache to an empty list, we set it to a list
k/v pairs built as a map over the 'except' option (which defaults to nothing)

Bug 1360675 - Bugzilla->clear_request_cache: add option to preserve some keys in the request cache

---

Bugzilla/User.pm
extensions/Needinfo/template/en/default/bug/needinfo.html.tmpl

Turns out I missed the logic for displaying the real name beside the needinfo
role selector. That logic is scary and weird and I would've replaced it had I
noticed it then.
This patch removes the template code that generated JS, and instead puts
populates a data-identity attribute with the real name (or login name).
I added a convenience method to Bugzilla::User for this, which can later be
upstreamed.

Bug 1357775 - the needinfo dropdown for the triage owner should display the name and email address when selected

---

vagrant_support/cron.yml

No bug -- since this is just a dev environment fix.

give each cron job a name, so that they don't accumulate

---

extensions/OrangeFactor/web/js/orange_factor.js

OrangeFactor is now behind SSO, so cross-origin requests to the API must use `withCredentials` to ensure the session cookie is sent if it exists. OrangeFactor's API permits this via appropriately set `Access-Control-Allow-{Origin,Credentials}` headers.
Users will also now be reminded about the need to sign in via OrangeFactor first.
Unfortunately there's no way to catch the SSO HTTP 302 separately from other failure modes, since:
(a) the `XMLHttpRequest` spec doesn't allow for telling if a request redirected
(b) the workaround (sniffing content-type of the response and seeing if it's `text/html` rather than `application/json`) isn't possible since BMO's CSP blocks the request to auth0.com.
...however this extension is going to be replaced once OrangeFactor is decommissioned, so meh.
The …

Bug 1368739 - Make OrangeFactor extension work with SSO

---

extensions/BMO/template/en/default/pages/get_permissions.html.tmpl

As specified in [Bug: 1364634](https://bugzilla.mozilla.org/show_bug.cgi?id=1364634), the link to `editbugs` in `get_permissions.html.tmpl` has been updated successfully.

Bug 1364634 - Point people to the editbugs request component instead of the mailing list

---

extensions/PhabBugz/Extension.pm
extensions/PhabBugz/bin/update_project_members.pl
extensions/PhabBugz/lib/Config.pm
extensions/PhabBugz/template/en/default/admin/params/phabbugz.html.tmpl

https://bugzilla.mozilla.org/show_bug.cgi?id=1370378

Fix bug #1370378 - Add Phabricator Extension enabled flag to instantly toggle off all Phabricator syncing. r?dkl

---

Bugzilla/Install/Requirements.pm
Makefile.PL
extensions/Bitly/Config.pm

This patch:
1. adds LWP::Protocol::connect
2. moves LWP::UserAgent (also known as 'LWP') and Mozilla::CA from Bitly (which required the specific version) to the main, always-required part of Makefile.PL. 
3. Removes LWP::UserAgent from the 'updates' feature
4. As auth_delegation now doesn't require anything that isn't always present, there is no reason to define it as a 'feature' in Makefile.PL so that is also removed.
I've also pushed this to the 'carton' branch, and started a new build of the vendored dependencies. I'll update this bug with a link to build results shortly. (probably it will take an hour to finish building).

Bug 1370973 - Add support for CONNECT proxy (add LWP::Protocol::connect)

---

extensions/BzAPI/lib/Resources/Bugzilla.pm

I made a rookie mistake and confused the precedence of and/not vs. &&/!. Using && and ! results in the desired behavior.

Bug 1372539 - Fix incorrect caching on bzapi/configuration

---

extensions/BugModal/Extension.pm
extensions/Needinfo/Extension.pm

By default, include needinfo everywhere.
Also set the default for bug modal to on.

Bug 1372363 - Fix BMO defaults (bug modal pref, needinfo exclusions)

---

.htaccess
Bugzilla/ModPerl.pm

So the fix here is to give an ErrorDocument outside of any <Directory>,
as the "global" level ErrorDocument is what AllowEncodedSlashes wants to use.

Bug 1373295 - Encoded slashes in url allow misleading text on unstyled 404 pages due to AllowEncodedSlashes

---

t/902-crypt-openpgp-random.t

This is likely a *failing* test case, but that's good because it lets me know what I need to fix (and will detect regressions)

Bug 1378848 - Crypt::OpenPGP + Crypt::Random breaks when /dev/random is slow/unavailable

---

.perltidyrc

previously, the perltidyrc was written with the original recommendations of the
upstream bugzilla project. The style used there is... inconsistent at best. For
a while now, I've been using perltidy -pbp and telling others to do the same for
new code. However there are two exceptions to -pbp that are widely useful:
1. line length can be up to 120.
2. brace vertical tigntness is turned off.
This means that there is always a newline after the { in a multi-line brace
construct.

replace perltidyrc with on that specifies -pbp with two exceptions

---

.circleci/config.yml
.editorconfig
Bugzilla/Install/Localconfig.pm
Dockerfile
README.rst
docker_files/init.pl
extensions/BMO/Extension.pm
t/901-secure-mail-loop.t

This is the first (working) iteration of a configuration that allows
CircleCI to build 'bmo' docker images that are runnable.
Some other changes were required for this:
1. The base image used in Dockerfile was changed from centos:6.7 to
mozillabteam/bmo-base:slim.
This is a new version of (github) mozilla-bteam/docker-bmo-base
which is much smaller, and includes all the system RPMs and other
bits that our bmo Dockerfile expects.
2. init.pl mistakenly had '--no-assets' which is not currently a checksetup.pl
option.
3. 901-secure-mail-loop.t (which checks for an infinite loop) had
to have its timeout increased because CircleCI sometimes is quite slow.
4. version.txt // __version__ now includes build information from CircleCI
environmental variables
5. editorconfig knows about yml files now. …

Bug 1380531 - Write initial CircleCI configuration for BMO

---

Bugzilla/User.pm
Bugzilla/Util.pm
t/extract-nicks.t

Changed up the regex to match a much wider arrange of characters -- all letters, numbers,
and the symbols |._-
Also ignores 5:30 (or other timezones in people's realnames)

Bug 1378873 - user autocomplete no longer works for some strings

---

extensions/PhabBugz/lib/Util.pm

The `public` value, along with env var config, allows for truly public revisions.

Bug 1385947 - Make revisions fully public

---

.circleci/config.yml

I forgot to do this -- this makes it so only 'master' is pushed to 'latest'.
Later we will support other branches (and tags)

nit: only push to latest for the master branch

---

extensions/PhabBugz/lib/WebService.pm
extensions/PhabBugz/template/en/default/hook/global/user-error-errors.html.tmpl

Phabricator will need this endpoint to validate whether a given BMO account ID has permission to view a given BMO bug ID.
To test, comment out the `ThrowUserError('unauthorized_user') unless $user->login eq PHAB_BMO_USER_EMAIL;` line and use cURL to check visibility of public and private bugs:
```
curl -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-Bugzilla-API-Key: {api_key}' http://bmo-web.vm/rest/phabbugz/check_bug/{bugid}/{userid}
```

Bug 1389372 - Add REST API endpoint to validate whether a BMO user ID can see a given BMO bug

---

.circleci/config.yml

need to use a newer version of bmo-slim, which includes git. Without git, the "native" circleci is used which has a lot of bugs.

use mozillabteam/bmo-slim:20170818.1

---

Bugzilla/Config/Common.pm
Bugzilla/Config/GroupSecurity.pm
extensions/AntiSpam/lib/Config.pm
extensions/BMO/Extension.pm
extensions/EditComments/Extension.pm
extensions/PhabBugz/lib/Util.pm
extensions/Push/lib/Connector/Phabricator.pm
extensions/RestrictComments/lib/Config.pm

- This change will update the subscriber list of the revision when assignee, qa_contact, or cc list members   change since any of those will allow access to the bug.
- I switched to using subscribers.set instead of add in the Conduit API call which will overwrite whatever the current subscriber list is. This works well except in the case where someone adds themself as a subscriber in Phabricator instead of as a CC on the bug.
- TODO: we need to check the group changes in the push connector data to see if the groups actually changed and if not, then just do the subscribers change only. Right now it will create a new custom policy even if groups have not changed. This pollutes the change history of the revision needlessly.

Bug 1396957 - Synchronize CC list on security bugs over to revisions as subscribers

---

Bugzilla/ModPerl/StartupFix.pm
mod_perl.pl

The code in mod_perl.pl is executed twice. mod_perl does this to "make sure graceful restarts work".
It isn't clear that this is useful, since we don't use graceful restarts (which are not recommended with apache / mod_perl anyway) and it costs performance.
But more importantly it makes sanitizing %ENV more complicated than it needs to be.
This patch uses a source filter which clears out the rest of the mod_perl.pl during the first apache restart (when restart_count < 2). It includes a warning message so that this won't be a weird to debug problem in the future. Although I doubt it will, since I'm getting the hell off of apache as soon as we're out of scl3.)

Bug 1405011 - Prevent code in mod_perl.pl from executing twice

---

.circleci/config.yml
Bugzilla/Install/Filesystem.pm
Bugzilla/Install/Localconfig.pm
Bugzilla/ModPerl/StartupFix.pm
checksetup.pl
httpd/httpd.conf
mod_perl.pl
scripts/entrypoint.pl

This includes a patch from #256 which should land first.

Bug 1404092 - Bugzilla->localconfig should directly use environmental variables and ignore the localconfig file

---

js/field.js

Bug 1405754 - Autocomplete failing at random for some nicks (including, and especially bz)

---

t/001compile.t

This should make tests finish much quicker.
The code is already going to be compiled by other tests, and so most of the time this test is not useful.

no bug - avoid running compile tests in CI

---

scripts/generate_bmo_data.pl

For testing #291, we need to add the cf_due_date field. This adds the BMO product (which is one of the limited set of products that has the due date) and the cf_due_date as well.
It also adds machinery for adding new custom fields.
Note we have dozens of custom fields in prod that are not in the test env.
To test this, run the typical vagrant command then then 'vagrant ssh web' and run:
```bash
perl scripts/generate_bmo_data.pl vagrant@bmo-web.vm
```

no bug - add bmo product and cf_due_date to testing data set

---

extensions/BugModal/template/en/default/bug_modal/field.html.tmpl

Fix [Bug 1424787 - Due Date on bug modal is 1 day ahead](https://bugzilla.mozilla.org/show_bug.cgi?id=1424787)
* Use the default `html` filter in the same way as the hidden `<input>` field for the due date.
* Enclose the value in the `<time>` element.
* I have added the custom field locally but can't find on bug pages, so not tested this yet actually.

Bug 1424787 - Due Date on bug modal is 1 day ahead

---

extensions/BugModal/web/bug_modal.js

Errors reported on the console as datetimepicker is not defined (988a42a).

Bug 1424940 - Removing datetimepicker residue (followup)

---

js/comments.js
js/global.js
skins/standard/global.css

Fix [Bug 905763 - Fix named anchors in various pages so that the Sandstone theme header can be set to a fixed position](https://bugzilla.mozilla.org/show_bug.cgi?id=905763)
* Apply the fixed header + comment focus workaround (added in #289) to any page
* Enable [smooth scroll](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) for a better experience
* Use ECMAScript 6+, notably [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) 🎉

Bug 905763 - Fix named anchors in various pages so that the Sandstone theme header can be set to a fixed position

---

js/global.js

Follow up [Bug 905763 - Fix named anchors in various pages so that the Sandstone theme header can be set to a fixed position](https://bugzilla.mozilla.org/show_bug.cgi?id=905763) / #301
@dklawren has mentioned on IRC that a focused comment sometimes goes under the new global header when the page is loaded. This extends the `setTimeout` timer in JS a little bit to try fixing the issue.

Bug 905763 follow-up - Make sure focused comment will always be displayed under global header

---

.circleci/config.yml
Bugzilla/Extension.pm
Bugzilla/Template/PreloadProvider.pm
Dockerfile
Makefile.PL
mod_perl.pl
vagrant_support/bashrc

This patch adds an environmental variable USE_NYTPROF, that when set causes the apache config to load Devel::NYTProf::Apache. Profiles are stored in the data directory and get relatively unique names (per request).
Additionally, we now pass the full filename to PreloadProvider, and we begin source code lines
at line 1, both of which prevent warnings in Devel::NYTProf.

Simplify using Devel::NYTProf

---

Bugzilla/Sentry.pm
Bugzilla/Template.pm

It's hard to get a single accurate number for this change, but this change
is good:
Most noticeable here:
spent 46.4ms Bugzilla::Template::Plugin::Hook::process
spent 72.2ms  Bugzilla::Template::Plugin::Hook::process
Before:
After:

Bug 1427230 - Avoid loading CGI::Carp, which makes templates slow.

---

js/global.js
template/en/default/account/prefs/sessions.html.tmpl

Fix [Bug 1426673 - The logout link cannot be found as what Sessions page says](https://bugzilla.mozilla.org/show_bug.cgi?id=1426673)
* Show the fallback image on the Account menu if loading of Gravatar is blocked
* Tested with the Ghostery extension and Firefox's built-in Tracking Protection (strict mode)

Bug 1426673 - The logout link cannot be found as what Sessions page says

---

extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/Revision.pm
extensions/PhabBugz/lib/Util.pm
extensions/PhabBugz/lib/WebService.pm
extensions/Push/lib/Connector/Phabricator.pm

Also had to make some other refactor to make this work properly so apologize for the extra length.

 Bug 1426518 - Revisions can optionally not have a bug id so we need to make it optional in the type constraints of Revision.pm

---

template/en/default/global/header.html.tmpl

The `<meta>` element declaring the encoding must be inside the `<head>` element and **within the first 1024 bytes** of the HTML as some browsers only look at those bytes before choosing an encoding.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset

Bug 1428166 - Move <meta charset> to start of <head>

---

extensions/BugModal/web/bug_modal.js
extensions/BugModal/web/common_bug_modal.js
js/global.js
template/en/default/bug/navigate.html.tmpl

Fix [Bug 1427800 - Wrong anchor scrolling with old UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1427800)
* This function `scroll_element_into_view` is actually no longer unnecessary since #329 solved the overlapping issue, so I'll keep it to adjust the scroll position.
* For forward compatibility, I've added the support for [`<div role="feed">`](https://www.w3.org/TR/wai-aria-1.1/#feed) which could be the new scroll container of the comments.

Bug 1427800 - Wrong anchor scrolling with old UI

---

.editorconfig

I think 2 space indentation is common for CSS and JavaScript files these days. 4 spaces are too much for me.
* [Google Style Guides](https://google.github.io/styleguide/)
* [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript)
* [Mozilla Coding Style Guide](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style)
* [Why is two-space tab indent becoming the standard?](https://www.reddit.com/r/javascript/comments/5rjrcy/why_is_twospace_tab_indent_becoming_the_standard/)

no bug - Update editorconfig to use 2 space indentation for CSS and JavaScript

---

extensions/Review/web/js/badge.js
skins/standard/global.css
template/en/default/request/queue.json.tmpl

Fix [Bug 1429076 - Can we have a lock icon for requests in security-sensitive bugs in Requests Quick Look Dropdown?](https://bugzilla.mozilla.org/show_bug.cgi?id=1429076)
Sure we can!

Bug 1429076 - Can we have a lock icon for requests in security-sensitive bugs in Requests Quick Look Dropdown?

---

skins/standard/global.css

Fix [Bug 1429220 - Issues with the new fixed header implementation](https://bugzilla.mozilla.org/show_bug.cgi?id=1429220)
Scroll containers are `#header` and `#bugzilla-body` so `<body>` should not scroll. Actually `#header` should not scroll either. This issue will be solved once the site gets responsive design.

Bug 1429220 - Issues with the new fixed header implementation

---

extensions/Review/web/js/badge.js

Fix [Bug 1429194 - Clicking requests icon gives "Loading... " but never actually completes](https://bugzilla.mozilla.org/show_bug.cgi?id=1429194)
The regex will fail when any requester has their user name like "<:john>" or they don't have any real name set. This fixes both cases. Later I'll create a helper function to extract real name, nick name and email.

Bug 1429194 - Clicking requests icon gives "Loading... " but never actually completes

---

skins/standard/global.css

Fix [Bug 1429290 - Bugs now display too wide to fit in my window; reading bugs is much harder](https://bugzilla.mozilla.org/show_bug.cgi?id=1429290)
* Give some narrower style to the fixed header: hide menu labels
* The modal bug detail pages won't get a horizontal scrollbar on window size > 920px

Bug 1429290 - Bugs now display too wide to fit in my window; reading bugs is much harder

---

Bugzilla/CGI.pm

patch for https://bugzilla.mozilla.org/show_bug.cgi?id=1426414  
I decided to only preload woff2, as those should be font used by most mondern browsers I guess.
sending all fonts in all formats doesnt sound like a good idea to me.
I wasnt able to test this locally as I didnt have a working bmo setup on my dev box.
could this be deployed somewhere so we can test it?

Bug 1426414: Send preload headers for webfonts

---

extensions/Review/web/js/badge.js

This is step 2 of https://en.gravatar.com/site/implement/hash/
My email address has uppercase so Gravatars for me are currently broken in this UI. The Perl BMO code already calls [`lc`](https://github.com/mozilla-bteam/bmo/blob/e655f5133b4dd5c5d6f253069767db75c64eb349/extensions/Gravatar/Extension.pm#L34).

Lowercase the email address before generating the MD5 for Gravatar

---

extensions/Review/web/js/badge.js

Fix [Bug 1430495 - Make loading of Requests dropdown faster](https://bugzilla.mozilla.org/show_bug.cgi?id=1430495)
* Use the same technique as Firefox's tab warming to load the Requests dropdown content faster.

Bug 1430495 - Make loading of Requests dropdown faster

---

template/en/default/index.html.tmpl

Fix [Bug 1429688 - focus Search Bugs box by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1429688)
Automatically focus the Quick Search box on the home page when the page is loaded by simply adding the `autofocus` attribute.

Bug 1429688 - focus Search Bugs box by default

---

request.cgi

`@data = @$result` makes a copy of an array. Instead of doing that, we just use the array ref (and rename `$result` to `$data`)

Bug 1431294 - requests.cgi - allocate less memory

---

Bugzilla/Template.pm
extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
template/en/default/bug/edit.html.tmpl
template/en/default/list/table.html.tmpl

Fix [Bug 1428270 - Unwrappable content in summary can cause top buttons to bleed out of main content box](https://bugzilla.mozilla.org/show_bug.cgi?id=1428270)
* Add a simple template filter for inserting [`<wbr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) elements to camel and/or snake case words, like what I'm doing on [fxsitecompat.com](https://github.com/fxsitecompat/www.fxsitecompat.com/blob/master/layouts/docs/single.html#L32)
* Use the filter for the bug summary on the bug details and search results
* It can also be used for other pages but those are good starting points!

Bug 1428270 - Unwrappable content in summary can cause top buttons to bleed out of main content box

---

extensions/Review/template/en/default/hook/global/header-badge.html.tmpl
extensions/Review/web/js/badge.js

Fix [Bug 1429888 - See All link in Requests dropdown should show results grouped by flags as before](https://bugzilla.mozilla.org/show_bug.cgi?id=1429888)
* The link should show results grouped by flag/type as before.
* The background fetch request should still be grouped by requestee so the response will be ordered by date, saving some time to reorder the results with JavaScript.

Bug 1429888 - See All link in Requests dropdown should show results grouped by flags as before

---

extensions/SecureMail/template/en/default/pages/securemail/help.html.tmpl

StartCom is untrusted, should not be mentioned as a certificate provider on Secure Bug Mail help page. This patch removes the reference.

Bug 1424363 - securemail help page recommends getting a certificate from StartCom

---

scripts/sendmail.pl

To review this, @Micheletto can you verify this by testing it against the dev stack?
1. Copy the one file from this patch to the admin container
2. set mail_delivery_method in data/params to Test
3. run:
```bash
echo -e "To: robot@example.com\r\nFrom: bugzilla@example.com\r\nSubject:\r\nBatman\r\n\r\nanananananananana" | perl scripts/sendmail.pl
```
If the jobqueue daemom isn't running in the stack yet, run it once manually:
```bash
perl jobqueue.pl -d -f onepass
```
After that, you should see something like this in data/mail.testfile:
```
From - Wed, 07 Feb 2018 04:45:02 -0800
To: robot@example.com
From: bugzilla@example.com
Subject: Batman
X-Bugzilla-URL: http://bmo-web.vm/
Auto-Submitted: auto-generated
MIME-Version: 1.0
Date: Wed, 07 Feb 2018 04:45:02 -0800
X-Generated-By: …
```

Bug 1435735 - Add script to add email job to jobqueue

---

extensions/Needinfo/Extension.pm

This fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1211377 for me, in local testing in vagrant. It's only 4 lines of perl but it's probably terrible. Please tell me how to make it sufficient so we can ship this and I can stop wanting to throw my computer out of the window when updating security bugs.

Bug 1211377 - needinfo from someone not in sec group shows warning message even when bug is being removed from sec group

---

extensions/PhabBugz/lib/User.pm

This is the User.pm module only for now. I have patches that add support for using the new module for loading of phabricator users instead of the utility methods in Util.pm. I felt review would be easier if I made smaller PRs for each of those instead of one large PR. Please review and once landed, I will create PRs for other parts of the code to utilize the new class module.
dkl

Bug 1437383: Create User.pm PhabBugz class for loading of a user object from phabricator

---

Bugzilla/Install/Localconfig.pm
Bugzilla/ModPerl.pm
Bugzilla/ModPerl/BasicAuth.pm
ses/index.cgi
template/en/default/admin/users/bounce-disabled.txt.tmpl
template/en/default/email/ses-complaint.txt.tmpl
template/en/default/setup/strings.txt.pl
vagrant_support/checksetup_answers.j2

Adds a /ses/ endpoint, protected by http basic auth, for handling ses
notifications.
SES must be configured with SNS topics for bounce and complaint that
both https post to the /ses/ endpoint.
Credentials for this endpoint must be provided in localconfig.

Bug 1438206 - Process SES email bounces properly

---

Bugzilla/Constants.pm
Bugzilla/Install/Filesystem.pm

Add a confdir option to bz_locations() that is similar to data/ but intended to be used for configuration files. This can replace docker_support (and later, perhaps, vagrant_support)

Bug 1437646 - Part 1 - Add confdir to Bugzilla::Constants

---

extensions/MyDashboard/template/en/default/pages/mydashboard.html.tmpl
extensions/MyDashboard/web/styles/mydashboard.css

Fix [Bug 1429621 - Add Saved Searches to My Dashboard](https://bugzilla.mozilla.org/show_bug.cgi?id=1429621)
Add the Saved Searches section to the bottom of the My Dashboard page so people can have a plain list of their searches as seen on the removed global footer.

Bug 1429621 - Add Saved Searches to My Dashboard

---

Bugzilla/Template.pm

Fix [Bug 1433299 - Link in summary is broken](https://bugzilla.mozilla.org/show_bug.cgi?id=1433299)
Sorry I couldn't work on this sooner but here's the patch for my regression. I'm not a regex guru so might be wrong. This solution is based on [this Stack Overflow thread](https://stackoverflow.com/q/18621568). Tested locally.

Bug 1433299 - Link in summary is broken

---

Bugzilla/DaemonControl.pm
Dockerfile

This PR adds a module that exports functions which return [Futures](https://metacpan.org/pod/Future) that either start daemons (`run_httpd()`, `run_cereal()`),
check for running services (`assert_httpd()`, `assert_database()`, `assert_selenium()`).
It also has functions that return callbacks to assist writing functions similar to the above run_() functions.

Bug 1437646 - Part 2 - Add Bugzilla::DaemonControl

---

extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/Project.pm
extensions/PhabBugz/lib/Revision.pm
extensions/PhabBugz/lib/Util.pm
extensions/Push/lib/Connector/Phabricator.pm

Phabricator's Herald has a "Secure Email" rule and Phabricator sends a
restricted email notification if a revision belongs to the newly created
"secure-revision" group project.
With this patch Bugzilla will automatically assign a secure revision to
the "secure-revision" group project.
Additionally:
The get_project_phid is modified and is now caching the response in
memcached.

Bug 1440239 - PhabBugz - Assign a secure-revision.

---

Bugzilla/Memcached.pm

This adds TRACE-level logging to _set() and _get(), to help @Micheletto debug something in the new env. 
By default this will have almost no impact -- TRACE is not logged by default. Of course it's not free, but this is fine I think. :)

Bug 1442099 - Add memcached tracing to help debug weirdness in cloud env

---

extensions/BMO/template/en/default/global/choose-product.html.tmpl
extensions/BMO/web/styles/choose_product.css

Fix [Bug 1419973 - Modify product selector layout on Browse and Enter Bug pages](https://bugzilla.mozilla.org/show_bug.cgi?id=1419973)
* Update the markup to ditch the table layout
* Use columns for the product selector on the [Browse](https://bugzilla.mozilla.org/describecomponents.cgi) and [New Bug](https://bugzilla.mozilla.org/enter_bug.cgi) pages so more/all products can be displayed at once.

Bug 1419973 - Modify product selector layout on Browse and Enter Bug pages

---

extensions/Review/web/js/badge.js
request.cgi
template/en/default/global/header.html.tmpl
template/en/default/request/queue.json.tmpl

Fix [Bug 1429344 - Review requests in requests dropdown should link to MozReview or GitHub instead of Bugzilla details page](https://bugzilla.mozilla.org/show_bug.cgi?id=1429344)
* Retrieve `attachments.mimetype` from DB as `attach_mimetype`
* Retrieve `attachments.ispatch` from DB as `attach_ispatch` instead of `ispatch` for consistency (this field is not used in other templates so the change should be safe)
* Treat MozReview and Phabricator requests as patches
* Support GitHub pull requests and Google Docs as well
* Link directly to those external sites
* For regular patches, link to the Splinter Review page if available

Bug 1429344 - Review requests in requests dropdown should link to MozReview or GitHub instead of Bugzilla details page

---

CONTRIBUTING.md

@emceeaich - can you review and make suggestions for the FIXME parts about the code of conduction section? I've copied this from Servo's, but changed it from refering to Rust's Code of Conduct to The Mozilla Participation Guidelines. 
@justdave what is the canonical URL for referencing the bugzilla developers list?

no bug - add a contributing.md

---

Bugzilla/CGI.pm

This is just removing some dumb code that turns an array into a hash using (shift, shift) and a then a hash into an array using unshift... Originally [Bug 1136125](https://bugzilla.mozilla.org/show_bug.cgi?id=1136125).

Bug 1443057 - Backport 1136125 to bmo - Reduce memory usage of Bugzilla::CGI->send_cookie()

---

Bugzilla/Logging.pm

So this function is called as a log filter in the conf/log4perl-*.conf files. So it needs to be defined before those files are loaded.

Bug 1443049 - is_interactive() must be declared before log4perl config is loaded

---

Bugzilla/DaemonControl.pm
t/daemon-control-catch-signal.t

we need to remove the signal watcher after the future is marked as done.
It's not legal to call ->done() on a future more than once.

Bug 1441181 - Step 7 - Fix bug in catch_signal()

---

extensions/Splinter/template/en/default/hook/request/queue-after_column.html.tmpl

Fix [Bug 1444088 - review link for patches on the requests page no longer shows up](https://bugzilla.mozilla.org/show_bug.cgi?id=1444088)
This is a fallout from #372. I changed `ispatch` to `attach_ispatch` but forgot to look at hooks linked from the [request templates](https://github.com/mozilla-bteam/bmo/tree/master/template/en/default/request) and this is the only one needs to be updated.

Bug 1444088 - review link for patches on the requests page no longer shows up

---

Bugzilla/JobQueue/Runner.pm
jobqueue.pl

(Originally #439, which was accidentally merged to the wrong branch)
Documentation of the things this is using:
[Future::Utils::fmap_void is described here](https://metacpan.org/pod/Future::Utils#APPLYING-A-FUNCTION-TO-A-LIST).
The main loop of the master is basically this future:
```perl
fmap_void { $self->run_worker("work") }
concurrent => $jobs,
generate   => sub { !$signal_f->is_ready };
```
So until the `$signal_f` future is ready (done, canceled, or failed), the fmap_void ensures that least `$jobs` of the `run_worker()` futures are pending. The result of `fmap_void` is a single future.
It's `fmap_void` because it does not collect the (potentially infinite) number of generated `run_worker()` futures.

Bug 1441181 - Step 6 - Add concurrency 

---

.circleci/config.yml
Dockerfile
Makefile.PL
mod_perl.pl

So this patch adds Linux::Smaps as a optional feature dependency,
and it also makes Linux::Pdeathsig the same. It then includes all linux_ features into the 'bmo' feature...
What this means is that Linux:: modules are required for bmo but if you want to run this locally on OSX it will still work.
If Linux::Smaps is not found, and we're running on linux, we set a huge apache_size_limit and issue a warning.

Bug 1445700 -  apache_size_limit should be 800_000 when Linux::Smaps is not installed. 

---

Bugzilla/CGI.pm

This does look bad, but we've had this code in upstream bugzilla for a while. And the warnings tend to be very annoying. Currently this is keeping us on an older version of CGI.pm

Bug 1443058 - Backport 1087400 to bmo - CGI 4.05 throws tons of "CGI::param called in list context" warnings

---

Bugzilla/Template.pm
checksetup.pl

This seems to make bugzilla-dev happy.
I've verified other files created by checksetup end up with correct permissions (e.g. version.json)

Bug 1446156 - mkdir template_cache: Permission denied

---

extensions/BMO/template/en/default/pages/user_activity.html.tmpl
extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
extensions/InlineHistory/template/en/default/hook/bug/comments-aftercomments.html.tmpl
template/en/default/bug/activity/table.html.tmpl

Throughout bugzilla we normally remove the host of an email address
when displaying the page to a user that is not authenticated. This
prevents spam bots and such from scrapping people's emails.
This was not being done for mentor email addresses in the activity
stream and bug history. See Bug 1440328.
This commit properly filters the mentor email addresses in all places
where we commonly filter emails.
Filtering in `user_activity.html.tmpl` and `activity_stream.html.tmpl` fixes the immediate problem mentioned in the bug, but I've also filtered in `comments-aftercomments.html.tmpl` and `table.html.tmpl` since those areas looked similar. Please let me know if I should revert those changes.

Bug 1440328 - Obfuscate mentor email for users that aren't logged in

---

Bugzilla/DB.pm
Bugzilla/Install/Localconfig.pm
template/en/default/setup/strings.txt.pl

Adds a localconfig option to specify a username and password to use when connecting to the shadow db. If not provided, the default dbuser an dbpass will be used.
Also fixes a typo with setting the shadowport and shadowsock.

add shadowdb username and password in localconfig param override

---

Bugzilla/Mailer.pm

Add a `References` header to emails for new bugs to allow threading in situations where our `Message-ID` is overwritten (eg. SES).

Bug 1448681 - Bugmail Message-ID header format changed without changing In-Reply-To/References, breaking threading

---

extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/Revision.pm
extensions/PhabBugz/lib/Util.pm

…entire commit message, not just first line

Bug 1440829 - Bugzilla comment for Phabricator commit should include entire commit message, not just first line

---

Bugzilla.pm

[release tag](https://github.com/mozilla-bteam/bmo/tree/release-20180328.1)
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1448681" target="_blank">1448681</a>] Bugmail Message-ID header format changed without changing In-Reply-To/References, breaking threading</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1440829" target="_blank">1440829</a>] Bugzilla comment for Phabricator commit should include entire commit message, not just first line</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1449413" target="_blank">1449413</a>] Refactor circleci container building stuff</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1449156" target="_blank">1449156</a>] …

bump version to 20180328.1

---

extensions/PhabBugz/lib/Feed.pm

Currently, we're sending the "User removed from revision" comment when
the Accept flag has been removed from a revision. This could happen in a
number of use cases:
1. The reviewer resigned from being a reviewer.
2. The reviewer has been removed from reviewers list.
3. Someone (author, reviewer) removed acceptance of the revision by changing
its status to "Needs Review".
This patch is sending a "flag is deactivated" or "reviewer removed from
revision" depending on the current status of the reviewer.
Test Plan:
Accept a revision.
Change the revision to "Needs Review".
Check the bug comment.
Accept the revision.
Remove the user from reviewers list.
Check the bug comment.

Bug 1441063: Fix the unaccepted revision comment (PhabBugz)

---

template/en/default/email/new-api-key.txt.tmpl

When a user logs in to MozReview or Phabricator for the first time an api key is created for them. Because the api key is created in the background, the user may be alarmed when they next check their email and see that an api key was created on their Bugzilla account.
This PR updates our email to inform the user if one of our review tools was responsible for creating the api key.
This was tested with the auth delegation test shim in https://bugzilla.mozilla.org/show_bug.cgi?id=1447028:

Bug 1200695 - API-key-creation emails should reflect if the action was a result of auth delegation

---

Bugzilla/Error.pm

These changes make it so errors in sanity tests don't fail without a database present.
To test this, simply try running 001compile.t without having run Makefile.PL first. You should get a reasonable error (about MYMETA.json not existing, I think).
@upasana-me can you test this? I think without the patch you get the error you reported.

Bug 1441244 - prevent compounding error messages in tests

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1448681" target="_blank">1448681</a>] Bugmail Message-ID header format changed without changing In-Reply-To/References, breaking threading</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1440829" target="_blank">1440829</a>] Bugzilla comment for Phabricator commit should include entire commit message, not just first line</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1449413" target="_blank">1449413</a>] Refactor circleci container building stuff</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1449156" target="_blank">1449156</a>] Bugzilla::Memcached should use smaller timeouts and ping servers at instantiation …

bump version to 20180330.1

---

Bugzilla/JobQueue.pm

docker-compose up --build produces a lot less output with this (tested).

Bug 1450283 - JobQueue should treat "no jobs" as a trace-level message, and all other logs as info

---

js/instant-search.js

```
When an API token is seen by JSON-RPC, it will attempt to authenticate
it, including blank tokens (empty strings). Thus, avoid passing an
empty string in the first place.
The pattern to pass an empty string if the absence of
BUGZILLA.api_token is the most common way to include the
Bugzilla_api_token in the JSON-PRC requests. However, most places
which pass a token to JSON-RPC in JavaScript are in contexts where a
user is expected to be logged in, and this is not the case for instant
search.
Although this could have been fixed by patching
Bugzilla::Auth::Login::Cookie::get_login_info to treat empty API
tokens as if none were given, this method was chosen, as this is also
the approach used in the ProdCompSearch extension (where a login
session also does not need to be required), and to …
```

Bug 1450920 - Don't pass blank API token to JSON-PRC in instant search

---

Bugzilla/Mailer.pm

to populate the badhosts bloomfilter for testing:
```bash
perl scripts/bloomfilter-populate.pl badhosts < list-of-hostnames.txt
```

Bug 1451416 - Bugzilla sometimes sends emails to accounts when it shouldn't

---

Bugzilla/WebService/Bug.pm
Bugzilla/WebService/Server/REST/Resources/Bug.pm
docs/en/rst/api/core/v1/bug.rst

Adds a new endpoint that allows users to search for possible duplicates of bugs via bug id or a summary.

Bug 1421110 - Add REST API endpoint for /bug/possible_duplicates

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1450283" target="_blank">1450283</a>] JobQueue should treat "no jobs" as a trace-level message, and all other logs as info</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1450920" target="_blank">1450920</a>] Instant Search doesn't work when not logged in</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1447028" target="_blank">1447028</a>] Add auth delegation test script</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1446431" target="_blank">1446431</a>] Allow Baseline scan to ignore forms that dont need CSRF Tokens</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1450791" target="_blank">1450791</a>] SES handler needs to support both "event" and "notification" …

bump version to 20180412.1

---

extensions/OpenGraph/template/en/default/hook/global/header-start.html.tmpl

So we need to html escape the result of the txt filter.
Oops.

Bug 1453697 - ensure error_message is escaped in opengraph description

---

extensions/BMO/template/en/default/email/bugmail.html.tmpl

Adds a link to unsubscribe from all emails in the html format of the bugmail template. The plaintext format already contained a link and message to configure email settings.
Running a diff between the `email/bugmail.html.tmpl` in the BMO extension vs the default template shows that there are a lot of changes between these two. So at this time it seems easier to keep both templates. **Question:** Should I also add an unsubscribe link to the default template since this is a generic improvement?

Bug 1450325 - add unsubscribe link to html bug email template

---

extensions/BMO/template/en/default/account/create.html.tmpl

On the right the checkbox would be in a weird place if text had
overflowed on a smaller screen. Being on the left is also standard
practice.

Bug 1451599 - Move guidelines checkbox on signup page to the left

---

extensions/BugModal/web/bug_modal.js

- When you input (type or copy paste) into the comment box, we save the text of the box into localStorage.
- When the bug page loads, or tab is switched to (if 2 tabs with the same bug are open) we populate the comment box with the saved text, if it exists.
- When you save a bug we clear the localStorage.
- This solves the problem mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1438205 and just in general allows people to start typing a comment, close the page, and come back to it tomorrow.

Bug 1438205 - Preserve comments in progress across page reloads

---

extensions/BMO/template/en/default/pages/attachment_bounty_form.html.tmpl

Labels the additional credit fields as Twitter and URL.
The attachment itself remains the same, but, people will likely begin putting better values there as we would want.

Bug 1455772 - Label bug bounty form credit fields

---

extensions/BugModal/web/bug_modal.css

Prior to this commit, the only indication that a comment was private was the small "Private" tag in the comment header. This commit restores the red font color to private comments and adds a small dashed border for those that have trouble seeing the color red.

Bug 1373280 - Highlight private comments in new bug modal UI

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1450325" target="_blank">1450325</a>] Update email templates with instructions for unsubscribing from all emails</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1451599" target="_blank">1451599</a>] Checkbox for agreement terms at create account page should be on the left side</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1438205" target="_blank">1438205</a>] Preserve comments in progress across page reloads</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1452531" target="_blank">1452531</a>] PhabBugz code should add allow visibility to reviewers when creating custom policies</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1440828" target="_blank">1440828</a>] …

bump version to 20180426.4

---

Bugzilla/CGI.pm
extensions/OrangeFactor/Extension.pm
extensions/OrangeFactor/template/en/default/hook/bug/edit-after_custom_fields.html.tmpl
extensions/OrangeFactor/template/en/default/hook/bug_modal/edit-details_rhs.html.tmpl
extensions/OrangeFactor/web/js/orange_factor.js

Upgrades the OrangeFactor extension to use the new TreeHerder failures page and api, since https://brasstacks.mozilla.com/orangefactor/ will be decommissioned soon.
The functionality remains the same as before.

Bug 1453759 - Port OrangeFactor extension to treeherder

---

Bugzilla/Install/Localconfig.pm

Some default values are tainted. We untaint environmental variables already, so we should untaint these too.

no bug - untaint default values in localconfig

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1459336" target="_blank">1459336</a>] feed daemon skips setting r+ for accepted revision if the same user already has a flag set even if flag is status of ?</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1460466" target="_blank">1460466</a>] Phab bot does not create r+ for acceptance when there are still blocking reviewers</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1440086" target="_blank">1440086</a>] Refactor PhabBugz extension code to use new User.pm module for better type checking</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1458664" target="_blank">1458664</a>] Feed daemon when adding or updating a new project in Phabricator, it should fix permissions and also make …

bump version to 20180523.1

---

extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/WebService.pm
extensions/PhabBugz/template/en/default/hook/global/user-error-errors.html.tmpl

To test this you will need to perform some administrative steps as admin on the phabricator instance.
1. More Applications -> Harbormaster -> Manage Build Plans -> Create Build Plan
2. Description: "Wait Until Bugzilla Updates Revision"
3. Create
4. Add Build Step
5. Make HTTP Request
6. URI: "http://bmo.test/rest/phabbugz/build_target/${buildable.revision}/${target.phid}"
7. HTTP Method: "POST"
8. Create New Credential
9. Name: "Phabricator Bot Credential"
10. Login/Username: "phab-bot@bmo.tld"
11. Password: <phab-bot@bmo.tld api key from bmo.test>
12. Create Credential
13. When Complete: "Wait for message"
14. Phabricator -> Herald -> Create Herald Rule
15. New Rule for: "Differential Revisions" and Continue
16. Rule Type: "Global" and Continue
17. Rule Name: "Wait Until Bugzilla …

Bug 1462685 - Use Phabricators Draft functionality to allow sending of initial revision email after BMO has updated the policies

---

Bugzilla.pm

[release tag](https://github.com/mozilla-bteam/bmo/tree/release-20180530.1)
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1462685" target="_blank">1462685</a>] Use Phabricators Draft functionality to allow sending of initial revision email after BMO has updated the policies</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1464226" target="_blank">1464226</a>] quicksearch can't search for "Resolution:---"</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1464312" target="_blank">1464312</a>] Write script to undo the INACTIVE changes on bugs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1465225" target="_blank">1465225</a>] New changes for draft revisions can miss …

bump version to 20180530.1

---

static/metricsgraphics/socorro-lens.html

Fix [Bug 1466159 - crash graph is wrong](https://bugzilla.mozilla.org/show_bug.cgi?id=1466159)
White spaces in `location.search` are represented as `+` signs in this case, which have to be replaced with white spaces again. Tested locally.
Note: I think the code needs a refactoring with [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) and [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), but it’s a separate issue.

Bug 1466159 - crash graph is wrong

---

js/global.js

The error is dumped in the console while using the [Bugzilla Helper](https://bugzilla.mozilla.org/enter_bug.cgi?format=guided). I'm sure this doesn't cause any negative impact on the current UI, but it's a mistake in my code. Let's fix it.
```
SyntaxError: '#h=dupes%7CFirefox' is not a valid selector
```

no bug - Fix SyntaxError in global.js

---

extensions/BMO/template/en/default/bug/create/create-dev-engagement-event.html.tmpl

Fix [Bug 1465889 - form.dev-engagement-event field should be red instead of black](https://bugzilla.mozilla.org/show_bug.cgi?id=1465889)
Simply adding a missing `warning` class to the template. Tested locally.

Bug 1465889 - form.dev-engagement-event field should be red instead of black

---

extensions/BMO/template/en/default/global/choose-product.html.tmpl

The following footer is only for the [Enter Bug](https://bugzilla.mozilla.org/enter_bug.cgi) page, shouldn’t be on the [Browse](https://bugzilla.mozilla.org/describecomponents.cgi) page.
> Switch to the Bugzilla Helper | Custom bug entry forms
[Bug 1469689 - Remove Bugzilla Helper and custom bug entry form links from Browse page](https://bugzilla.mozilla.org/show_bug.cgi?id=1469689)

Bug 1469689 - Remove Bugzilla Helper and custom bug entry form links from Browse page

---

js/attachment.js
skins/standard/attachment.css
template/en/default/attachment/createformcontents.html.tmpl
template/en/default/global/header.html.tmpl

Some users complain about the Secure Connection Failed browser error when uploading too large attachment. It’s a server-side issue but can be avoided by adding a client-side simple size checker.
This change shows an accessible error message and prevents the form from being submitted unless the user selects a file smaller than the limit (10 MB on BMO).
[Bug 1469333 - Check attachment file size client-side and inform user of too large file before uploading it](https://bugzilla.mozilla.org/show_bug.cgi?id=1469333)

Bug 1469333 - Check attachment file size client-side and inform user of too large file before uploading it

---

Bugzilla/DB.pm
Bugzilla/DB/Mysql.pm
Bugzilla/DB/Oracle.pm
Bugzilla/DB/Pg.pm
Bugzilla/DB/Sqlite.pm
Bugzilla/JobQueue.pm

I'd like to use DBIx::Connector (in #585), so first let's remove the really weird stuff we do about subclassing DBI::db.

Bug 1461379 - refactor Bugzilla::DB to not subclass DBI

---

.circleci/config.yml
Bugzilla.pm
Bugzilla/DB.pm
Bugzilla/ModPerl.pm
Dockerfile
Makefile.PL
token.cgi

This should make it so there is only two connections to the DB per process.
This is related to mozilla/infosec-risk-management-bugzilla#13

Bug 1461379 - use DBIx::Connector to manage database connections

---

extensions/BugModal/web/bug_modal.js

Add a small but clear UI feedback for the Copy Summary button not to confuse users.
[Bug 1470275 - Copy Summary button should give some feedback](https://bugzilla.mozilla.org/show_bug.cgi?id=1470275)

Bug 1470275 - Copy Summary button should give some feedback

---

extensions/BMO/Extension.pm

Decode GitHub pull request diff properly.
[Bug 1470343 - GitHub PR diff is not decoded in UTF-8](https://bugzilla.mozilla.org/show_bug.cgi?id=1470343)
Notice that **Couldn’t copy bug summary** is displayed as expected, compared to the [current view](https://bugzilla.mozilla.org/attachment.cgi?id=8986913&action=edit).

Bug 1470343 - GitHub PR diff is not decoded in UTF-8

---

Bugzilla/Group.pm
Bugzilla/Object.pm

When working on #282 I kept encountering the fragility of our model system.
This fragility involves two things:
1) Extensions adding new columns to model objects
2) The use of those model objects in checksetup.
In particular, the SecureMail extension causes this problem because (at checksetup-time) we need to lookup certain Group objects.
Thus I propose to
1) allow model classes to take their list of columns from the informations schema (exposed via `bz_table_columns_real`)
2) Have Bugzilla::Group do this when being used in a commandline (e.g. checksetup) context.

Bug 1471044 - Allow some model classes to have dynamic column names  with class method DYNAMIC_COLUMNS

---

extensions/BugModal/web/bug_modal.js
extensions/BugModal/web/comments.js
extensions/BugModal/web/common_bug_modal.js
extensions/ProdCompSearch/web/js/prod_comp_search.js
js/comment-tagging.js
js/field.js
skins/standard/global.css

Fix the autocomplete dropdown lists displayed at a wrong, fixed position when the page is scrolled down. Given the fixed global header, these widgets has to be attached to the main scroll area instead of `<body>`. See the [README of the jQuery plug-in](https://github.com/devbridge/jQuery-Autocomplete) for the option details.
[Bug 1452096 - Some custom dropdown UI widgets stay fixed and don't move with scroll](https://bugzilla.mozilla.org/show_bug.cgi?id=1452096)

Bug 1452096 - Some custom dropdown UI widgets stay fixed and don't move with scroll

---

scripts/remove-non-public-data.pl
scripts/sanitizeme.pl

The only remaining issue with this script was that it would sometimes die about tables that were already dropped. This fixes that problem.

Bug 1457550 - Update scripts/remove-non-public-data.pl suitability for current BMO infrastructure.

---

extensions/BugModal/template/en/default/bug_modal/header.html.tmpl
extensions/BugModal/web/bug_modal.css
extensions/BugModal/web/bug_modal.js

Add a "new changes" indicator to the modal bug page, and automatically scroll down to those changes for faster browsing, as seen on Slack.
[Bug 1469023 - Show "new changes since (datetime)" indicator that links to unread changes/comments](https://bugzilla.mozilla.org/show_bug.cgi?id=1469023)

Bug 1469023 - Show "new changes since (datetime)" indicator that links to unread changes/comments

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1467297" target="_blank">1467297</a>] variable masks earlier declaration in Feed.pm in Phabbugz extension</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1467271" target="_blank">1467271</a>] When making a revision public, make the revision editable only by the bmo-editbugs-team project (editbugs)</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1468848" target="_blank">1468848</a>] Change presentation of show_bug.cgi urls to be /bug/ID or /bug/ALIAS.</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1456877" target="_blank">1456877</a>] Add a wrapper around libcmark_gfm to Bugzilla</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1468818" …

bump version to 20180627.1

---

Bugzilla/Attachment.pm
extensions/BMO/template/en/default/hook/attachment/createformcontents-mimetypes.html.tmpl
template/en/default/attachment/createformcontents.html.tmpl
template/en/default/attachment/show-multiple.html.tmpl

Fix [Bug 1471417 - Remove XUL from attachment Content Type options; add SVG to standard options; mark PDF viewable](https://bugzilla.mozilla.org/show_bug.cgi?id=1471417).

Remove XUL from attachment Content Type options; add SVG to standard options; mark PDF viewable

---

extensions/BugModal/web/bug_modal.css

The human-readable summary on a module header should be hidden when the module is open, because it basically shows duplicated info.
[Bug 1344080 - Module headers should be minified when the module is open](https://bugzilla.mozilla.org/show_bug.cgi?id=1344080)

Bug 1344080 - Module headers should be minified when the module is open

---

Bugzilla/Memcached.pm
Makefile.PL

Bug 1275545 Use Sereal for Cache::Memcached::Fast r=dylan

---

extensions/PhabBugz/lib/Revision.pm

…er syncing is currently broken on prod bmo

Bug 1472196 - Disable use of editbugs as edit policy since group member syncing is currently broken on prod bmo

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1471417" target="_blank">1471417</a>] Remove XUL from attachment Content Type options; add SVG to standard options; mark PDF viewable</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1344080" target="_blank">1344080</a>] Module headers should be minified when the module is open</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1469378" target="_blank">1469378</a>] Update feed daemon to only manage subscribers on a revision if the bug is private, otherwise leave it alone</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1469373" target="_blank">1469373</a>] Phabbugz fails with undefined error when phab user without linked BMO account accepts BMO linked revision</li>
<li>[<a …

bump version to 20180629.1

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1472326" target="_blank">1472326</a>] group member syncing is currently broken on production bmo</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1472755" target="_blank">1472755</a>] False positives on IP blocking logic</li>
</ul>

bump version to 20180703.1

---

Bugzilla/DB.pm
Bugzilla/Install/DB.pm
Bugzilla/User.pm
Bugzilla/WebService/Server/REST/Resources/User.pm
Bugzilla/WebService/User.pm
js/field.js

This optimizes the common case of username lookup to be fast at the expense of slightly different behavior.
For bare words consisting of ASCII characters, a prefix match against login_name and the new nickname field is attempted.
For words containing @, only the login_name is considered.
For words beginning with :, only the nickname is considered.
Multiple words, or non-ASCII characters will use a fulltext search against the realname field.
This means 'Mark Cote' will correctly find @markrcote. 
The time savings of this on bugzilla-dev appears to be about 600ms
Prod:
Dev:

Bug 1469911 - Make user autocompletion faster

---

Bugzilla/WebService/Server/REST/Resources/BugUserLastVisit.pm
docs/en/rst/api/core/v1/bug-user-last-visit.rst

* Add a missing REST API route `/bug_user_last_visit` which is [documented](https://bmo.readthedocs.io/en/latest/api/core/v1/bug-user-last-visit.html) and also available as JSON-RPC `BugUserLastVisit.get` and `BugUserLastVisit.update` methods (still used on non-modal bug pages and My Dashboard)
* Update the document to clarify the actual results
[Bug 1260096 - BugUserLastVisit api not working and throwing error code : 32614](https://bugzilla.mozilla.org/show_bug.cgi?id=1260096)
Open a modal bug page, and enter this in the browser’s console:
```javascript
bugzilla_ajax({ url: '/rest/bug_user_last_visit', type: 'GET' }, result => console.log(result));
bugzilla_ajax({ url: '/rest/bug_user_last_visit', type: 'POST', data: { ids: [1,2,3] } }, result => console.log(result));
```

Bug 1260096 - BugUserLastVisit api not working and throwing error code : 32614

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1473798" target="_blank">1473798</a>] Add and remove members of a phabricator project instead of setting exact list</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1474617" target="_blank">1474617</a>] conduit-suite phabricator local development instance missing some default configuration</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1476052" target="_blank">1476052</a>] Bugzilla mishandles diff attachments that are UTF-8 and contain U+FFFF</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1472961" target="_blank">1472961</a>] Copy Summary button should copy link as well</li>
</ul>

bump version to 20180717.1

---

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugmailFilter/template/en/default/account/prefs/bugmail_filter.html.tmpl

Just use the Unicode character to avoid double escaping. Tested locally.
[Bug 1474026 - Double HTML escaping in crash signature update](https://bugzilla.mozilla.org/show_bug.cgi?id=1474026)

Bug 1474026 - Double HTML escaping in crash signature update

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1473798" target="_blank">1473798</a>] Add and remove members of a phabricator project instead of setting exact list</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1474617" target="_blank">1474617</a>] conduit-suite phabricator local development instance missing some default configuration</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1476052" target="_blank">1476052</a>] Bugzilla mishandles diff attachments that are UTF-8 and contain U+FFFF</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1472961" target="_blank">1472961</a>] Copy Summary button should copy link as well</li>
<li>[<a …

bump version to 20180717.2

---

extensions/BMO/template/en/default/pages/group_members.html.tmpl
extensions/BMO/web/js/edituser_menu.js
extensions/Gravatar/template/en/default/hook/bug/comments-user-image.html.tmpl
extensions/UserProfile/template/en/default/hook/account/prefs/account-start.html.tmpl
template/en/default/global/header.html.tmpl

Given that the `/user_profile` URL is not shareable and `/user_profile?login={USER_EMAIL}` is not visible to unauthenticated users, simply use `/user_profile?user_id={USER_ID}` to work around the issue. We could eventually replace it with `/user/{USER_NICK}` and redesign the page.
[Bug 1136271 - Make user profile page visible to anyone for easier sharing](https://bugzilla.mozilla.org/show_bug.cgi?id=1136271#c6)

Bug 1136271 - Make user profile page visible to anyone for easier sharing

---

extensions/PhabBugz/lib/Feed.pm

Attachments created by Phabricator are created as the user performing
the action as the creator; however the user's email preferences where
not honoured.  This resulted in emails being sent for these changes even
when the user has "don't email me about change I make" set.

Bug 1475593 - Bugzilla Emails received when patches are attached in Phabricator

---

extensions/PhabBugz/lib/WebService.pm

The ThrowUserError() calls in PhabBugz's WebService.pm were
causing errors as Bugzilla::Error wasn't being imported.

no bug - Include Bugzilla::Error in PhabBugz's WebService.pm.

---

Bugzilla/CGI.pm
extensions/GoogleAnalytics/web/js/analytics.js

* Set GA's [`transport`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#transport) option to use [`navigator.sendBeacon`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) by default
* Replace the `image-src` CSP directive with `connect-src` to allow beacon or fallback XHR
[Bug 1419636 - Make Google Analytics use beacon/XHR instead of img tag](https://bugzilla.mozilla.org/show_bug.cgi?id=1419636)

Bug 1419636 - Make Google Analytics use beacon/XHR instead of img tag

---

extensions/ComponentWatching/web/js/overlay.js

The new one-click component watching functionality added in #646 should be disabled properly if the user is not logged in. This checks if their API key is available, and if not, simply remove the Watch buttons.
[Bug 1479523 - Disable one-click component watching for logged out users](https://bugzilla.mozilla.org/show_bug.cgi?id=1479523)

Bug 1479523 - Disable one-click component watching for logged out users

---

Bugzilla/User/Setting.pm
Bugzilla/WebService/Server/REST.pm
extensions/Review/Extension.pm
mod_perl.pl
rest.cgi

In #672 performance regressed a bit, so let's win that back here.
The theme of this change is to load bugzilla classes earlier. It seems to save about 40ms per API call.
Before:
After

Bug 1320977 - performance tweaks

---

Bugzilla/UserAgent.pm

* On the Enter Bug page, select the `x86_64` platform on Intel Mac by default.
* Tested with Firefox, Chrome and Safari.
[Bug 1466737 - "use my platform" should default to x86_64 on Mac OS X](https://bugzilla.mozilla.org/show_bug.cgi?id=1466737)

Bug 1466737 - "use my platform" should default to x86_64 on Mac OS X

---

skins/standard/global.css

* Fix a regression from from #646 where labels in the dropdown list are not wrapped properly
* Add an ellipsis at the end of labels (not yet supported in Firefox)
[Bug 1479563 - Wrap labels in Requests dropdown list](https://bugzilla.mozilla.org/show_bug.cgi?id=1479563)
Firefox (left) and Chrome (right)

Bug 1479563 - Wrap labels in Requests dropdown list

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/template/en/default/bug_modal/field.html.tmpl

* Remove `<label>` inside `<a>` so the help link works as expected
* Use the `aria-label` attribute instead to make `<select>` accessible
[Bug 1478013 - Importance, Status and Platform section labels in show bug view are linked but not clickable](https://bugzilla.mozilla.org/show_bug.cgi?id=1478013)

Bug 1478013 - Importance, Status and Platform section labels in show bug view are linked but not clickable

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1476288" target="_blank">1476288</a>] Replace moz_nick with (new, revised) nick and also attempt to disallow duplicate nicks</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1472954" target="_blank">1472954</a>] Implement one-click component watching on bug modal and component description pages</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1136271" target="_blank">1136271</a>] Make user profile page visible to anyone for easier sharing</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1475593" target="_blank">1475593</a>] Bugzilla Emails received when patches are attached in Phabricator</li>
<li>[<a …

 bump version to 20180801.1 

---

.circleci/config.yml
Dockerfile
Makefile.PL

This updates the base image and the dependency specification to include the datadog and sentry libs.

no bug - add dependencies needed for monitoring

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1480583" target="_blank">1480583</a>] User-&gt;match is not paging properly so all user results are not return if more than 100 users</li>
</ul>

bump version to 20180803.1

---

extensions/MyDashboard/web/js/flags.js

simplified what was there by just adding a new Revision column with the ID as a link directly to the revision in Phab instead of adding a new row. If you hover the link, the revision summary is displayed.

Bug 1480891 my dashboard does not show the revision id and title for phabricator review requests

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1480891" target="_blank">1480891</a>] my dashboard does not show the revision id and title for phabricator review requests</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1481893" target="_blank">1481893</a>] After recent push of bug 1478897 bug/revision syncing has been broken due to coding error</li>
</ul>

bump version to 20180808.1

---

skins/standard/attachment.css

Font Awesome was one of my local fonts which is not available on BMO 😓 Just use Material Icons for now. It doesn’t have media format icons, but I don’t want to add another icon font file.

Bug 602313 follow up - Icons on new attachment uploader are broken

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=602313" target="_blank">602313</a>] Allow creation of attachments by pasting an image from clipboard, as well as by drag-and-dropping a file from desktop</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1482475" target="_blank">1482475</a>] Add extensive testing framework</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1480878" target="_blank">1480878</a>] Monitor the health of PhabBugz connector job processing</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1473958" target="_blank">1473958</a>] Update Thunderbird logo, replace Data Platform and Tools icon on easy product selector</li>
<li>[<a …

bump version to 20180820.1

---

Bugzilla/Install/Localconfig.pm
README.rst
extensions/BMO/template/en/default/hook/global/header-additional_header.html.tmpl
template/en/default/setup/strings.txt.pl

* Cherry-pick #603 that has been backed out in #626
* Stop using `bugzil.la` as canonical URL, which is actually marked up with wrong HTML
[Bug 1399721 - change canonical from bugzil.la to bugzilla.mozilla.org](https://bugzilla.mozilla.org/show_bug.cgi?id=1399721)

Bug 1399721 - change canonical from bugzil.la to bugzilla.mozilla.org

---

scripts/secbugsreport.pl

Adds X-Bugzilla-Type to secbugsreport email which fixes some warnings that perl was outputting.

no bug - add X-Bugzilla-Type to secbugsreport email

---

Bugzilla.pm

[release tag](https://github.com/mozilla-bteam/bmo/tree/release-20180910.1)
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1399721" target="_blank">1399721</a>] change canonical from bugzil.la to bugzilla.mozilla.org</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1486369" target="_blank">1486369</a>] please enable "due date" for Firefox -&gt; Security: Review Request component</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1488292" target="_blank">1488292</a>] Remove MozReview extension from BMO code tree as MozReview is being decommissioned</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1479466" target="_blank">1479466</a>] Security-bug email reports</li> …

bump to version 20180910.1

---

Bugzilla/DB.pm
Makefile.PL

The code didn't allow a way of doing this without a lot of work.
So I had to take the following approach:
The 'dbh' attribute is now a method that delegates to DBIx::Connector's dbh
method. Per the docs, ->dbh() "Returns the connection's database handle. It will
use a an existing handle if there is one, if the process has not been forked or
a new thread spawned, and if the database is pingable. Otherwise, it will
instantiate, cache, and return a new handle."
Then there is the matter of the 'handles' on dbh. I've used Package::Stash to
insert proxy methods into the class when it is loaded.

Bug 1490708 - Ensure we always call DBIx::Connector->dbh before any DBI method

---

extensions/BugModal/web/bug_modal.js

Open the bug activity page in a new tab when the History menu item on bug modal is clicked.
[Bug 1345673 - Open Bugzilla History in a New Window or Tab](https://bugzilla.mozilla.org/show_bug.cgi?id=1345673)

Bug 1345673 - Open Bugzilla History in a New Window or Tab

---

Bugzilla.pm

the following will be been pushed to bugzilla.mozilla.org:
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1487422" target="_blank">1487422</a>] Remove Phabricator section from MyDashboard and related WebService API</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1490687" target="_blank">1490687</a>] Stop setting r+s on Phabricator attachments</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1490708" target="_blank">1490708</a>] Ensure we always call DBIx::Connector-&gt;dbh before any DBI method</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1491973" target="_blank">1491973</a>] Add GeckoView to BMO::Data special casing</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1345673" target="_blank">1345673</a>] Open …

bump version to 20180918.1

---

extensions/BMO/template/en/default/global/choose-product.html.tmpl
extensions/BMO/web/styles/choose_product.css

* Add the new GeckoView product to the New Bug and Browse pages.
* Use the same icon as Firefox for Android, because GeckoView has no logo yet.
[Bug 1470536 - Add new GeckoView product to easy product selector on Browse and Enter Bug pages](https://bugzilla.mozilla.org/show_bug.cgi?id=1470536)
The below is a live mockup created with DevTools.

Bug 1470536 - Add new GeckoView product to easy product selector on Browse and Enter Bug pages

---

Bugzilla/DB.pm

This is a bigger change than I anticipated, because the way we cached
DBIx::Connector objects was bad.
Now we cache the Bugzilla::DB instances in connect_main() and connect_shadow().
This is for maintaining a 1:1 mapping of Bugzilla::DB objects and
DBIx::Connector objects. This is important because we want be able to inspect
Bugzilla::DB->bz_in_transactions() from the 'connected' event.
Note that we weaken the lexical variable $self in _build_connector()
because it is referenced by the callback passed to DBI.
Without this there would be a memory cycle and stuff would never be freed.
(tested my understanding in this gist:
https://gist.github.com/dylanwh/646574a027f7b7d92cb7586676da7468)

Bug 1492926 - Handle DBIx::Connectors more appropriately

---

extensions/BMO/template/en/default/global/choose-product.html.tmpl
extensions/BMO/web/js/new-bug-frequent-comp.js
extensions/BMO/web/styles/choose_product.css
template/en/default/global/header.html.tmpl

* A request from the DevTools team (and probably more)
* Let users to choose from their most-used components on the New Bug page
* Show top 10 components the user has filed against within a year
[Bug 1473417 - Show often/recently used products/components on New Bug page](https://bugzilla.mozilla.org/show_bug.cgi?id=1473417)

Bug 1473417 - Show often/recently used products/components on New Bug page

---

Bugzilla.pm

The following changes will be pushed to bugzilla.mozilla.org:
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1487422" target="_blank">1487422</a>] Remove Phabricator section from MyDashboard and related WebService API</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1490687" target="_blank">1490687</a>] Stop setting r+s on Phabricator attachments</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1490708" target="_blank">1490708</a>] Ensure we always call DBIx::Connector-&gt;dbh before any DBI method</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1491973" target="_blank">1491973</a>] Add GeckoView to BMO::Data special casing</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1345673" target="_blank">1345673</a>] …

bump version to 20180925.1

---

Bugzilla/Quantum.pm
Bugzilla/Test/Util.pm
Makefile.PL
t/mojo-example.t

This PR adds a new test case that uses Mojo::Test. It's a very simple test, but it is well-commented (I hope) and can be used as an example for future work.
One part that is missing that @mars-f will want to see is how to mock the datadog object -- but that part is easy to explain.

Bug 1494065 - Add a basic test using Test::Mojo

---

extensions/BMO/template/en/default/hook/flag/type_comment-form.html.tmpl
extensions/FlagTypeComment/template/en/default/flag/type_comment.html.tmpl
extensions/FlagTypeComment/web/js/ftc.js
extensions/FlagTypeComment/web/styles/ftc.css
skins/standard/attachment.css
skins/standard/global.css
template/en/default/flag/list.html.tmpl

* A request from the Release Management team
* Upon selecting "?" for an approval flag, insert a temporary form that will be later converted to plaintext comment text when submitting form
* If a template is not available, fallback to traditional plaintext comment template stored in the DB
* https://screenshots.firefox.com/TxHyLrNCfuslLAbG/bmo-web.vm
* https://screenshots.firefox.com/tNzGtdwY0bCe6i9e/bmo-web.vm
[Bug 1489718 - Insert form widgets for approval flag requests instead of free-form comment text](https://bugzilla.mozilla.org/show_bug.cgi?id=1489718)

Bug 1489718 - Insert form widgets for approval flag requests instead of free-form comment text

---

extensions/GuidedBugEntry/template/en/default/bug/create/comment-guided.txt.tmpl
extensions/GuidedBugEntry/template/en/default/guided/guided.html.tmpl
extensions/GuidedBugEntry/web/js/guided.js
template/en/default/bug/create/comment-guided.txt.tmpl
template/en/default/bug/create/create-guided.html.tmpl

* Remove one usage of the non-standard `navigator.buildID` DOM property, which will be removed from Firefox in the near future
* Also remove another Build Identifier field based on the browser’s UA string, which isn’t useful because it has been frozen at `Gecko/20100101`.
[Bug 1493490 - Remove navigator.buildID usage from Bugzilla Helper](https://bugzilla.mozilla.org/show_bug.cgi?id=1493490)

Bug 1493490 - Remove navigator.buildID usage from Bugzilla Helper

---

Bugzilla/Quantum.pm
Bugzilla/Quantum/Plugin/Glue.pm

this makes all the mojo timeouts larger -- except for 'clients' which should be smaller because we're so synchronous. It also puts them into environmental variables so ops can tweak them. 
Note some of the code has moved to the main application class to make future people less likely to not notice these values.

no bug - use more generous timeouts

---

buglist.cgi
template/en/default/list/list.html.tmpl

Allow to customize the `buglist.cgi` title using `&title=foobar` param.
[Bug 1494645 - Allow customizing HTML <title> of search results](https://bugzilla.mozilla.org/show_bug.cgi?id=1494645)

Bug 1494645 - Allow customizing HTML <title> of search results

---

Bugzilla.pm
Bugzilla/CGI.pm
Bugzilla/Quantum.pm
Bugzilla/Quantum/CGI.pm
Bugzilla/Quantum/Plugin/Glue.pm
Bugzilla/Quantum/Plugin/Helpers.pm
scripts/entrypoint.pl

There are some things that should've been in the first patch but were missed:
1. Calling $c->finish in the finally block should not happen if an exception has been raised.
2. Bugzilla->cleanup() should be called at the same time the mojolicious stash is cleared.
3. Code referencing the shutdownhtml should be removed
4. The conditionals that ran code in Bugzilla.pm when it was not run under mod_perl should instead check where the Bugzilla.pm module was loaded from.
5. Revert the default template from #770 
6. Also removed some stuff that manipulates the PATH and signals, which we shouldn't do

Bug 1495071 - Mojolicious Cleanup

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1487422" target="_blank">1487422</a>] Remove Phabricator section from MyDashboard and related WebService API</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1490687" target="_blank">1490687</a>] Stop setting r+s on Phabricator attachments</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1490708" target="_blank">1490708</a>] Ensure we always call DBIx::Connector-&gt;dbh before any DBI method</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1491973" target="_blank">1491973</a>] Add GeckoView to BMO::Data special casing</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1345673" target="_blank">1345673</a>] …

bump version to 20181002.1

---

Bugzilla/WebService/Product.pm
docs/en/rst/api/core/v1/product.rst

Add the `triage_owner` field to each component returned by `/rest/product` API.
[Bug 1489120 - Add a rest API to get triage owners for each product/component pair](https://bugzilla.mozilla.org/show_bug.cgi?id=1489120)

Bug 1489120 - Add a rest API to get triage owners for each product/component pair

---

public/metricsgraphics/socorro-lens.html

Fix a wrong CSS path in metricsgraphics.
[Bug 1495746 - /app/static/metricsgraphics/css/google-OpenSans.css missing in app container](https://bugzilla.mozilla.org/show_bug.cgi?id=1495746)

Bug 1495746 - /app/static/metricsgraphics/css/google-OpenSans.css missing in app container

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1495349" target="_blank">1495349</a>] Remove Persona extension</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1263502" target="_blank">1263502</a>] Add duplicates to /rest/bug/id</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1495906" target="_blank">1495906</a>] After mojo update /latest/configuration API call no longer works and gives page not found</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1496233" target="_blank">1496233</a>] "Dunno" -&gt; "Don't know" in approval request form</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1489120" target="_blank">1489120</a>] Add a rest API to get triage …

bump version to 20181004.1

---

extensions/PhabBugz/lib/Feed.pm

Use Datadog to count the number of times that jobs are run by the
phabbugz job scheduler.  This should catch problems if the process
responsible for running the jobs dies.

Bug 1496832 - Add monitoring for feed daemon becoming unresponsive

---

extensions/BMO/web/js/new-bug-frequent-comp.js

Fix the most-used components on the New Bug page not considering bug cloning cases.
[Bug 1496803 - Suggested component links ignore cloned bug data](https://bugzilla.mozilla.org/show_bug.cgi?id=1496803)

Bug 1496803 - Suggested component links ignore cloned bug data

---

extensions/BMO/template/en/default/bug/create/custom_forms.none.tmpl

Personas Plus has retired, and the GitHub issue link under the Mozilla Labs product should be removed.
[Bug 1497234 - Remove Personas Plus GitHub link from Custom Bug Entry Forms index](https://bugzilla.mozilla.org/show_bug.cgi?id=1497234)

Bug 1497234 - Remove Personas Plus GitHub link from Custom Bug Entry Forms index

---

template/en/default/global/header.html.tmpl

Remove `<base href>` introduced during the Mojo migration (#517). It was originally added in #603 but backed out in #626.
[Bug 1497070 - In-page links are broken due to <base href> added during Mojo migration](https://bugzilla.mozilla.org/show_bug.cgi?id=1497070)

Bug 1497070 - In-page links are broken due to <base href> added during Mojo migration

---

public/metricsgraphics/socorro-lens.html

Change the graph’s default matching condition from Like Match (“signature contains X”) to Exact Match (“signature is X”) to avoid confusion.
[Bug 1497437 - The crash graph should display Exact Match results by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1497437)

Bug 1497437 - The crash graph should display Exact Match results by default

---

.circleci/config.yml
Bugzilla.pm
Dockerfile

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1496803" target="_blank">1496803</a>] Suggested component links ignore cloned bug data</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1497234" target="_blank">1497234</a>] Remove Personas Plus GitHub link from Custom Bug Entry Forms index</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1497070" target="_blank">1497070</a>] In-page links are broken due to &lt;base href&gt; added during Mojo migration</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1497437" target="_blank">1497437</a>] The crash graph should display Exact Match results by default</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=623384" …

bump version to 20181010.1

---

docs/en/rst/administering/parameters.rst
skins/standard/global.css
template/en/default/admin/params/general.html.tmpl
template/en/default/global/header.html.tmpl

* Move the site-wide message in the main content to above the global header
* As a side-along, add `<noscript>` message for browsers with JavaScript disabled
[Bug 1498436 - Move site-wide message to global header](https://bugzilla.mozilla.org/show_bug.cgi?id=1498436)

Bug 1498436 - Move site-wide message to global header

---

Bugzilla/WebService/Product.pm

This saves a large amount of memory by avoiding the duplication of the serialized flag format.

Bug 1495741 - memory issues: use local flag cache

---

js/field.js

Allow to submit the bug form when you hit Ctrl+Enter (Windows/Linux) or Cmd+Enter (macOS) on the comment area. This works with both modal and non-modal bug page as well as the new bug page.
[Bug 1009716 - Add (Cmd|Ctrl)+Enter shortcut for submitting from text areas.](https://bugzilla.mozilla.org/show_bug.cgi?id=1009716)

Bug 1009716 - Add (Cmd|Ctrl)+Enter shortcut for submitting from text areas.

---

conf/checksetup_answers.txt
contribute.json
extensions/ContributorEngagement/template/en/default/contributor/email.txt.tmpl
template/en/default/account/prefs/apikey.html.tmpl
vagrant_support/checksetup_answers.j2

Change the Read the Docs domain from .org to .io to avoid a redirect.
[Bug 1499417 - Change BMO docs links from bmo.readthedocs.org to .io](https://bugzilla.mozilla.org/show_bug.cgi?id=1499417)

Bug 1499417 - Change BMO docs links from bmo.readthedocs.org to .io

---

extensions/FlagTypeComment/web/js/ftc.js
extensions/FlagTypeComment/web/styles/ftc.css
extensions/Review/template/en/default/hook/flag/list-requestee.html.tmpl
extensions/Review/web/styles/review.css
skins/standard/attachment.css
template/en/default/attachment/edit.html.tmpl

* Hide the original comment form when the custom flag request form is inserted
* Improved the page layout to prevent the flags and form from going below the fold
[Bug 1496004 - Improve layout of attachment detail page, hide comment form when custom form is inserted](https://bugzilla.mozilla.org/show_bug.cgi?id=1496004)
* [Default](https://screenshots.firefox.com/L98zPjdU6WP2Iy8T/bmo-web.vm)
* [Form inserted](https://screenshots.firefox.com/0c625eM6JudauKdS/bmo-web.vm)

Bug 1496004 - Improve layout of attachment detail page, hide comment form when custom form is inserted

---

Dockerfile
patches/Mojo-IOLoop-Stream.pm.patch

In perl 5.12, length(undef) was made no longer a warning.
In order to reduce memory usage, mojo undefines the outgoing buffer.
This means on perl <= 5.12, a warning is printed frequently (multiple times
per request).
Mojo support for 5.10 is waning, so for the moment we patch that code to silence
this warning.

no bug - silence mojo warning

---

Bugzilla/Quantum/Plugin/BlockIP.pm
template/en/default/global/ip-blocked.html.tmpl

This is just a proposal, I think we'd need higher approval to use recaptcha.
Also I'd check for the do-not-track header and not load recaptcha if found.

Bug 1482644 - Improve "Too many requests" page with an explaination

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1354589" target="_blank">1354589</a>] Implement OAuth2 on BMO</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1498206" target="_blank">1498206</a>] Replace LWP::UserAgent with Mojo::UserAgent in phabbugz extension</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1498436" target="_blank">1498436</a>] Move site-wide message to global header</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1498362" target="_blank">1498362</a>] Shutter the "Powered By Mozilla" form</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1009716" target="_blank">1009716</a>] Add (Cmd|Ctrl)+Enter shortcut for submitting from text …

bump version to 20181017.1

---

Bugzilla/WebService/Bug.pm
docs/en/rst/api/core/v1/attachment.rst

* Allow to set bug flags, needinfo in particular, with the [attachment API methods](https://bmo.readthedocs.io/en/latest/api/core/v1/attachment.html).
* Tested locally with simple data
[Bug 1487171 - Allow setting bug flags when creating/updating attachment with API](https://bugzilla.mozilla.org/show_bug.cgi?id=1487171)

Bug 1487171 - Allow setting bug flags when creating/updating attachment with API

---

skins/standard/global.css

* Solve rough scrolling issue and undesired bounce effect on desktop Safari
* Add [`overscroll-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) for all browsers
* Tested with various browsers on macOS, Windows, Android, iOS
[Bug 1469733 - Fix scrolling glitch on Safari](https://bugzilla.mozilla.org/show_bug.cgi?id=1469733)

Bug 1469733 - Fix scrolling glitch on Safari

---

Bugzilla/Config/Reports.pm
Bugzilla/Report/SecurityRisk.pm
scripts/secbugsreport.pl
t/security-risk.t
template/en/default/admin/params/reports.html.tmpl
template/en/default/reports/email/security-risk.html.tmpl

- Add requested graphs
- Treat marking a bug as stalled the same as closing it
- Pivot the tables to be more readable
- Make the report more actionable
- Group by teams
- Round up the median age
- Move the open bug count to the first column
- Color code the add/closed deltas
- Convert the open bug graphs to stacked graphs

Bug 1496057 - Update Security Bugs Report

---

skins/standard/attachment.css

Fix the [broken attachment flags layout](https://twitter.com/brianskold/status/1054536937741017088) regressed in #788. The CSS flexbox should be applied only to the attachment edit/details page.
[Bug 1501133 - Attachment flags layout on new bug page is broken](https://bugzilla.mozilla.org/show_bug.cgi?id=1501133)

Bug 1501133 - Attachment flags layout on new bug page is broken

---

.circleci/config.yml
Bugzilla/Quantum.pm
Bugzilla/Quantum/CGI.pm
Bugzilla/Quantum/Plugin/BlockIP.pm
Bugzilla/Template.pm

By moving BlockIP plugin first, it is ensured to execute first.
This is a slight speed gain. The primary speed gain is by caching
the content of the template.
Before: 429 Too Many Requests (0.031951s, 31.298/s)
After:  429 Too Many Requests (0.000182s, 5494.505/s)

Bug 1501849 - Speed up IP blocked page: pre-render template

---

extensions/BugModal/template/en/default/bug_modal/header.html.tmpl
extensions/OpenGraph/template/en/default/hook/global/header-start.html.tmpl

#681 wasn’t the right solution for the issue, so let’s do this.
* Avoid using `Bugzilla.cgi.self_url` because it will be `post_bug.cgi` after POSTed.
* Embed the correct `<meta property="og:url">` only on bug pages, just like `<link rel="canonical">`, because the page’s canonical URL cannot be determined in some cases, e.g. search results.
* Use the same, correct URL for `BUGZILLA.bug_url` in JavaScript.
[Bug 1479535 - BUGZILLA.bug_url is wrong on bug page after POSTed, Copy Summary doesn’t work as expected](https://bugzilla.mozilla.org/show_bug.cgi?id=1479535)

Bug 1479535 - BUGZILLA.bug_url is wrong on bug page after POSTed, Copy Summary doesn’t work as expected

---

extensions/FlagTypeComment/template/en/default/flag/type_comment.html.tmpl

Add the missing `version` filter to the FlagTypeComment extension assets to prevent old CSS/JavaScript files from being served to users. Note that `basepath` will be prepended in the filter so it’s not necessary in these paths.
[Bug 1503162 - Approval request form is incomplete in some cases](https://bugzilla.mozilla.org/show_bug.cgi?id=1503162)

Bug 1503162 - Approval request form is incomplete in some cases

---

Bugzilla/WebService/Bug.pm

* Fix the data type of the [native bug count API](https://bugzilla.mozilla.org/rest/bug?keywords=intermittent-failure&chfieldfrom=-1y&count_only=true) return value. It has to be an integer, not a string. 
* The change is only for REST and JSON-RPC. I’m not familiar with XML-RPC and it’s going away anyway, so I’ll keep it as-is.
[Bug 1503182 - Fix data type of native bug count API return value](https://bugzilla.mozilla.org/show_bug.cgi?id=1503182)

Bug 1503182 - Fix data type of native bug count API return value

---

docs/en/rst/api/core/v1/index.rst
extensions/Review/lib/WebService.pm

Also update the perldoc to fix the description of the `id`
response field.

Bug 1384230 - Document flag_activity API.

---

Bugzilla/Bug.pm
enter_bug.cgi
extensions/BMO/template/en/default/bug/create/create-client-bounty.html.tmpl
extensions/BMO/template/en/default/bug/create/create-doc.html.tmpl
extensions/BMO/template/en/default/bug/create/create-itrequest.html.tmpl
extensions/BMO/template/en/default/bug/create/create-legal.html.tmpl
extensions/BMO/template/en/default/bug/create/create-mobile-compat.html.tmpl
extensions/BMO/template/en/default/bug/create/create-mozlist.html.tmpl
extensions/BMO/template/en/default/bug/create/create-trademark.html.tmpl
extensions/BMO/template/en/default/bug/create/create-user-engagement.html.tmpl
extensions/BMO/template/en/default/bug/create/create-web-bounty.html.tmpl
extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/template/en/default/bug_modal/field.html.tmpl
template/en/default/bug/create/create-guided.html.tmpl
template/en/default/bug/create/create.html.tmpl
template/en/default/bug/edit.html.tmpl

Remove the default “http://“ value from the URL field. Instead, add “https://“ as the `placeholder` attribute.
[Bug 1436619 - http:// in URL field](https://bugzilla.mozilla.org/show_bug.cgi?id=1436619)

Bug 1436619 - http:// in URL field

---

skins/standard/global.css

Fix regressions from #728 which I couldn’t find while testing.
* Trackpad swipe page navigation is no longer working due to `overscroll-behavior`
* Horizontal scrolling on a narrower screen (mobile) is no longer working due to `overflow`
* Vertical scrolling at the top and bottom of the page is no longer working when the page is zoomed due to `overscroll-behavior`

Bug 1503748 - Trackpad swipe navigation and mobile horizontal scrolling broken, vertical scrolling partially broken when zoomed

---

extensions/BugModal/web/bug_modal.css
skins/standard/describecomponents.css
template/en/default/reports/components.html.tmpl

* Fix layout on the component description pages, including:
* [Core](https://bugzilla.mozilla.org/describecomponents.cgi?product=Core): due to the [newly added HTML descriptions](https://bugzilla.mozilla.org/show_bug.cgi?id=1484408)
* [Websites](https://bugzilla.mozilla.org/describecomponents.cgi?product=Websites): due to the longer domain-based component names
* See [this screenshot](https://screenshots.firefox.com/K4nIt0ik8s8wqomi/bmo-web.vm) for how it works (default assignee and QA are hidden on BMO, shown for demo purpose only)
[Bug 1485303 - lists in component descriptions break describecomponents.cgi layout](https://bugzilla.mozilla.org/show_bug.cgi?id=1485303)

Bug 1485303 - lists in component descriptions break describecomponents.cgi layout

---

skins/standard/global.css

Fix the cursor on the global header’s searchbar, that should be an I-beam instead of hand/pointer.
[Bug 1482338 - “Search Bugs” field has “cursor: pointer” style while it’s text field](https://bugzilla.mozilla.org/show_bug.cgi?id=1482338)

Bug 1482338 - "Search Bugs" field has "cursor: pointer" style while it's text field

---

Bugzilla/WebService/Bug.pm

Fix a regression from #872. Looks like my first attempt was right, and I didn’t test the updated code 😓 When `count_only=1`, the `$data` will be an integer so it can be used as-is.
[Bug 1505762 - count_only=1 results in error with REST API](https://bugzilla.mozilla.org/show_bug.cgi?id=1505762)

Bug 1505762 - count_only=1 results in error with REST API

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1436619" target="_blank">1436619</a>] http:// in URL field</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1505762" target="_blank">1505762</a>] count_only=1 results in error with REST API</li>
</ul>

bump version to 20181108.1

---

Bugzilla/WebService/Bug.pm
docs/en/rst/api/core/v1/bug.rst

* Add the `triage_owner` and `triage_owner_detail` fields to the response of `/rest/bug`.
* Allow to search bugs by `triage_owner` via `/rest/bug`.
[Bug 1505793 - Add triage owner in /rest/bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1505793)

Bug 1505793 - Add triage owner in /rest/bug

---

extensions/BMO/Extension.pm

The original PR #26 requires a space before a PR/issue notation but it doesn’t work when it’s in parentheses or at the beginning of line. Just use `\b` instead.
[Bug 1351116 - github issue links are not expanded in parentheses](https://bugzilla.mozilla.org/show_bug.cgi?id=1351116)

Bug 1351116 - github issue links are not expanded in parentheses

---

Bugzilla/WebService/Bug.pm
Bugzilla/WebService/Group.pm
Bugzilla/WebService/User.pm
docs/en/rst/api/core/v1/bug.rst
docs/en/rst/api/core/v1/flag-activity.rst
docs/en/rst/api/core/v1/group.rst
docs/en/rst/api/core/v1/user.rst
extensions/Review/lib/WebService.pm
qa/t/webservice_user_get.t

Expose the internal `nick` field to user objects returned by various API methods, `/rest/bug` and `/rest/user` in particular.
[Bug 1505831 - Add nick field to all user objects including *_detail returned by /rest/bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1505831)

Bug 1505831 - Add nick field to all user objects including *_detail returned by /rest/bug

---

extensions/BMO/template/en/default/bug/create/create-swag.html.tmpl
extensions/EditTable/web/js/edit_table.js
extensions/GuidedBugEntry/web/js/guided.js
extensions/MyDashboard/web/js/flags.js
extensions/MyDashboard/web/js/query.js
extensions/Review/web/js/review_history.js
extensions/Splinter/web/splinter.js
extensions/TrackingFlags/web/js/admin.js
js/bug.js
js/comment-tagging.js
js/field.js
js/global.js
js/instant-search.js
template/en/default/reports/report-table.html.tmpl

`YAHOO.lang` and `String.prototype.trim` polyfill are no longer needed. 
* YUI 2 `YAHOO.lang.JSON` and YUI 3 `Y.JSON` -> native `JSON`
* YUI 2 `YAHOO.lang.trim()` -> `String.prototype.trim()`
* YUI 2 `YAHOO.lang.escapeHTML()` and YUI 3 `Y.Escape.html()` -> `String.prototype.htmlEncode()` (Bugzilla’s own polyfill)
[Bug 1493996 - Stop using YAHOO.lang.*, remove String.prototype.trim polyfill](https://bugzilla.mozilla.org/show_bug.cgi?id=1493996)

Bug 1493996 - Stop using YAHOO.lang.*, remove String.prototype.trim polyfill

---

extensions/EditComments/Extension.pm

Splitting the schema change from #736. Just adding the `is_hidden` column to the `longdescs_activity` table.

Bug 1484892 schema change only - Add is_hidden column to longdescs_activity

---

Bugzilla/Role/Storable.pm
Bugzilla/User.pm

This introduces a Role::Tiny role that uses the existing `flatten_to_hash()` method of `Bugzilla::Object` to allow Storable round-tripping.
When working on #884 it seems that the Bugzilla::User object has this CODEref in it somewhere.
This is a rather simple change that allows it to be stored and recovered.
I have another patch that isn't needed right now which is a much more efficient version of `_serialisation_keys` but it seems it isn't needed right now.

Create a role that allows Bugzilla::Object-based classes to be stored using Storable

---

extensions/Splinter/Extension.pm
extensions/Splinter/lib/Util.pm
extensions/Splinter/template/en/default/hook/request/email-after_summary.txt.tmpl

Use an absolute/complete URL for a Splinter review link in plaintext emails. In HTML, there is `<base href>` so a relative URL should work. Tested locally with [actual emails](https://github.com/mozilla-bteam/bmo#testing-emails).
[Bug 1507867 - splinter review links in emails are missing host/scheme, rendering them unusable](https://bugzilla.mozilla.org/show_bug.cgi?id=1507867)

Bug 1507867 - splinter review links in emails are missing host/scheme, rendering them unusable

---

skins/standard/buglist.css
template/en/default/list/list.html.tmpl

When the `buglist.cgi` URL contains the `title` param or it’s a saved search, show the title in `<h1>` on the page. Technically `<h1>` should always be there, but we can revisit later when redesigning the search results page.
[Bug 1507518 - Allow title parameter value in url to be the title of the page](https://bugzilla.mozilla.org/show_bug.cgi?id=1507518)

Bug 1507518 - Allow title parameter value in url to be the title of the page

---

Bugzilla.pm

Note that passing bug_id to active_custom_flags() means you can get inactive flags.
call list:
* Bugzilla->active_custom_flags
* Bugzilla::Extension::TrackingFlags::active_custom_flags
* Bugzilla::Extension::TrackingFlags::Flag::match
* Bugzilla::Extension::TrackingFlags::Flag::preload_all_the_things
```perl
if ($params && exists $params->{'bug_id'} && $params->{'bug_id'}) {
```

Bug 1508695 - Incorrect or missing tracking flags on search results

---

Bugzilla/Role/FlattenToHash.pm
Bugzilla/User.pm

Bugzilla::User is still not always safe for storable:
Can't use an undefined value as an ARRAY reference at
/vagrant/Bugzilla/Object.pm line 286, at
/vagrant/local/lib/perl5/TheSchwartz/Job.pm line 29.
This adds a different implementation of flatten_to_hash() that relies on the
DB_COLUMNS defined for the class (via _get_db_columns, so extensions work
correctly). The new method is `_get_db_keys` and it should always return the same result as `_serialisation_keys` except that it does not require first querying the database.
This can be tested as below (note: `Set::Object` is not currently included with BMO, but it makes the below illustration easier)
```perl
$ set(Bugzilla::User->_get_db_keys) - set(Bugzilla::User->_serialisation_keys)
Took 0.000822067260742188 seconds.
Set::Object()
```

add a better flatten_to_hash method to User

---

Bugzilla/Chart.pm
Bugzilla/Util/DateTime.pm
extensions/BMO/lib/Reports/ReleaseTracking.pm
extensions/BMO/lib/Reports/UserActivity.pm

Move `Bugzilla::Extension::BMO::Util` to `Bugzilla::Util::DateTime` and use the `parse_date` method for the charts. In the future, the other date-related methods in `Bugzilla::Util` could also be moved to `Bugzilla::Util::DateTime`.
[Bug 324535 - Allow the use of relative dates in charts](https://bugzilla.mozilla.org/show_bug.cgi?id=324535)

Bug 324535 - Allow the use of relative dates in charts

---

js/buglist.js
template/en/default/list/edit-multiple.html.tmpl
template/en/default/list/list.html.tmpl

As part of the background bug editing in #884 I'm adding a checkbox that says "run edits in background". I'm adding some code to the frontend to make this obvious to the user and while I'm at it I'll need to add some new JS. Rather than add more to the html I'd like move it out.

move inline js on the buglist out to a separate file

---

extensions/BMO/Extension.pm

The regex in #897 matches not only GitHub issues/PRs but also regular links with a fragment, Searchfox URLs in particular. This modified and simplified regex checks if there's no slash before the string to exclude those links.

Bug 1351116 followup - Don't match regular links

---

request.cgi
template/en/default/request/queue.csv.tmpl
template/en/default/request/queue.html.tmpl
template/en/default/request/queue.json.tmpl

Fix a regression from #691. The requestee of a flag can be undefined if it's not specifically requestable. This PR prevents `Bugzilla::User::new` being called in such cases, and make the requestee column empty in HTML/CSV and `null` in JSON.

Bug 1508903 - internal error on requests.cgi:  Bad argument param sent to Bugzilla::User::new function.

---

extensions/BMO/lib/Reports/Triage.pm
extensions/BMO/template/en/default/pages/triage_owners.html.tmpl

* Update the default product list for the [Triage Owners](https://bugzilla.mozilla.org/page.cgi?id=triage_owners.html) page
* Use a proper label for the default list instead of confusing `__Any__`
[Bug 1499697 - Update triage owner list to include all Firefox-related major products and stop saying `__Any__`](https://bugzilla.mozilla.org/show_bug.cgi?id=1499697)

Bug 1499697 - Update triage owner list to include all Firefox-related major products and stop saying __Any__

---

Bugzilla/DB/Mysql.pm
Bugzilla/WebService/User.pm

This patch improves the behavior of fulltext searches for real names.
For instance, 'Israel Mad' actually finds @purelogiq now (it turns into
```sql
SELECT login_name FROM  profiles where MATCH(realname) AGAINST ('+Israel +Mad*' IN BOOLEAN MODE)  LIMIT 25
```
The trick is to the use [Boolean Mode](https://dev.mysql.com/doc/refman/5.5/en/fulltext-boolean.html), so each word is prefixed with a `+`, and the final word ends with `*`.

improve fulltext completion for real names

---

extensions/EditComments/web/js/inline-editor.js

Ignore trailing space(s) or additional empty line(s) when checking if the comment is edited. This have to be caught client-side even though I’ve added a server-side check just in case. With this fix, those changes won’t enable the Update Comment (Save) button.

Bug 1510832 - Adding a trailing space to a comment causes an error

---

Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm

Split from #942. Add the `bug_description_template` column to the `products` table in preparation for the feature addition.
[Bug 1510109 - Implement per-product new bug comment templates](https://bugzilla.mozilla.org/show_bug.cgi?id=1510109)

Bug 1510109 - Implement per-product new bug comment templates (schema change only)

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1510427" target="_blank">1510427</a>] improve fulltext completion for real names</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1508261" target="_blank">1508261</a>] Closing DevRel sponsorship form on Bugzilla and updating Wiki page</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1508385" target="_blank">1508385</a>] Remove links to input.mozilla.org from Guided Bug Entry flow</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1510653" target="_blank">1510653</a>] API method for returning users profile information when given a valid oauth2 access token</li>
<li>[<a …

bump version to 20181129.1

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1510427" target="_blank">1510427</a>] improve fulltext completion for real names</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1508261" target="_blank">1508261</a>] Closing DevRel sponsorship form on Bugzilla and updating Wiki page</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1508385" target="_blank">1508385</a>] Remove links to input.mozilla.org from Guided Bug Entry flow</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1510653" target="_blank">1510653</a>] API method for returning users profile information when given a valid oauth2 access token</li>
<li>[<a …

bump version to 20181127.2

---

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
extensions/BugModal/web/bug_modal.css

Make the comment action buttons, including Edit, Tag and Reply, a little bit bigger, and tweak the margin around the buttons.
[Bug 1511158 - Enhance comment action button style](https://bugzilla.mozilla.org/show_bug.cgi?id=1511158)

Bug 1511158 - Enhance comment action button style

---

Bugzilla/Quantum.pm
Bugzilla/Quantum/API.pm
Bugzilla/Quantum/CGI.pm
Bugzilla/Quantum/OAuth2/Clients.pm
Bugzilla/Quantum/Plugin/OAuth2.pm
Bugzilla/Quantum/SES.pm

I think this is a more sensible way of handling routes. 
The convention is that each controller can have a setup_routes() class method, which is passed in the routes object. Note this is something like what CGI->load_all() was doing, so I renamed load_all() to setup_routes.
Additionally, we subclass the oauth plugin to provide our defaults.

cleanup oauth2 code and make a better mechanism for splitting routes out from the application class

---

Bugzilla/WebService/User.pm
js/field.js

I don't think we need to load the request info for every user suggestion,
so this adds a fast_mode option that avoids calling the hook.

make user suggest faster by doing less work

---

extensions/BugModal/web/bug_modal.css

Fix a regression from #736 where I changed the design of comment action buttons from text to icons. The icon itself should not be clickable, otherwise the click event target will be wrong.
[Bug 1512424 - Comment Reply button is not working properly on Chrome](https://bugzilla.mozilla.org/show_bug.cgi?id=1512424)

Bug 1512424 - Comment Reply button is not working properly on Chrome

---

extensions/GuidedBugEntry/web/js/guided.js

Exclude the `components.flag_types` field from product API calls to improve performance.
[Bug 1511558 - Guided form's Core Component dropdown list cannot be loaded](https://bugzilla.mozilla.org/show_bug.cgi?id=1511558)

Bug 1511558 - Guided form's Core Component dropdown list cannot be loaded

---

extensions/BugmailFilter/template/en/default/hook/account/prefs/prefs-tabs.html.tmpl
extensions/ComponentWatching/template/en/default/hook/account/prefs/prefs-tabs.html.tmpl
extensions/Example/template/en/default/hook/account/prefs/prefs-tabs.html.tmpl
extensions/RequestNagger/template/en/default/hook/account/prefs/prefs-tabs.html.tmpl
extensions/SecureMail/template/en/default/hook/account/prefs/prefs-tabs.html.tmpl

With the latest version of template toolkit, the use preferences pages are empty.
This seems like a bug-fix upstream, rather than a regression. The reason is we're calling tabs = tabs.import() in many extensions..
It doesn't appear that hash.import() returns the hash, and this was working because the context of the template was localized.
https://metacpan.org/pod/distribution/Template-Toolkit/lib/Template/Manual/VMethods.pod#import

Bug 1513087 - User preferences page is totally empty with Template v2.28

---

Bugzilla/Product.pm
editproducts.cgi
enter_bug.cgi
template/en/default/admin/products/edit-common.html.tmpl

* Allow Bugzilla admins to define a per-product new bug comment template on the Edit Product page. [Screenshot](https://screenshots.firefox.com/8EvjYUvtfAdZucfm/bmo-web.vm)
* Prefill the comment box on the New Bug page with the per-product template if defined.
[Bug 1510109 - Implement per-product new bug comment templates](https://bugzilla.mozilla.org/show_bug.cgi?id=1510109)

Bug 1510109 - Implement per-product new bug comment templates

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1513087" target="_blank">1513087</a>] User preferences page is totally empty with Template v2.28</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1456878" target="_blank">1456878</a>] Support markdown comments</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1510109" target="_blank">1510109</a>] Implement per-product new bug comment templates</li>
</ul>

bump version to 20181212.1

---

template/en/default/bug/comment.html.tmpl

We forgot to correctly switch between a div and pre tag on the new
bug comment preview, based on whether markdown is enabled or not.
This was causing plaintext comments to lose their formatting (only when previewed).

Bug 1514765 - fix new bug comment preview

---

Bugzilla/CGI.pm
extensions/BMO/template/en/default/hook/bug/show-header-end.html.tmpl
extensions/BMO/template/en/default/hook/bug_modal/header-end.html.tmpl
extensions/BMO/web/js/firefox-crash-table.js

Embed a crash data table on Firefox bugs as per a request from the Release Management team.
* Copy the [original WebExtension code](https://github.com/mozilla/crash-stop-addon/blob/master/webextension/content.js), contained in `window.addEventListener('DOMContentLoaded')`.
* Embed the script on both modal and legacy `show_bug.cgi`
* Add CSP for the product-details API and iframe
[Bug 1493253 - Embed crash count table to bug pages](https://bugzilla.mozilla.org/show_bug.cgi?id=1493253)

Bug 1493253 - Embed crash count table to bug pages

---

Bugzilla/Install/Filesystem.pm
google1498b17dba53f45e.html

index.html is never used, so we should remove that option.
This also removes the useless google verification html file too.

remove index.html stuff

---

Bugzilla/JobQueue.pm
jobqueue-worker.pl

Inside the 'tick' function for the worker processes, we set an alarm() for five minutes. That should be long enough -- and importantly after five minutes another worker may pick up the same job. In the case of a job triggering an infinite loop, only a max of one worker will be out of commission for that time.

Bug 1517606 - Prevent infinite loops by making workers die after 5 minutes

---

extensions/BugModal/web/bug_modal.js

The link to the attachment is under a paragraph tag if markdown is enabled.

Bug 1518381 - lightbox is no longer used when clicking on an attachment's link in markdown comments

---

extensions/PhabBugz/web/style/phabricator.css

Bug 1509122 - Need additional space between status icon and status text in the revision panel in show_bug

---

Bugzilla/Comment.pm
extensions/Splinter/Extension.pm

This matches the magic splinter header and sets the markdown flag to false if it matches. I'm not sure if it is safe to call `update()` from `object_end_of_create` though

Bug 1518303 - Comments on splinter patches are misformatted with markdown styling

---

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
extensions/BugModal/web/bug_modal.css

As a quick fix, we will hide the icon until something better can be done.

Bug 1518218 - The attachment icon is misplaced

---

template/en/default/bug/comment.html.tmpl

This fixes the bug entry form, which was using the 'pre' tag when it should use 'div'.
This works because `comment` is always defined, but sometimes it is a string and other times it is an object. calling `comment.id` is a good way to see if it is a comment object or not.

Bug 1518268 - Preview cuts off bottoms of things using ```

---

extensions/BMO/template/en/default/email/bugmail.html.tmpl

I verified this change looks ok in apple mail, I'll try to get it into gmail as well. Do you happen to have a working thunderbird setup?

Bug 1518266 - Font of comment emails is rendered too large since markdown has been enabled

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1514765" target="_blank">1514765</a>] New bug comment preview broken when use_markdown is disabled</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1515144" target="_blank">1515144</a>] Prevent Google Analytics script from being loaded when DNT:1 so that Tracking Protection doesn't have to block it</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1515405" target="_blank">1515405</a>] Add rate limiting for comments and attachment accesses</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1514848" target="_blank">1514848</a>] Add utility to revoke API keys</li>
<li>[<a …

bump version to 20190108.1

---

Bugzilla/CGI.pm

I thought the crash data table was being displayed when it was deployed on the dev server, but it’s not working on the staging server now. The `frame-src` CSP is required to show the `<iframe>` properly.
Note: since the table is needed for modal *and* legacy bug pages, both `SHOW_BUG_MODAL_CSP` and `DEFAULT_CSP` have to be updated.

Bug 1493253 follow up - Set CSP for crash table iframe

---

extensions/BMO/web/js/firefox-crash-table.js

@calixteman asked me to bump the version of the crash table code to `0.4.0` so the queries can be distinguished from ones sent from the [original Firefox extension](https://github.com/mozilla/crash-stop-addon).

Bug 1493253 follow up - bump the version

---

extensions/BugModal/web/bug_modal.css

https://bugzilla.mozilla.org/show_bug.cgi?id=1518238#c0 Looks pretty weird, we should only use the 
21px line height on paragraphs. Also, I think setting a max-width on paragraphs may make sense?

only change the line-height of paragraphs

---

Bugzilla/Markdown.pm
t/markdown.t

This fixes a regression in the code that allows literal html tags.
Eventually we should remove this hack in favor of a proper extension to
libcmark-gfm

Bug 1519240 - Markdown comments ruin links wrapped in <>

---

extensions/EditComments/template/en/default/hook/global/header-start.html.tmpl
extensions/EditComments/web/js/inline-editor.js
extensions/EditComments/web/styles/inline-editor.css

Allow to preview edited comments, just like the regular comment form (or GitHub).
[Bug 1518328 - The edit comment feature should have a preview mode as well](https://bugzilla.mozilla.org/show_bug.cgi?id=1518328)

Bug 1518328 - The edit comment feature should have a preview mode as well

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1518522" target="_blank">1518522</a>] phabbugz comments in bugs need to set is_markdown to true</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1493253" target="_blank">1493253</a>] Embed crash count table to bug pages</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1518264" target="_blank">1518264</a>] New non-monospace comments styled with way too small a font size</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1500441" target="_blank">1500441</a>] Make site-wide announcement dismissable</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1519240" target="_blank">1519240</a>] Markdown comments ruin …

bump version to 20190116.1

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1518522" target="_blank">1518522</a>] phabbugz comments in bugs need to set is_markdown to true</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1493253" target="_blank">1493253</a>] Embed crash count table to bug pages</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1518264" target="_blank">1518264</a>] New non-monospace comments styled with way too small a font size</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1500441" target="_blank">1500441</a>] Make site-wide announcement dismissable</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1519240" target="_blank">1519240</a>] Markdown comments ruin …

bump version to 20190116.2

---

extensions/BMO/web/js/firefox-crash-table.js

Sorry, #1041 was incomplete. Here's the right thing to do. 😓

Bug 1520495 followup - Crash count table does not detect uplift links in Markdown comments

---

Bugzilla/Markdown.pm

Bug 1519564 followup - ensure there are never newlines in html attributes

---

template/en/default/request/queue.html.tmpl

Show **Requester** and **Requestee** emails properly on the Request Queue page, and prevent these user objects being rendered as weird hashes.
[Bug 1511261 - request queue page shows 'Bugzilla::User=HASH(...)' instead of username](https://bugzilla.mozilla.org/show_bug.cgi?id=1511261)

Bug 1511261 - request queue page shows 'Bugzilla::User=HASH(...)' instead of username

---

extensions/RequestNagger/template/en/default/email/request_nagging-user.html.tmpl
extensions/RequestNagger/template/en/default/email/request_nagging-user.txt.tmpl

Fix the link where people can opt out of request reminders.
[Bug 1520856 - "Opt out of these emails" at bottom of overdue request nagging emails doesn't open desired page](https://bugzilla.mozilla.org/show_bug.cgi?id=1520856)

Bug 1520856 - "Opt out of these emails" at bottom of overdue request nagging emails doesn't open desired page

---

extensions/FlagTypeComment/web/js/ftc.js

Use Markdown for uplift approval requests. For example, [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1520756#c8) will [looks like this](https://screenshots.firefox.com/wzGtgneN6Q6N0mMI/bmo-web.vm).
[Bug 1520533 - Utilize Markdown in uplift form comments](https://bugzilla.mozilla.org/show_bug.cgi?id=1520533)

Bug 1520533 - Utilize Markdown in uplift form comments

---

extensions/EditComments/template/en/default/hook/global/header-start.html.tmpl

Simply check if `bug` is defined. Tested with several scenarios we have encountered the issue: create a bug, update a bug, view a bug, create an attachment, and update an attachment. The only downside I could find is that the strings will also be included in the legacy bug page where comments are not editable, but given the modal bug page is default, that case can be ignored.
[Bug 1521653 - Cannot edit comments after creating or updating an attachment](https://bugzilla.mozilla.org/show_bug.cgi?id=1521653)

Bug 1521653 - Cannot edit comments after creating or updating an attachment

---

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
extensions/BugModal/template/en/default/bug_modal/new_comment.html.tmpl
extensions/BugModal/web/bug_modal.css
extensions/BugModal/web/common_bug_modal.css
extensions/EditComments/web/js/inline-editor.js
skins/standard/global.css
template/en/default/bug/comment.html.tmpl

Contains all the changes in #1027 plus fixes
- Windows users fonts were all monospace
- Preview for long comments on bug page flowed outside of the box
- @dylanwh / @kyoshino I realized that when editing an old non-markdown comment, the comment preview is rendered by /rest/bug/comment/render which always chooses to render as markdown (since it doesn't have the comment object, so it can't know whether you're editing a non-markdown comment or not). Do you guys want me to modify the api to allow a 'as_plaintext' flag or something? Dunno if that will have any repercussions down the line. Or we could pass in the comment id.

Bug 1518268 - Re-style all markdown content, consistently

---

Bugzilla/Search.pm
Bugzilla/WebService/Bug.pm
extensions/TrackingFlags/lib/Flag.pm

Two fixes here:
1. In cases where tracking flags are obviously not needed, we pass `skip_extensions`
2.  per @dklawren suggestion, in search we set a var to disable preloading

Bug 1512815 - Skip preloading tracking flags in the Bug API

---

Bugzilla.pm
Bugzilla/Config/Admin.pm
Bugzilla/Error.pm
template/en/default/global/code-error.html.tmpl
template/en/default/global/user-error.html.tmpl

This PR hooks into both the UserError and CodeError calls. If the error is happening in 'webpage' mode, we check a rate limit. If the rate limit is exceeded, we set a template var (so the template can indicate a rate limit was exceeded) and block as normal.
The default is generous, we can experiment in prod.

Bug 1520582 - Block ips of users that get too many page errors

---

Bugzilla/WebService.pm
Bugzilla/WebService/Wants.pm
t/wants.t

This should add a `$self->wants_object` to every API class, and `$self->wants_object->match(...)` should behave just like `filter_wants`, but also provides more methods for introspecting the wanted fields and types.

Bug 1512815 - add object that encapsulates the include/exclude logic.

---

extensions/FlagTypeComment/web/js/ftc.js

Fix the uplift request form doesn't work with Phabricator requests due to the Markdown syntax support added in #1055. Phabricator request attachments don't come with `<input name="markdown_off">` so trying to remove it will be a `SyntaxError`, leading to an empty comment.
[Bug 1522601 - Uplift request question and answer don't show up as comments](https://bugzilla.mozilla.org/show_bug.cgi?id=1522601)

Bug 1522601 - Uplift request question and answer don't show up as comments

---

.vscode/tasks.json
README.rst

Updates the readme to let new users know that they have to run
`start_morbo` before they can visit bmo-web.vm.
Also updates the VS Code tasks to work again.

no bug - Update README and VS Code tasks for morbo dev server

---

template/en/default/index.html.tmpl

Specify the `format` to make sure the link will always lead to the Advanced Search page. Otherwise, you’ll be taken to your last selected or default search page, e.g. Instant Search.
[Bug 1523172 - Advanced Search link on home page doesn’t always take me to Advanced Search](https://bugzilla.mozilla.org/show_bug.cgi?id=1523172)

Bug 1523172 - Advanced Search link on home page doesn’t always take me to Advanced Search

---

Bugzilla/App.pm

The STS header is set on 200's but not on other response codes such as 404s.
The intention is for this to fix that, but I've not been able to test this change.
I've got BMO to run using docker-compose but for some reason that doesnt appear to pick up any of my changes, even when I change other parts of the code that should be much more visible :/
Will happily test if someone can explain to me how I can get my local changes reflected in the docker images.
The conditions were ripped off from https://github.com/mozilla-bteam/bmo/blob/master/Bugzilla/CGI.pm#L593-L602

Bug 1523365 - Ensure all requests have the HSTS header (if configured)

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1511490" target="_blank">1511490</a>] BMO's oauth tokens should be use jwt</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1519782" target="_blank">1519782</a>] The OrangeFactor extension should link back to Intermittent Failure View using '&amp;tree=all'</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1523004" target="_blank">1523004</a>] Sort Phabricator revisions by numeric value instead of alphabetically</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1523172" target="_blank">1523172</a>] Advanced Search link on home page doesn’t always take me to Advanced Search</li>
<li>[<a …

bump version to 20190129.1

---

Bugzilla/Hook.pm
Bugzilla/Search/Quicksearch.pm
extensions/BMO/Extension.pm
extensions/TrackingFlags/Extension.pm
t/quicksearch.t

Exclude Graveyard products when no classification, product or component is specified in search terms, just like we are only searching open bugs by default. Given that there are several QuickSearch forms on the site, this will be done server side, in the BMO extension.
[Bug 1523317 - Exclude Graveyard products from QuickSearch results](https://bugzilla.mozilla.org/show_bug.cgi?id=1523317)

Bug 1523317 - Exclude Graveyard products from QuickSearch results

---

extensions/FlagTypeComment/web/js/ftc.js

Change the heading level from `<h2>` to `<h3>` and `<h3>` to `<h4>` respectively so uplift approval request comments will be a bit more readable.
[Bug 1524158 - markdown generated by approval comment form could be improved](https://bugzilla.mozilla.org/show_bug.cgi?id=1524158)

Bug 1524158 - markdown generated by approval comment form could be improved

---

extensions/BMO/Extension.pm
extensions/BMO/template/en/default/bug/create/create-blocklist.html.tmpl
extensions/BMO/template/en/default/bug/create/custom_forms.none.tmpl

We'd like a form for blocklisting bugs.
This covers the options at https://wiki.mozilla.org/Blocklisting but without plugin blocks, since these will most likely only be filed internally.

Bug 1525308 - Add a custom bug entry form for blocklisting bugs

---

Bugzilla/DB/Sqlite.pm

The latest sqlite is not compatible with the types of alter table statements we use, hence this pragma is required.

no bug - add pragma required to use latest sqlite version

---

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
extensions/BugModal/web/comments.js

Remove the CC changes, which are hidden by default, and the Show CC Changes option from the modal bug page, because CC changes are not real activities.
[Bug 1525808 - Remove CC changes from activity stream](https://bugzilla.mozilla.org/show_bug.cgi?id=1525808)

Bug 1525808 - Remove CC changes from activity stream

---

Vagrantfile

Some users have more resources to provide to the db vm and prior to this
PR there is no easy way to do so without customizing the Vagrantfile.

no bug - Parameterize vagrant db cpu and memory allocation

---

Bugzilla/App/Plugin/Glue.pm
Bugzilla/Auth.pm
Bugzilla/Auth/Login/Cookie.pm
Bugzilla/Auth/Persist/Cookie.pm
Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm
Bugzilla/User/Session.pm
Bugzilla/WebService.pm
docs/en/rst/api/core/v1/general.rst
docs/en/rst/api/core/v1/user.rst
sanitycheck.cgi
skins/standard/global.css
skins/standard/mobile.css
t/mojo-oauth2.t
template/en/default/account/auth/login.html.tmpl
template/en/default/account/prefs/sessions.html.tmpl

Remove the **Restrict this session to this IP address** option and relevant code since people are moving around more often, 2FA is enabled, less than 20% of users are enabling it, and no one actually wants it.
[Bug 1402894 - Remove "Restrict this session to this IP" option from login page](https://bugzilla.mozilla.org/show_bug.cgi?id=1402894)

Bug 1402894 - Remove "Restrict this session to this IP" option from login page

---

Bugzilla/BugMail.pm

Add See Also bugs to the Referenced Bugs section in email notifications. Tested locally with real emails. For new bugs, the `bug_id` property on `BugUrl` object can be used. For updates, parse the changes to find any Bug ID.
[Bug 1047539 - Bugmails including "See Also" bug links do not include a "Referenced Bugs" section with the summary of the other bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1047539)

Bug 1047539 - Bugmails including "See Also" bug links do not include a "Referenced Bugs" section with the summary of the other bug

---

Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm

Split from #1067 and #1084. Update the DB schema:
* Add `bug_type` column to `bug` table
* Add `default_bug_type` column to `components` table
* Add new `regressions` table with `regressed_by` and `regresses` columns

Bug 1461492/1522341 - Schema changes for Regressions & Bug Type fields

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1523317" target="_blank">1523317</a>] Exclude Graveyard products from QuickSearch results</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1512815" target="_blank">1512815</a>] Optimize Bugzilla-&gt;active_custom_fields() for CPU and memory usage</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1524174" target="_blank">1524174</a>] Redirect to show_bug.cgi after creating bug or updating a bug</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1524213" target="_blank">1524213</a>] phabricator revisions list on bug page has extra / in the revision link</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1523404" …

bump version to 20190221.1

---

extensions/BMO/template/en/default/hook/flag/type_comment-form.html.tmpl
extensions/FlagTypeComment/web/js/ftc.js
template/en/default/attachment/edit.html.tmpl

Allow to make an uplift request of multiple patches. This is done by sending API requests.
[Bug 1496207 - Allow to request uplift of multiple patches at once by adding checkboxes for other patches](https://bugzilla.mozilla.org/show_bug.cgi?id=1496207)

Bug 1496207 - Allow to request uplift of multiple patches at once by adding checkboxes for other patches

---

extensions/BMO/template/en/default/hook/flag/type_comment-form.html.tmpl
extensions/FlagTypeComment/web/js/ftc.js

A small change on top of #802. If the uplift “Needs manual test from QE,” send an API request in background to set the `qe-verify?` flag.
[Bug 1527178 - If an uplift request answers Yes to needing manual QA, automatically set the qe-verify flag](https://bugzilla.mozilla.org/show_bug.cgi?id=1527178)

Bug 1527178 - If an uplift request answers Yes to needing manual QA, automatically set the qe-verify flag

---

Bugzilla/Flag.pm
buglist.cgi
process_bug.cgi
template/en/default/flag/list.html.tmpl
template/en/default/list/edit-multiple.html.tmpl

Allow to bulk-edit bug flags on the **Change Several Bugs at Once** page.
[Bug 1502500 - Adding the qe-verify flag as an editable field when using Bugzilla's "Change Several Bugs at Once" option](https://bugzilla.mozilla.org/show_bug.cgi?id=1502500)

Bug 1502500 - Adding the qe-verify flag as an editable field when using Bugzilla's "Change Several Bugs at Once" option

---

extensions/BMO/lib/Reports/Triage.pm

Add NSPR and NSS to the default triage owner query.
[Bug 1463874 - Update Default Products and Remove Buglist Queries from triage_owners.html](https://bugzilla.mozilla.org/show_bug.cgi?id=1463874)

Bug 1463874 - Update Default Products and Remove Buglist Queries from triage_owners.html

---

Bugzilla/Search/Quicksearch.pm
template/en/default/pages/quicksearch.html.tmpl

Stop treating a word entered in the search bar as a bug alias to avoid unexpected results for users.
[Bug 1527053 - Can't search for "video" to find all relevant bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1527053)

Bug 1527053 - Can't search for "video" to find all relevant bugs

---

extensions/BugModal/web/bug_modal.css
extensions/BugModal/web/bug_modal.js

1. It should remain in the viewport even when you start scrolling. Use `position:sticky`.
2. It should remain visible for a few seconds when you reach new changes.
[Bug 1532482 - Improve “new changes since” indicator UX](https://bugzilla.mozilla.org/show_bug.cgi?id=1532482)

Bug 1532482 - Improve “new changes since” indicator UX

---

Bugzilla.pm
Bugzilla/App/Plugin/Glue.pm
Bugzilla/CGI.pm
Bugzilla/MFA.pm
Bugzilla/Search/Quicksearch.pm
attachment.cgi
chart.cgi
colchange.cgi
extensions/BMO/Extension.pm
extensions/BMO/lib/Reports/Groups.pm
extensions/BMO/lib/Reports/ReleaseTracking.pm
extensions/GuidedBugEntry/Extension.pm
extensions/Voting/Extension.pm
github.cgi
long_list.cgi
new_bug.cgi
post_bug.cgi
relogin.cgi
report.cgi
showattachment.cgi
token.cgi
userprefs.cgi
votes.cgi
xml.cgi

Make sure all the internal redirects are absolute URLs starting with the `basepath` param, which is `/` on BMO. Once this is merged, we can use pretty URLs like `/bug/1503483` or `/user/kohei`.
[Bug 1503483 - Convert redirects to absolute path](https://bugzilla.mozilla.org/show_bug.cgi?id=1503483)

Bug 1503483 - Convert redirects to absolute path

---

extensions/Gravatar/Extension.pm
extensions/Needinfo/template/en/default/bug/needinfo.html.tmpl
js/field.js
skins/standard/global.css
template/en/default/flag/list.html.tmpl
template/en/default/global/userselect.html.tmpl

* Show request count and blocking status (added to the API in #672) in user autocomplete dropdown list for the review/feedback/needinfo fields
* Show an alert if any person blocking requests is selected, and prevent the person being added to the field
* Show the gravatar for each person in the dropdown list for easier recognition
* [Bug 1477931 - Show number of review/feedback/needinfo in user autocomplete and prevent person from being added if requests are blocked](https://bugzilla.mozilla.org/show_bug.cgi?id=1477931)

Bug 1477931 - Show number of review/feedback/needinfo in user autocomplete and prevent person from being added if requests are blocked

---

docs/en/rst/api/core/v1/bug.rst

Update the [API doc](https://bmo.readthedocs.io/en/latest/api/core/v1/bug.html#get-bug) to mention that `/rest/bug?limit=0` will be defaulted to the max value, not unlimited.
[Bug 1276471 - Document that GET /rest/bug returns a maximum of $max_search_results bugs by default (default: 10000) even with limit=0](https://bugzilla.mozilla.org/show_bug.cgi?id=1276471)

Bug 1276471 - Document that GET /rest/bug returns a maximum of $max_search_results bugs by default (default: 10000) even with limit=0

---

js/attachment.js
template/en/default/attachment/createformcontents.html.tmpl

Use the latest [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) currently available in Firefox Nightly/Beta and Chrome to let users take a screenshot directly from the browser. Wow, we don’t need Java nor Flash! 🎉
Note: this API requires HTTPS 🔒 which means the local server must have a TLS certificate to test the functionality. I don’t know how to do it with Vagrant so I’m using the [Apache reverse proxy](https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html) instead.
[Bug 1391439 - Add ability to capture and attach a screenshot through the Bugzilla UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1391439)

Bug 1391439 - Add ability to capture and attach a screenshot through the Bugzilla UI

---

extensions/Gravatar/Extension.pm

Remove an unnecessary `&amp;` from the Gravatar URL generator. These URLs will be HTML-escaped in a template or script.

no-bug - Gravatar URLs are double-HTML-escaped

---

Bugzilla.pm

[release tag](https://github.com/mozilla-bteam/bmo/tree/release-20190312.1)
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=989476" target="_blank">989476</a>] A comment from a "new to bugzilla" user on a mentored [good-first-bug] should trip the needinfo flag.</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1529985" target="_blank">1529985</a>] "Phabricator Revisions" section of bug is stuck at "Loading...." due to typo in phabricator.js</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1496207" target="_blank">1496207</a>] Allow to request uplift of multiple patches at once by adding checkboxes for other patches</li>
<li>[<a …

bump version to 20190312.1

---

scripts/generate_bmo_data.pl

Update the Primary field sort key in the BMO data generation script to make P1 the highest. BMO production has already been updated by Emma through the admin page.
[Bug 1535075 - Change sort key for Priority so P1 will be first when sorting bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1535075)

Bug 1535075 - Change sort key for Priority so P1 will be first when sorting bugs

---

Bugzilla/WebService/Bug.pm
docs/en/rst/api/core/v1/bug.rst
docs/en/rst/api/core/v1/comment.rst
extensions/EditComments/Extension.pm

* Allow to retrieve comments, attachments and history at once with `/rest/bug/[ID]?include_fields=attachments,comments,history`, just like the legacy BzAPI.
* Moved the Comment object’s `raw_text` field from the EditComments extension to core, so `/rest/bug/[ID/comment` and `/rest/bug/[ID]?include_fields=comments` will be consistent. Otherwise it would require an explicit field option like `/rest/bug/[ID]?include_fields=comments,raw_text`.
* Update relevant docs.
[Bug 994896 - Add the ability to get comments, attachments, and history using Bug.get](https://bugzilla.mozilla.org/show_bug.cgi?id=994896)

Bug 994896 - Add the ability to get comments, attachments, and history using Bug.get

---

extensions/Splinter/template/en/default/hook/attachment/edit-action.html.tmpl
extensions/Splinter/template/en/default/hook/attachment/list-action.html.tmpl
extensions/Splinter/template/en/default/pages/splinter.html.tmpl

Remove the Splinter Review support for GitHub pull requests, which are currently showing “ Splinter Review” link on the attachment list.
[Bug 1286448 - Remove Splinter Review for GitHub PRs](https://bugzilla.mozilla.org/show_bug.cgi?id=1286448)

Bug 1286448 - Remove Splinter Review for GitHub PRs

---

extensions/BMO/Extension.pm
extensions/BMO/lib/Data.pm
extensions/BMO/template/en/default/bug/create/create-blocklist.html.tmpl

Show the [custom blocklist form](https://bugzilla.mozilla.org/form.blocklist) when users are visiting the [Toolkit :: Blocklist Policy Requests bug report page](https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Blocklist%20Policy%20Requests). Add a link to “Switch to the standard bug entry form” to the bottom of the page.
[Bug 1535498 - Go directly to the blocklisting form when selecting blocklist policy requests on the enter_bug page.](https://bugzilla.mozilla.org/show_bug.cgi?id=1535498)

Bug 1535498 - Go directly to the blocklisting form when selecting blocklist policy requests on the enter_bug page.

---

Bugzilla/Bug.pm

Remove an extra space from bug activities, which could be seen when the change set is corrupted.

Bug 1513956 - The summary in the history contains additional white spaces

---

Bugzilla/WebService/Bug.pm
docs/en/rst/api/core/v1/attachment.rst

Add `creator_detail` to [/rest/bug/(id)/attachment](https://bmo.readthedocs.io/en/latest/api/core/v1/attachment.html#get-attachment) like `creator_detail` in [/rest/bug/(id)](https://bmo.readthedocs.io/en/latest/api/core/v1/bug.html#get-bug). We don’t need `attacher_detail` because `attacher` is an alias for backward compatibility.

Bug 1537012 - Add creator_detail field to Get Attachment API

---

extensions/BugModal/web/bug_modal.css

Let users scroll the lightbox overlay when images are larger than the viewport.
[Bug 1535191 - Can't scroll attachments in lightbox view](https://bugzilla.mozilla.org/show_bug.cgi?id=1535191)

Bug 1535191 - Can't scroll attachments in lightbox view

---

Bugzilla/WebService/User.pm

So the most active users will be at the top of the list.
[Bug 1536279 - Sort suggested users by last seen date, not last login date](https://bugzilla.mozilla.org/show_bug.cgi?id=1536279)

Bug 1536279 - Sort suggested users by last seen date, not last login date

---

Bugzilla/Util.pm

Correct bad charset detection for plain text files.
[Bug 1538047 - Plain text attachment cut off due to wrong charset detection (UTF-8 as Windows-1252)](https://bugzilla.mozilla.org/show_bug.cgi?id=1538047)

Bug 1538047 - Plain text attachment cut off due to wrong charset detection (UTF-8 as Windows-1252)

---

template/en/default/reports/email/security-risk.html.tmpl

It is possible for the history shown in the security bugs report to
change from report to report under rare conditions. This commit adds
a small notice to make users aware of this.

Bug 1538712 - Add note about rare history change to secbugs report

---

Bugzilla/Report/SecurityRisk.pm

WIP: Gonna further test this fix and add a unit test for it.
This should fix the problems that dveditz and others have been reporting with the secbugs report
where bugs that have been marked as verified don't always have their histories replayed correctly.
The root cause here is the use of `dbh->selectall_hashref`. This method is used to ensure that the
results from the SQL query are mapped to their corresponding column names in a hash for easy access.
But, since the key of the hashmap is the bug id it appears that only the last event for that bug id
is returned. This went unnoticed because the SQL queries were returning the proper data (all events)
and in my testing when I set a bug as resolved that most often was the last event on that bug so it's
history would replay correctly during …

Bug 1539442 - Fix secbugs event builder to get more than the lastest event

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1535075" target="_blank">1535075</a>] Change sort key for Priority so P1 will be first when sorting bugs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=994896" target="_blank">994896</a>] Add the ability to get comments, attachments, and history using Bug.get</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1535376" target="_blank">1535376</a>] add support for upstream phabricator to the see-also fields</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1286448" target="_blank">1286448</a>] Remove Splinter Review for GitHub PRs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1535498" …

bump version to 20190329.1

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1535075" target="_blank">1535075</a>] Change sort key for Priority so P1 will be first when sorting bugs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=994896" target="_blank">994896</a>] Add the ability to get comments, attachments, and history using Bug.get</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1535376" target="_blank">1535376</a>] add support for upstream phabricator to the see-also fields</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1286448" target="_blank">1286448</a>] Remove Splinter Review for GitHub PRs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1535498" …

bump version to 20190329.2

---

extensions/BMO/template/en/default/hook/flag/type_comment-form.html.tmpl
extensions/FlagTypeComment/web/js/ftc.js
template/en/default/flag/list.html.tmpl

#802 didn’t work properly 😞
* The flag IDs set up locally and coded in the uplift template were wrong, because these were copy & pasted from the UI which included **non-breaking hyphens**. So you’ve got a “flag not found” API error due to an ID mismatch. Remove the unnecessary `no_break` filter and fix the template.
* Remove the unnecessary question “Do you want to request approval of these patches as well?” from the comment body.

Bug 1539849 - Multiple uplift request is not working as expected

---

Bugzilla/Bug.pm
Bugzilla/WebService/BugUserLastVisit.pm
Bugzilla/WebService/Constants.pm
extensions/BugModal/template/en/default/bug_modal/header.html.tmpl
template/en/default/bug/show-header.html.tmpl
template/en/default/global/user-error.html.tmpl

[Update the last-visited time for the specified bug and current user](https://bmo.readthedocs.io/en/latest/api/core/v1/bug-user-last-visit.html#update-last-visited) even if the user is not directly involved in. This change allows to enhance the UX, like
* Show the new comments/changes indicator on any bug
* Highlight any bug updated since last visit (like GitHub issue list)
* Search any recently visited bug from the quick search bar (#778)
* Style any visited bug reliably among multiple devices
[Bug 1481106 - Start logging bug_user_last_visit for all visited bugs even if the user is not involved](https://bugzilla.mozilla.org/show_bug.cgi?id=1481106)

Bug 1481106 - Start logging bug_user_last_visit for all visited bugs even if the user is not involved

---

extensions/BugModal/web/bug_modal.js
js/flag.js
qa/t/test_flags.t
qa/t/test_flags2.t

When `needinfo` or any other “specifically requestable” flag is changed to `?`, make the corresponding requestee field required.
[Bug 1453272 - Don't set specifically requestable flags, including needinfo, when it's empty](https://bugzilla.mozilla.org/show_bug.cgi?id=1453272)

Bug 1453272 - Don't set specifically requestable flags, including needinfo, when it's empty

---

Bugzilla/CGI.pm
extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
extensions/BugModal/web/bug_modal.css
extensions/BugModal/web/comments.js
js/global.js
skins/standard/global.css

* Load text files via REST API and render safely without `connect-src` CSP
* Make sure the Prism.js works properly
* Make sure not to load GitHub and Phab requests
* Stop showing deleted attachments mainly on Firefox OS bugs
* Add `media-src` for `<video>`/`<audio>` attachments so these can be loaded from bmoattachments.org
[Bug 1535190 - Inline attachments: remove text support and hide deleted ones](https://bugzilla.mozilla.org/show_bug.cgi?id=1535190)

Bug 1535190 - Make sure inline attachments are displayed properly

---

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
extensions/BugModal/template/en/default/bug_modal/header.html.tmpl
extensions/BugModal/web/bug_modal.css
extensions/BugModal/web/comments.js

Hide inline attachments if the bug has any of sensitive keywords or the comment has `hide-attachment` tag, because some images are known to hang the browser.
[Bug 1535723 - Don't show inline attachments for bugs that have the keywords "hang", "assertion", or "crash"](https://bugzilla.mozilla.org/show_bug.cgi?id=1535723)

Bug 1535723 - Don't show inline attachments for bugs that have the keywords "hang", "assertion", or "crash"

---

skins/standard/global.css

A [feedback](https://twitter.com/nicolaschevobbe/status/1111529317828382722) from @nchevobbe. This overrides the following rule that can be eventually removed once we get rid of all the `<hr>` from templates.
```css
#changeform hr {
display: none;
}
```

no bug - Show <hr> in Markdown comments

---

extensions/BMO/template/en/default/account/create.html.tmpl

I suspect this is one of the ways people are finding our email address.

no bug - remove explicit mention of the bugzilla admin email address

---

Bugzilla/WebService/User.pm
js/field.js
skins/standard/global.css

Revert #946 so the enhanced user autocomplete added in #684 can load both `gravatar` and `requests` via `/user/suggest` API. Both fields are provided by an extension, so the feature doesn’t work without this backout. I don’t see any performance difference on my local server with a production DB snapshot.
[Bug 1477931 - Show number of review/feedback/needinfo in user autocomplete and prevent person from being added if requests are blocked](https://bugzilla.mozilla.org/show_bug.cgi?id=1477931)

Bug 1477931 follow-up - Make sure Gravatar and requests are loaded via API

---

.circleci/config.yml
Bugzilla/App/Command/report_ping.pm
Bugzilla/Model/Result/Bug.pm
Bugzilla/Model/Result/Dependency.pm
Bugzilla/Model/Result/Duplicate.pm
Bugzilla/Model/Result/Flag.pm
Bugzilla/Model/Result/User.pm
Bugzilla/Report/Ping.pm
Bugzilla/Report/Ping/Simple.pm
Bugzilla/Types.pm
Dockerfile
Makefile.PL
t/report-ping-simple.t

This is the current expanded schema. I'd like to know what additional fields we want before I start the process of getting it signed off. @psiinon  @mars-f 
If the below is too verbose, consider looking at [the source](https://github.com/mozilla-bteam/bmo/blob/368fa33a172352c9c7681448934509a8ed5bbc67/Bugzilla/Report/Ping/Simple.pm#L23-L31) which is defined using [joi](https://github.com/hapijs/joi)
```json
{
"additionalProperties" : false,
"properties" : {
"bug_id" : {
"minimum" : 1,
"type" : "integer"
},
"bug_status" : {
"type" : "string"
},
"groups" : {
"items" : {
"type" : "string"
},
"type" : "array"
},
"keywords" : {
"items" : {
"type" : "string"
},
"type" : "array"
},
"priority" : {
"type" : "string"
},
"resolution" : {
"type" : "string"
},
"severity" : {
"type" : "string"
}
}, …
```

Bug 1506144 - Access bugzilla security bug metadata via STMO

---

extensions/BMO/Extension.pm
extensions/BMO/bin/migrate-bug-type.pl

* Allow to read a bug type migration list generated by [bugbug](https://github.com/mozilla/bugbug). @marco-c will give us the latest file later.
* Run it with `perl extensions/BMO/bin/migrate-bug-type.pl --csv=bugbug_results.csv`. It took <2 minutes on my VM.
* Set the file permission properly.
[Bug 1522348 - Bulk assign open bugs to task, enhancement, defect field](https://bugzilla.mozilla.org/show_bug.cgi?id=1522348)

Bug 1522348 part 2 - Add support for bugbug-generated bug list

---

Bugzilla/Attachment.pm
js/attachment.js
template/en/default/attachment/createformcontents.html.tmpl

Add “hide preview” checkbox to the New Attachment that forces the `application/octet-stream` binary content type.
[Bug 1538383 - Allow to hide inline preview when attaching a file, e.g. SVG crashtests.](https://bugzilla.mozilla.org/show_bug.cgi?id=1538383)

Bug 1538383 - Allow to hide inline preview when attaching a file, e.g. SVG crashtests.

---

Bugzilla/Search.pm
Bugzilla/Search/Quicksearch.pm
Bugzilla/WebService/Bug.pm
docs/en/rst/api/core/v1/bug.rst
template/en/default/pages/quicksearch.html.tmpl
template/en/default/search/form.html.tmpl

* Add a checkbox to the Advanced Search page, which allows to search only in bug description (initial comment)
* Add the `++description` shortcut for Quick Search that enables description search
* Add the `description` field to the [Get Bug API](https://bmo.readthedocs.io/en/latest/api/core/v1/bug.html#get-bug). Unlike #670,
* It returns comment body text, not a comment object
* It requires `description` or `_extra` in `include_fields`
* Add the `description` field to the [Search Bugs API](https://bmo.readthedocs.io/en/latest/api/core/v1/bug.html#search-bugs), which also allows to search only in bug description
* Update the docs
[Bug 1531757 - Allow to search only in bug description (comment 0) with both Quick and Advenced Search as well as …

Bug 1531757 - Allow to search only in bug description (comment 0) with both Quick and Advenced Search as well as API

---

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/template/en/default/bug_modal/tracking_flags.html.tmpl

Link keywords and status/tracking flags on the modal bug page to the relevant search results page for faster access.
[Bug 1539941 - Link keywords and flags in bug detail to searches (and later graphing)](https://bugzilla.mozilla.org/show_bug.cgi?id=1539941)

Bug 1539941 - Link keywords and flags in bug detail to searches (and later graphing)

---

extensions/BMO/lib/Reports/Triage.pm
extensions/BMO/template/en/default/pages/triage_owners.html.tmpl
extensions/BMO/web/styles/triage_reports.css

Update the [Triage Owners](https://bugzilla.mozilla.org/page.cgi?id=triage_owners.html) page to add bug counts by type. Also improve the style (sticky table header) and markup.
[Bug 1541111 - Separate bugs on Triage Owners page by type](https://bugzilla.mozilla.org/show_bug.cgi?id=1541111)

Bug 1541111 - Separate bugs on Triage Owners page by type

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/web/bug_modal.js
skins/standard/global.css

Add Permanent Edit Mode to the modal bug page, that can be toggled in the page menu next to the Follow button. In the near future, I’d like to have a rethink about how the modal UI works. In the meantime, the option is stored only in the browser’s local storage, not in Bugzilla’s user preferences.
[Bug 1281200 - New show_bug.cgi view should have an option to have fields editable by default.](https://bugzilla.mozilla.org/show_bug.cgi?id=1281200)

Bug 1281200 - New show_bug.cgi view should have an option to have fields editable by default.

---

Bugzilla/Template.pm
extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
template/en/default/bug/activity/table.html.tmpl

Use aliases, if available, for the history of bug list fields like Blocks and Regressions. The same applies to the See Also field that currently shows a bug ID prefixed with “bug”. This PR makes change to both the inline history on the modal bug page and the history page.
[Bug 1071066 - For bugs with aliases, inline history displays the bug number rather than the bug alias](https://bugzilla.mozilla.org/show_bug.cgi?id=1071066)

Bug 1071066 - For bugs with aliases, inline history displays the bug number rather than the bug alias

---

Bugzilla/WebService/Bug.pm

Use `Bugzilla::Bug->new()` in the bug comment and history APIs so any private bug won’t be throwing but simply skipped.
I have just noticed that `/rest/bug` supports the experimental, undocumented `permissive` param that returns an error object rather than skipping private bugs. The param is apparently not working for some reason, but this should be the default behaviour in our next generation API. I’m *not* adding the param to the comment and history APIs this time.
[Bug 1283392 - Query for history or comment containing private bug id should return no data for this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1283392)

Bug 1283392 - Query for history or comment containing private bug id should return no data for this bug

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/web/bug_modal.js

Show the “including you” label on the modal UI’s CC field just like the legacy UI. The current state is inconsistent because it says “Just you” if only you’re CCed.
[Bug 1344427 - Display "nn people including you" if current user is cc'ed on a bug.](https://bugzilla.mozilla.org/show_bug.cgi?id=1344427)

Bug 1344427 - Display "nn people including you" if current user is cc'ed on a bug.

---

extensions/FlagTypeComment/web/js/ftc.js

'?' is used ask the dev to asses whether to uplift but that's what the form is already doing.

Bug 1541582 - Set qe-verify to + when manual QA requested upon uplift

---

extensions/BugModal/web/bug_modal.js

Hide the “1 new change since last visit“ notification bar on the modal bug page if the change was made by yourself.
[Bug 1541123 - "1 new change since last visit" shown for the change I just submitted](https://bugzilla.mozilla.org/show_bug.cgi?id=1541123).

Bug 1541123 - "1 new change since last visit" shown for the change I just submitted

---

extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
extensions/BugModal/web/comments.js

Fix Phablicator requests with a description ending with `.js` or any source extension being displayed as a text attachment.
[Bug 1541231 - Certain Phablicator requests are displayed as inline attachment](https://bugzilla.mozilla.org/show_bug.cgi?id=1541231)

Bug 1541231 - Certain Phablicator requests are displayed as inline attachment

---

extensions/BMO/template/en/default/hook/flag/type_comment-form.html.tmpl

Once the **Regressed by** field is added, the **Feature/Bug causing the regression** custom field can be removed from the uplift approval request comment. Blocked until #1067 is merged.
[Bug 1152434 - Remove regressing bug ID field from uplift approval request once regressed-by field is added](https://bugzilla.mozilla.org/show_bug.cgi?id=1152434)

Bug 1152434 - Remove regressing bug ID field from uplift approval request once regressed-by field is added

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
skins/standard/global.css

People confuse the bug type label with bug status, so this PR removes the label from the modal bug header and instead shows it in the Status module. Also change the icon and colour of the defect and enhancement types.
[Bug 1541484 - Move the bug type from header to module and de-emphasize it so it’s not confused with bug status](https://bugzilla.mozilla.org/show_bug.cgi?id=1541484)

Bug 1541484 - Move the bug type from header to module and de-emphasize it so it’s not confused with bug status

---

Bugzilla/Template.pm
extensions/BMO/template/en/default/global/choose-product.html.tmpl
extensions/BMO/template/en/default/pages/triage_reports.html.tmpl
extensions/BMO/template/en/default/pages/user_activity.html.tmpl
extensions/BMO/web/styles/reports.css
extensions/BMO/web/styles/triage_reports.css
extensions/BugModal/template/en/default/bug_modal/flags.html.tmpl
extensions/BugModal/web/bug_modal.css
extensions/BugmailFilter/template/en/default/account/prefs/bugmail_filter.html.tmpl
extensions/BugmailFilter/web/style/bugmail-filter.css
extensions/GuidedBugEntry/template/en/default/guided/guided.html.tmpl
extensions/MyDashboard/template/en/default/pages/mydashboard.html.tmpl
extensions/MyDashboard/web/styles/mydashboard.css
skins/standard/global.css
template/en/default/admin/flag-type/list.html.tmpl
template/en/default/attachment/list.html.tmpl
template/en/default/bug/show-multiple.html.tmpl
template/en/default/flag/list.html.tmpl
template/en/default/global/choose-product.html.tmpl
template/en/default/global/header-search-dropdown.html.tmpl

Non-breaking hyphens make it difficult to find and copy actual flag names, etc. on the UI. Replace all of them with CSS `white-space: nowrap` to avoid issues like #1177 in the future.
[Bug 1539908 - Replace no_break filter with CSS nowrap](https://bugzilla.mozilla.org/show_bug.cgi?id=1539908)

Bug 1539908 - Replace no_break filter with CSS nowrap

---

extensions/BugModal/web/comments.js

Hide inline attachments on security bugs in case any corrupted/malformed image is attached.
[Bug 1542882 - Don't do image preview on security bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1542882)

Bug 1542882 - Don't do image preview on security bugs

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/template/en/default/bug_modal/field.html.tmpl
extensions/BugModal/web/bug_modal.css
extensions/BugModal/web/bug_modal.js
qa/t/test_bug_edit.t
qa/t/test_custom_fields.t
skins/standard/enter_bug.css
skins/standard/global.css
template/en/default/bug/create/create.html.tmpl
template/en/default/bug/field-label.html.tmpl
template/en/default/bug/field.html.tmpl

* Use a radio button UI for the Type field, instead of a dropdown list, just like the selectors in the [uplift request form](https://release.mozilla.org/tooling/bugzilla/2018/10/03/uplift-form.html).
* Apply the change to both the Enter Bug page and modal bug page.
* The change improves the UX and further encourages people to use/correct the type field.
* Incorporate #1190. (no change after all)
[Bug 1541133 - Bug type field should be a radio button](https://bugzilla.mozilla.org/show_bug.cgi?id=1541133)

Bug 1541133 - Bug type field should be a radio button

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/template/en/default/bug_modal/field.html.tmpl
extensions/BugModal/web/bug_modal.css

Show Depends on, Blocks and other bug IDs fields by bug type. For example, [Bug 1451850](https://bugzilla.mozilla.org/show_bug.cgi?id=1451850) will look like this:
[Bug 1527459 - Display dependency bugs by type, using the same colour/icon for each](https://bugzilla.mozilla.org/show_bug.cgi?id=1527459)

Bug 1527459 - Display dependency bugs by type, using the same colour/icon for each

---

extensions/MyDashboard/lib/Queries.pm
extensions/MyDashboard/web/js/query.js
extensions/MyDashboard/web/styles/mydashboard.css

Add the Type column to the “big query table” on My Dashboard.
[Bug 1531481 - Add bug type labels to My Dashboard](https://bugzilla.mozilla.org/show_bug.cgi?id=1531481)

Bug 1531481 - Add bug type labels to My Dashboard

---

extensions/BMO/lib/Reports/Triage.pm

Fix the [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1543127#c3) found by @purelogiq while testing the [Triage Owners page on the dev server](https://bugzilla-dev.allizom.org/page.cgi?id=triage_owners.html). If any predefined product, DevTools in this case, cannot be found in the database, simply skip it instead of throwing. You can test this by adding a fake product to the `DEFAULT_OWNER_PRODUCTS` list in `Triage.pm`.

no bug - Fix Triage Owner list throwing if predefined product is not found

---

Bugzilla/App.pm
Bugzilla/App/CGI.pm
Bugzilla/App/Plugin/Glue.pm
Bugzilla/CGI.pm
Bugzilla/CGI/ContentSecurityPolicy.pm
Bugzilla/Constants.pm
Bugzilla/Template.pm
attachment.cgi
chart.cgi
index.cgi
post_bug.cgi
process_bug.cgi
report.cgi
show_bug.cgi
template/en/default/global/header.html.tmpl
xmlrpc.cgi

This patch moves the code that sets most of the important headers out of the `Bugzilla::CGI` class and into the mojolicious `after_dispatch` hook. This means it will be run after (nearly all) requests. Some other code had to move (`url_is_attachment_base`) into helpers and the CSP functions are moved to the constants module (though this is not ideal).
This fixes a regression where the bugzilla index didn't set security headers.
Thanks to @claudijd for reporting this.

make it so the security headers are always set.

---

Bugzilla.pm
post_bug.cgi

A fallout from #1218. Fix the following error raised when you submit a new bug:
> Can't locate object method "content_security_policy" via package "Bugzilla::CGI" at post_bug.cgi line 307.
**But there's still another problem**: the new bug's title will be undefined, and the browser console also says:
> TypeError: BUGZILLA.user.settings is undefined

no bug - Fix missing object error when submitting new bug

---

extensions/BMO/bin/migrate-bug-type.pl

Fix bugs in the type migration script. This and a [follow-up SQL](https://gist.github.com/kyoshino/05c966dd40cb9d22a95e6c5b317d6f2f) were already run, so the change just is for future reference.
[Bug 1541303 - Default component bug type is not set as expected; enhancement severity is still used for existing bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1541303)

Bug 1541303 - Default component bug type is not set as expected; enhancement severity is still used for existing bugs

---

enter_bug.cgi

Fix a cloned bug wrongly adding the original bug to the Regressed by field.
[Bug 1543760 - When cloning a bug, the bug is added to 'Regressed by' of the new bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1543760)

Bug 1543760 - When cloning a bug, the bug is added to 'Regressed by' of the new bug

---

extensions/BugModal/web/bug_modal.css

Add a strike-through to obsolete inline attachment links on the modal bug page. Plus, fix the font weight (a fallout from #1203).
[Bug 1543718 - Obsolete attachments should have a strikethrough](https://bugzilla.mozilla.org/show_bug.cgi?id=1543718)

Bug 1543718 - Obsolete attachments should have a strikethrough

---

extensions/BMO/Extension.pm
extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/ComponentWatching/Extension.pm
template/en/default/attachment/create.html.tmpl

Prevent the Unassigned label from being displayed for email addresses ending with `@invalid.bugs`. Other default assignees like `administration@bugzilla.bugs` will still be displayed as Unassigned.
[Bug 1543798 - Do not treat email addresses with invalid.bugs as unassigned when displaying bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1543798)

Bug 1543798 - Do not treat email addresses with invalid.bugs as unassigned when displaying bugs

---

extensions/BugModal/web/comments.js
extensions/FlagTypeComment/web/js/ftc.js

Properly escape user-defined attachment names inserted dynamically into the attachment preview and uplift request form. Also checked other uses cases of `insertAdjacentHTML()`.
[Bug 1544304 - Wrong escaping of quotes in attachment titles.](https://bugzilla.mozilla.org/show_bug.cgi?id=1544304)

Bug 1544304 - Wrong escaping of quotes in attachment titles.

---

Bugzilla/Auth/Login/APIKey.pm
Bugzilla/User/APIKey.pm
docs/en/rst/using/preferences.rst
template/en/default/account/prefs/apikey.html.tmpl
userprefs.cgi

It's been requested that an API key for a service owned by @calixteman be accessible from only a single source. This is presumably to hedge against the risk of the key leaking.
We already store the IP that last used an API key, so it seems easiest to add a "sticky" bit that makes the key not work when the IP doesn't match the previous one.
This PR adds the "sticky" column, and if the `last_used_ip` is set (e.g. the API key has been used) it can't be used from another IP. The sticky bit cannot be unset.

Bug 1541555 - Add facility for requiring an API Key to always come from the same IP address

---

extensions/BMO/template/en/default/bug/create/create-blocklist.html.tmpl

For testing you will need to create the following:
Product: Toolkit
Component: Blocklist Policy Requests
Group: blocklist-requests 
And set blocklist-requests to SHOWN/SHOWN for product Toolkit access controls.

Bug 1543163 - Make Toolkit :: Blocklist Policy Request component private by default

---

Bugzilla.pm

[release tag](https://github.com/mozilla-bteam/bmo/tree/release-20190418.1)
<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1541303" target="_blank">1541303</a>] Default component bug type is not set as expected; enhancement severity is still used for existing bugs</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1543760" target="_blank">1543760</a>] When cloning a bug, the bug is added to 'Regressed by' of the new bug</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1543718" target="_blank">1543718</a>] Obsolete attachments should have a strikethrough</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1543798" target="_blank">1543798</a>] Do not treat email addresses …

Bump version to 20190418.1

---

extensions/BugModal/template/en/default/bug_modal/field.html.tmpl
extensions/BugModal/web/bug_modal.css

Make the bug links on the Depends on, Blocks, Regressions, Regressed by fields visible even while editing the bug, just like the non-modal UI. This is a temporary workaround so we can disable the legacy UI sooner. I’ll create a [better UI](https://bugzilla.mozilla.org/show_bug.cgi?id=1539271) for these fields in the near future.
[Bug 1345750 - "Depends on" and "Blocks" bug lists should still show list of bug links in edit mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1345750)

Bug 1345750 - "Depends on" and "Blocks" bug lists should still show list of bug links in edit mode

---

extensions/BMO/lib/Data.pm

Reported by @calixteman: The Taskcluster product should display the Crash Signature field. For example, both [Bug 1544536](https://bugzilla.mozilla.org/show_bug.cgi?id=1544536) and [Bug 1540280](https://bugzilla.mozilla.org/show_bug.cgi?id=1540280) have a signature provided by the relman bot, but the field is not visible.

no bug - Show Crash Signature field on Taskcluster bugs

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl

Use the current bug’s component by default when you clone a bug. Users can change the component on the Enter Bug page if needed. The same applies to the “blocks”, “depends on” and “is regressed by” actions.
[Bug 1544059 - Cloning a bug as a blocker doesn't copy the 'component' field](https://bugzilla.mozilla.org/show_bug.cgi?id=1544059)

Bug 1544059 - Cloning a bug as a blocker doesn't copy the 'component' field

---

Bugzilla/Bug.pm

Properly check for the bug type defined at not only the instance level but also the component and product level when a new bug is filed without a user-defined type.
[Bug 1543741 - Blocklist requests getting filed as 'defect' instead of 'task' because of custom form](https://bugzilla.mozilla.org/show_bug.cgi?id=1543741)

Bug 1543741 - Blocklist requests getting filed as 'defect' instead of 'task' because of custom form

---

template/en/default/bug/create/create.html.tmpl

When the URL query param for `enter_bug.cgi` contains `bug_type`, respect it instead of the predefined per-component type.
[Bug 1543456 - Keep bug type passed to enter_bug.cgi via query even after component is selected](https://bugzilla.mozilla.org/show_bug.cgi?id=1543456)

Bug 1543456 - Keep bug type passed to enter_bug.cgi via query, including cloned bug, even after component is selected

---

extensions/BugModal/lib/ActivityStream.pm
extensions/BugModal/template/en/default/bug_modal/activity_stream.html.tmpl
extensions/EditComments/template/en/default/hook/bug_modal/activity_stream-comment_action.html.tmpl
extensions/EditComments/template/en/default/pages/comment-revisions.html.tmpl
extensions/EditComments/web/js/inline-editor.js
extensions/EditComments/web/styles/revisions.css
skins/standard/global.css

Show empty descriptions (comment 0) with a placeholder “No description provided” and let the user edit the content later if needed. This is the same behaviour as GitHub issues.
[Bug 1544132 - Allow editing empty Descriptions](https://bugzilla.mozilla.org/show_bug.cgi?id=1544132)

Bug 1544132 - Allow editing empty Descriptions

---

extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl

Fix a regression in the modal UI where the Dependency Tree link is not linked if there’s only one dependency bug, e.g. [Bug 1465851](https://bugzilla.mozilla.org/show_bug.cgi?id=1465851).
[Bug 1546774 - Show Dependency Tree link even if there’s only one bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1546774)

Bug 1546774 - Show Dependency Tree link even if there’s only one bug

---

Bugzilla/Search.pm
template/en/default/global/field-descs.none.tmpl
template/en/default/list/list.html.tmpl
template/en/default/search/boolean-charts.html.tmpl

Allow to search
> (field name) / ever changed
in Custom Search as a shortcut for 
> (field name) / changed after / 1970-01-01
[Bug 1546624 - Add a 'everchanged' operator](https://bugzilla.mozilla.org/show_bug.cgi?id=1546624)

Bug 1546624 - Add a 'everchanged' operator

---

Bugzilla/BugUrl/Bugzilla/Local.pm
Bugzilla/Template.pm
extensions/BugModal/template/en/default/bug_modal/edit.html.tmpl
extensions/BugModal/template/en/default/bug_modal/field.html.tmpl
extensions/BugModal/web/bug_modal.css

Show bugs in the See Also field by type, just like dependency and regression fields. Show external links separately in a pretty format (that applies to the URL field as well). #1187 merges these fields into the same References module.
[Bug 1546146 - Show bug types in See Also](https://bugzilla.mozilla.org/show_bug.cgi?id=1546146)

Bug 1546146 - Show bug types in See Also

---

extensions/Review/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl
skins/standard/enter_bug.css
template/en/default/bug/create/create.html.tmpl

* Remove the necessary **Reporter** name
* Hide the **Severity** field by default just like **Priority**
* Hide the **Mentors** custom field as well
[Bug 1543438 - Enter Bug page: Hide Severity and Mentors as advanced fields](https://bugzilla.mozilla.org/show_bug.cgi?id=1543438)

Bug 1543438 - Enter Bug page: Hide Severity and Mentors as advanced fields

---

Bugzilla/Search.pm
docs/en/rst/using/finding.rst

* Add `%self%` as an alias of `%user%` pronoun
* Add `%triageowner%` pronoun
* Make pronoun substitutions work with Flag Setter/Requestee fields
* Update the document
[Bug 1543189 - Add search pronouns: %triageowner% and %self%](https://bugzilla.mozilla.org/show_bug.cgi?id=1543189)

Bug 1543189 - Add search pronouns: %triageowner% and %self%

---

Bugzilla/Component.pm
Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm
Bugzilla/Product.pm
Bugzilla/WebService/Product.pm
docs/en/rst/api/core/v1/product.rst
editproducts.cgi
template/en/default/admin/components/edit-common.html.tmpl
template/en/default/admin/default_select.html.tmpl
template/en/default/admin/products/edit-common.html.tmpl
template/en/default/admin/products/list.html.tmpl
template/en/default/admin/products/updated.html.tmpl

Add the `default_bug_type` field to products that can be overridden by each component, which already has the same field. Will send a separate scheme-only PR once reviewed.
[Bug 1541617 - Allow Products to set a default bug type.](https://bugzilla.mozilla.org/show_bug.cgi?id=1541617)

Bug 1541617 - Allow Products to set a default bug type.

---

skins/standard/global.css

Apply CSS `max-height` to Markdown code blocks so [long intermittent log](https://github.com/mozilla/treeherder/pull/4888) and other snippets can be scrolled easily both in vertically and horizontally.
[Bug 1547098 - Limit the height of code in Markdown so the horizontal scrollbar can be found and used easily](https://bugzilla.mozilla.org/show_bug.cgi?id=1547098)

Bug 1547098 - Limit the height of code in Markdown so the horizontal scrollbar can be found and used easily

---

extensions/BugModal/web/bug_modal.js

Improve the behaviour of replying to a Markdown comment, making it consistent with older non-Markdown comments.
[Bug 1535574 - Reply to Markdown comment adds extra line above quoted text but not below](https://bugzilla.mozilla.org/show_bug.cgi?id=1535574)

Bug 1535574 - Reply to Markdown comment adds extra line above quoted text but not below

---

Bugzilla/Report/SecurityRisk.pm
scripts/secbugsreport.pl

Prior to this commit the report could specify a date to base the report
of off, but, it didn't accept a time (hour, min, second).
With this commit the report can be based on the exact day and time it
was run instead of just 0000 UTC of the specified date.
E.g. secbugsreport.pl $(date +'%Y %m %d %H %M %S %z').

Bug 1546444 - Parameterize time that the security bugs report uses

---

extensions/BugModal/web/comments.js

Prevent attachments from being previewed when it’s marked as binary, even if the content is plaintext. This should have been included in #1168.
[Bug 1547714 - Attachment with application/octet-stream MIME type should not be previewed even if it’s actually text file](https://bugzilla.mozilla.org/show_bug.cgi?id=1547714)

Bug 1547714 - Attachment with application/octet-stream MIME type should not be previewed even if it’s actually text file

---

Bugzilla/UserAgent.pm

Detect `x64` UA strings properly as a 64-bit platform, just like `x86_64`.
[Bug 1549007 - "From Reporter" populates 64-bit Windows 8.1 as x86](https://bugzilla.mozilla.org/show_bug.cgi?id=1549007)

Bug 1549007 - "From Reporter" populates 64-bit Windows 8.1 as x86

---

extensions/BugModal/web/bug_modal.js

Remove `pageshow` event handlers that lead to the unexpected behaviour.
[Bug 1550439 - Type is reset on hard-refresh with "Always Enable Edit Mode”](https://bugzilla.mozilla.org/show_bug.cgi?id=1550439)

Bug 1550439 - Type is reset on hard-refresh with "Always Enable Edit Mode"

---

extensions/BugModal/web/comments.js

Show and syntax-highlight the preview of text files only when the size is under 50 KB.
[Bug 1546877 - Slow Script warning on bugzilla page when loading preview of large json file](https://bugzilla.mozilla.org/show_bug.cgi?id=1546877)

Bug 1546877 - Slow Script warning on bugzilla page when loading preview of large json file

---

Bugzilla/Constants.pm
extensions/BMO/Extension.pm
extensions/BMO/template/en/default/hook/bug/edit-custom_field.html.tmpl
extensions/BMO/template/en/default/hook/bug_modal/edit-custom_field-cf_crash_signature.html.tmpl
extensions/BMO/web/js/firefox-crash-table.js
public/metricsgraphics/js/main.js
qa/t/test_bmo_autolinkification.t

With [bug 618185](https://bugzilla.mozilla.org/show_bug.cgi?id=618185#c26) decision has been made to make crash-stats.mozilla.org canonical domain.
This PR is for [bug 1548725](https://bugzilla.mozilla.org/show_bug.cgi?id=1548725).
Made with:
```
git checkout -b crash-stats_org
find . -type f -print0 | xargs -0 sed -i 's,crash-stats.mozilla.com,crash-stats.mozilla.org,g'
git add * && git commit -m "Change crash-stats.mozilla.com to .org"
```

Bug 1548725 - Change crash signature & report links from crash-stats.mozilla.com to .org

---

Bugzilla/DB/Schema.pm
Bugzilla/Install/DB.pm

Adds a datetime `forget_after_date` field to the profiles table.
This field will be used when determining which unresponsive inactive users to forget periodically.
This field will be normally set to 30 days after BMO detects and notifies a user that has been "inactive"
for a very long time, thus, giving the user 30 days to respond to prevent being forgotten.
Another benefit of this datetime field is that we can choose to send reminder emails as their
forget-date approaches (we may choose not to do this for other reasons).
`forget_after_date`:
- If null, the user should not be forgotten.
- If set, the user can & should be forgotten at anytime after the set date.
- This field should be unset anytime the user logs in or specifically requests to not be forgotten.

Bug 1550145 - Add 'forget_after_date' field to profiles table (schema only)

---

extensions/BugModal/web/bug_modal.css

Make the text on module headers unselectable, so it won’t be selected especially when the header is long-tapped on mobile.
[Bug 1549287 - Ghost selection on modal module headers](https://bugzilla.mozilla.org/show_bug.cgi?id=1549287)

Bug 1549287 - Ghost selection on modal module headers

---

extensions/OpenGraph/template/en/default/hook/global/header-start.html.tmpl

Show the bug type and priority in Bugzilla link previews on Slack, etc.
[Bug 1545330 - Add bug type to open graph data on bug detail page.](https://bugzilla.mozilla.org/show_bug.cgi?id=1545330)

Bug 1545330 - Add bug type to open graph data on bug detail page.

---

Bugzilla/Markdown.pm
Bugzilla/Template.pm

Fix wrong comment links in email notifications. Currently it’s like 
```html
<a href="#c4”>Comment 4</a>
```
but with this fix, it will be 
```html
<a href="/show_bug.cgi?id=1521423#c4" title=“NEW - Links to comments are not correct in bugmail">Comment 4</a>
```
[Bug 1521423 - Links to comments are not correct in bugmail](https://bugzilla.mozilla.org/show_bug.cgi?id=1521423)

Bug 1521423 - Links to comments are not correct in bugmail

---

extensions/MyDashboard/lib/Queries.pm
extensions/MyDashboard/web/js/flags.js

Hide flags without a requestee from My Dashboard, including `in-testsuite?` and `qe-verify?`, so only important info will be displayed.
[Bug 1225902 - Show only flags with requestee in the "Flags You Have Requested" section](https://bugzilla.mozilla.org/show_bug.cgi?id=1225902)

Bug 1225902 - Show only flags with requestee in the "Flags You Have Requested" section

---

scripts/secbugsreport.pl
template/en/default/reports/email/security-risk.html.tmpl

`FILTER time` from Bugzilla's template helpers was inconsistent on
how it rendered the dates of the columns (due to different system
timezones that change based on where the code is being run).
This patch sets manually formats the time (since FILTER time always wants to convert to the local or user's timezone).

Bug 1540715 - Fix offset of historical dates in secbugs report

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1546502" target="_blank">1546502</a>] Miscellaneous tweaks and fixes for 2019 week 16</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1345750" target="_blank">1345750</a>] "Depends on" and "Blocks" bug lists should still show list of bug links in edit mode</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1544059" target="_blank">1544059</a>] Cloning a bug as a blocker doesn't copy the 'component' field</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1543741" target="_blank">1543741</a>] Blocklist requests getting filed as 'defect' instead of 'task' because of custom form</li>
<li>[<a …

bump version to 20190516.1

---

extensions/MyDashboard/template/en/default/pages/mydashboard.html.tmpl
extensions/MyDashboard/web/js/flags.js

I forgot to include this in #1274. My Dashboard now only shows requests, not all the flags, so the labels have to be updated accordingly. UX-wise it’s better to avoid using “flag” anyway because it’s jargon.
[Bug 1225902 - Show only flags with requestee in the "Flags You Have Requested" section](https://bugzilla.mozilla.org/show_bug.cgi?id=1225902)

Bug 1225902 follow up - Change labels on My Dashboard

---

Bugzilla/Bug.pm

There are duplicated changes in the `bugs_activity` table made at the same time by the same user or different users. Prevent these weird changes from being displayed in both the history UI and API. Tested with all the reported cases including the duplicated bugs. 
[Bug 1514000 - Suppress duplicated changes in bug history made at the same time mainly due to mid-air collisions](https://bugzilla.mozilla.org/show_bug.cgi?id=1514000)

Bug 1514000 - Suppress duplicated changes in bug history made at the same time mainly due to mid-air collisions

---

extensions/ProdCompSearch/lib/WebService.pm

Using selectall_arrayref to build the hash is much faster than using a while loop over single results.
Also avoiding the calls to `->type()`
Not related to performance, but using offsets returned by `localtime()` is discouraged. `Time::localtime` is a core module since 5.10 and has no real performance difference.

Bug 1523536 follow-up - improve performance

---

Bugzilla/Bug.pm
extensions/TrackingFlags/Extension.pm
query.cgi

Fix the **Search By Change History** section on the Advanced Search page not listing all the available fields due to unusable `editable_bug_fields()`. Simply list all fields just like Custom Search, then exclude several uneditable ones including Bug ID and Reporter. This is just an UI issue; searches have been possible if you build query manually.
[Bug 1283312 - Allow searching for bugs which have had a flag value (r?, needinfo?, r-, …) set for some period of time](https://bugzilla.mozilla.org/show_bug.cgi?id=1283312)

Bug 1283312 - Advanced Search page doesn’t list Flags and many other fields in Search By Change History

---

extensions/BMO/Extension.pm
extensions/BMO/template/en/default/hook/bug_modal/edit-after_modules.html.tmpl
extensions/BMO/web/js/firefox-crash-table.js

Let the Crash Table functionality use a cached version of [firefox_versions.json](https://product-details.mozilla.org/1.0/firefox_versions.json) if available, so an extra API request can be avoided.
[Bug 1543489 - Update firefox-crash-table.js to use cached firefox_versions.json](https://bugzilla.mozilla.org/show_bug.cgi?id=1543489)

Bug 1543489 - Update firefox-crash-table.js to use cached firefox_versions.json

---

js/attachment.js

Stop disabling the MIME type selector when text is added to the attachment uploader, so the user can select `text/html` or enter whatever manually.
[Bug 1553780 - Can't type/paste text into attachment contents and set text/html mimetype](https://bugzilla.mozilla.org/show_bug.cgi?id=1553780)

Bug 1553780 - Can't type/paste text into attachment contents and set text/html mimetype

---

Bugzilla.pm

<ul>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1225902" target="_blank">1225902</a>] Show only flags with requestee in the "Flags You Have Requested" section</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1552720" target="_blank">1552720</a>] Linkify bug summaries on My Dashboard query table</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1542554" target="_blank">1542554</a>] Add bug type icons to dependency trees</li>
<li>[<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1514000" target="_blank">1514000</a>] Suppress duplicated changes in bug history made at the same time mainly due to mid-air collisions</li>
<li>[<a …

bump version to 20190528.1

---

extensions/Needinfo/Extension.pm
extensions/Needinfo/template/en/default/bug/needinfo.html.tmpl
extensions/Needinfo/template/en/default/hook/bug/create/create-after_custom_fields.html.tmpl

Make it easier to request info on the Enter Bug page by adding a dedicated field. Currently it requires you to set the `needinfo?` flag hidden in the advanced fields, which is quite unintuitive.
[Bug 1376609 - Make needinfo field more visible when filing a new bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1376609)

Bug 1376609 - Make needinfo field more visible when filing a new bug

---

extensions/Splinter/web/splinter.css
extensions/Splinter/web/splinter.js
skins/standard/attachment.css
skins/standard/global.css

Apply the new skin to Splinter so it looks good even in the Dark Mode. The diff colour scheme is the same as the static diff page.
[Bug 1554521 - Dark mode makes Splinter nearly impossible to read](https://bugzilla.mozilla.org/show_bug.cgi?id=1554521)

Bug 1554521 - Dark mode makes Splinter nearly impossible to read

---

Bugzilla/Util.pm
js/util.js

Make relative dates sound more natural by saying Yesterday or Last hour/month/year.
[Bug 1543881 - Modify relative date labels like “a day ago” and “a year ago“](https://bugzilla.mozilla.org/show_bug.cgi?id=1543881)

Bug 1543881 - Modify relative date labels like “a day ago” and “a year ago“

---

docs/en/rst/api/core/v1/bug.rst

Fix the API doc mentioning multiple alias that is not supported in BMO and Bugzilla 6.0.
[Bug 1534307 - Remove wrongly mentioned multiple alias support from API doc](https://bugzilla.mozilla.org/show_bug.cgi?id=1534307)

Bug 1534307 - Remove wrongly mentioned multiple alias support from API doc

---

extensions/BMO/Extension.pm

Add redirects to external forms that were moved from BMO, including `form.dev-engagement-event` and `form.ipc`.
[Bug 1513644 - Redirect removed forms to proper destination whenever possible](https://bugzilla.mozilla.org/show_bug.cgi?id=1513644)

Bug 1513644 - Redirect removed forms to proper destination whenever possible

---

template/en/default/reports/email/security-risk.html.tmpl

The Sandstone theme change accidentally changed some styles in the
report email that wouldn't be able to benefit from the new theme.
This fix restores colors in the email.

no bug: Fix security bugs report colors

---

skins/standard/attachment.css

Show the `<textarea>` for **Edit Attachment As Comment** in a monospace font as before, so it’s easier to comment on a patch. It’s a regression from the new skin.
[Bug 1556306 - Edit Attachment As Comment now uses variable rather than fixed width font](https://bugzilla.mozilla.org/show_bug.cgi?id=1556306)

Bug 1556306 - Edit Attachment As Comment now uses variable rather than fixed width font

---

extensions/BugModal/web/bug_modal.js

Fix a regression where cancelling editing a bug to a 404 Not Found page.
[Bug 1556725 - Hitting Cancel button during edit mode leads to 404 page](https://bugzilla.mozilla.org/show_bug.cgi?id=1556725)

Bug 1556725 - Hitting Cancel button during edit mode leads to 404 page

---

Bugzilla/Bug.pm

Fix a summary update in history not appearing in the bug history due to a uppercase-to-lowercase change and case insensitive string comparison in MySQL. Just compare the removed and added values in the Perl code.
[Bug 1556320 - Mismatch between changed summary and current summary](https://bugzilla.mozilla.org/show_bug.cgi?id=1556320)

Bug 1556320 - Mismatch between changed summary and current summary

---

template/en/default/global/header.html.tmpl

Show the security issue banner on bugs restricted to the `core-security-release` and `pocket-security-sensitive` groups.
[Bug 1555847 - Bugs in core-security-release and pocket-security-sensitive groups have Confidential header, should be Security](https://bugzilla.mozilla.org/show_bug.cgi?id=1555847)

Bug 1555847 - Bugs in core-security-release and pocket-security-sensitive groups have Confidential header, should be Security

---

extensions/PhabBugz/lib/Feed.pm
extensions/PhabBugz/lib/Revision.pm

The new change will not update status if the revision is a draft and the status is 'changes-planned'. This happens when someone submits a review using 'moz-phab submit --wip'. Otherwise it should still do the old behavior of moving to 'needs-review'.
Bugzilla Link:
[Bug 1555409 - D32774 not moved out of Draft state](https://bugzilla.mozilla.org/show_bug.cgi?id=1555409)

Bug 1555409 - D32774 not moved out of Draft state
